### ISSUE TITLE
No css/scripts referenced inside index html

### ISSUE THREAD

**Issue by MartB** [hackmdio/codimd#1016]
My mainpage shows: 

```
<link href="" rel="stylesheet"><link href="" rel="stylesheet"><link href="" rel="stylesheet">
```

```
<script src="/config"></script><script src="" defer="defer"></script><script src="" defer="defer"></script>
```

Eventhough webpack seems to run without any errors.
I suspect this is related to the recent changes to webpack.

~Any pointers?~
Edit: found a fix that works for me.

**Comment by SISheogorath** [comment]
Can you check your webpack version that is used? And what version of CodiMD are you running? When it's latest master, please make sure you successfully upgraded to Webpack version 4.

**Comment by davidmehren** [comment]
I can't reproduce this in the current `master`.
When I try to apply @MartB s fix, everything breaks because the links look like `<link href="[object Object]" rel="stylesheet">`

**Comment by MartB** [comment]
daheck how are you installing webpack?

i nuked node_modules and ran npm install and it will not work.

**Comment by davidmehren** [comment]
Correction: I *can* reproduce this.
It seems to be our version definition of `"html-webpack-plugin": "^4.0.0-alpha"` (note the `^`).
This allows version `4.0.0-beta.2` to be installed, which needs the changed template.
My `yarn.lock` has prevented this upgrade, so I could not reproduce the error.

@MartB Do you want to amend your PR with `html-webpack-plugin` pinned to `4.0.0-beta.2` and an updated `yarn.lock`?

**Comment by MartB** [comment]
@davidmehren sure!

**Comment by MartB** [comment]
Done i hope i did it right heh.

**Comment by davidmehren** [comment]
I think we should remove the `^` in the version range, so while `html-webpack-plugin` is in beta, we don't get more surprises like this one.

Regarding Node 10: Some dependencies (I think it was `uws`) use native code and are not compatible with Node 10.

I'll do a PR to change the docs shortly.

**Comment by SISheogorath** [comment]
Much more important and breaks: scrypt.

But we already got a solution by ccoenen (don't want to mention him unneeded), just needs to be adapted for CodiMD. As soon as we fixed that, we should be compatible to node 10.

And about `yarn` vs. `npm install`: See #943 which already introduces such a change :)

But I should rewrite the setup script entirely as I realized lately.

**Comment by MartB** [comment]
The only thin i have to say about uws is = https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/

Im using the normal websocket module and i experienced no issues.
However im not using it on a large scale deployment.

@BackToTopic
I will change it.
