### ISSUE TITLE
I can't sign in by email with docker-hackmd!

### ISSUE THREAD

**Issue by aerodrogan** [hackmdio/codimd#1019]
Hi all,
I am newbie for program.
I try install the docker-hackmd on my NAS system.
It seems to work fine. But I can login with e-mail. 
It shown "Below is history from this browser" when I login with eamil.
Below is my config.json
```
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        }
    },
    "development": {
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        }
    },
    "production": {
        "domain": "nas-cs3",
		"port": "32791",
		"urlAddPort": true,
		"allowAnonymous": true,
		"allowAnonymousEdits": true,
		"email": true,
		"allowEmailRegister": true,
		
        "db": {
            "dialect": "sqlite",
            "storage": "/data/db.sqlite"
        },

    }
}
```

**Comment by aerodrogan** [comment]
HiSISheogorath ,
Thanks.
But I have no idea how to Use environment variables. Would you have some guide for me?

The config.json
```json
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        }
    },
    "development": {
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        }
    },
    "production": {
        "domain": "nas-cs3:32795",

        "db": {
            "dialect": "sqlite",
            "storage": "/data/db.sqlite"
        }
    }
}

```

I try to register a user via email.
![](https://codimd.s3.shivering-isles.com:443/demo/uploads/upload_3d9902741df5208d0e5c23da3991e912.png)

After login via e-mail, the page still shown as a guest note [+New guest note]
![](https://codimd.s3.shivering-isles.com:443/demo/uploads/upload_53f3a94af35eb06674256bc3fdc57e0f.png)

**Comment by SISheogorath** [comment]
You have to sign in after registering using the same credentials. Also we don't recommend to use local users.

To use environment variables with docker images, please check the official docker docs:

https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file
https://docs.docker.com/compose/compose-file/#environment

For the available variables see our README:

https://github.com/hackmdio/codimd#environment-variables-will-overwrite-other-server-configs
