### ISSUE TITLE
CodiMD should return 400 error when path contains subpath

### ISSUE THREAD

**Issue by jo-so** [hackmdio/codimd#1025]
I have *allowFreeURL* enabled. When I access a path with */abc/def*, CodiMD returns *503*. I should be an client error like *400*, as long as sub-paths aren't supported.

**Comment by SISheogorath** [comment]
I just double checked this on our demo instance: https://demo.codimd.org/meow/test

Results in a 404 which isn't perfect, but acceptable. Maybe something weird with your setup? Check that CodiMD isn't dying for whatever reason.

**Comment by SISheogorath** [comment]
And I realized that we don't use `allowFreeURL` on the demo instance. So I checked locally and codimd itself redirects me from `http://localhost:3000/test/meow` to `http://localhost:3000/test#`.

Seems like there is something in your setup.

**Comment by jo-so** [comment]
It must have been a mistake on my side. I've changed my config in the meantime and I can't reproduce this response 503 any longer.
