### ISSUE TITLE
Make robots.txt a special note

### ISSUE THREAD

**Issue by dsprenkels** [hackmdio/codimd#1052]
Currently, in freely mode, `/robots.txt` is editable as if it were a regular note. However, `robots.txt` has a special meaning for web browsers. Because of this my CodiMD server awkwardly has a `robots.txt` [page](https://codimd.dsprenkels.com/robots.txt) that was created by a bot some time ago.

Can we treat the `/robots.txt` note as a special note and return a HTTP `204 No Content` or `404 Not Found` status code?

**Comment by dsprenkels** [comment]
By the way, I am interested in trying to implement this myself, as a first 'Good beginner bug'.

**Comment by SISheogorath** [comment]
Mhm, right, that can happen in freeurl mode (which I still don't recommend to use but people want it :man_shrugging:).

I would actually considering to add a real robots.txt. Either as template, or as file.

Have a look at this code section for implementing it:

https://github.com/hackmdio/codimd/blob/3d1b138a31b9939143d9d6fa0cd94460061efcbd/lib/web/statusRouter.js#L94-L109

Consider to add an option to enable full blocking of indexing for the whole instance. I would not recommend to add blacklisting for individual notes there. You can already block indexing by [yaml-metadata](https://github.com/hackmdio/codimd/blob/master/public/docs/yaml-metadata.md#robots) and this way you don't expose note URLs.
