### ISSUE TITLE
CMD_USESSL is missing from README.md

### ISSUE THREAD

**Issue by dsprenkels** [hackmdio/codimd#1062]
`README.md` actually lists the json configuration option `useSSL`, but it does not list the corresponding environment variable `CMD_USESSL`, which is defined in `environment.js`.

I haven't checked for any other missing entries in the table.

**Comment by SISheogorath** [comment]
Along with that also `sslKeyPath` and its friends are missing.

**Comment by mmoya** [comment]
Documented in https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration. This can be closed.

**Comment by bakhtiarcr7** [comment]
the issue is solved yet or need still need some work, I want to contribute if there are any good first issues, please do let me know

**Comment by jackycute** [comment]
We recommend use nginx or other load balancer for SSL offloading.
Please read more at: https://hackmd.io/s/codimd-configuration#SSL
