### ISSUE TITLE
Support export as a revision of an existing Gist

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#108]
>  https://twitter.com/csuwildcat/status/725029409216942081

**Comment by rlouf** [comment]
Similar to #114?

**Comment by jackycute** [comment]
No really, this can be a separated enhancement for current exist `export to gist` feature.

**Comment by ccoenen** [comment]
this has been marked as "enhancement" for two years, I don't believe it will be added any time soon. If someone wants to work on it, it will probably get merged. Until then, I'm closing it.
