### ISSUE TITLE
how can we reference math equations or figures?

### ISSUE THREAD

**Issue by joamatab** [hackmdio/codimd#1093]
what is the recommended way to reference math equations or figures?

**Comment by SISheogorath** [comment]
Where do you want to reference them?

Within the document? External sources?

We allow to use html, so the simplest way is to add a tag with an ID infront and linking to this id.

```
<span id="my-math"></span>

$$
Some MathJax
$$
```

And later in your document you can reference back:

```
<a href="#my-math">
```

Hope that's what you searching for.

**Comment by ccoenen** [comment]
I'll close this for now. Feel free to comment on it if you feel it's not resolved, yet!

**Comment by joamatab** [comment]
how could we add auto-numbering to the equations so we can refer to them later?

in latex you can do:

\begin{equation}
L(x)  = \frac{1}{1+jx}
\label{eq:Lx}
\end{equation}

and then \ref(eq:Lx)
