### ISSUE TITLE
Feature: Restrict GitHub login to specific org

### ISSUE THREAD

**Issue by arthur-c** [hackmdio/codimd#1099]
It would be great to be able to restrict login to only a single GitHub organization (or a list), and disable all other auth methods

**Comment by ssmaithili** [comment]
Hey I am a beginner, I would love to contribute, can you point me on how to get started?

**Comment by HarshPanchal26** [comment]
Hey are you still Working on a project , I am new to open source community , So if  you need any help then let me know , I will try my best.

**Comment by Narcos101** [comment]
hey @arthur-c  is this issue still open?

**Comment by flotaro** [comment]
I will fix this one.

**Comment by jackycute** [comment]
This has been implemented in #1710
