### ISSUE TITLE
mattermost oauth2 behind reverse proxy

### ISSUE THREAD

**Issue by amasson84** [hackmdio/codimd#1104]
Hello
I have been looking for a while now and I don't find how to have it working so far here is what I'm trying to do.
I have a single physical server (running proxmox) with virtual machine and containers

I have a codimd docker working on a virtual machine (ip 192.168.10.32 port 3000) and a mattermost container (ip 192.168.10.15 port 8065)
both are behind  a reverse proxy (another containers 192.168.10.10 with apache), this reverse proxy associate a particular domain to each service and put the ssl encryption (with let's encrypt)

the codimd can then be accessible from the outside with hmd.mydomain.com and the matermost with mm.mydomain.com

Everything works fine except now I would like to use oauth2 to connect codimd to the mattermost and I get a internal server error because codimd cannot have a token `InternalOAuthError: Failed to obtain access token`

I followed the configuration for the auth with mattermost.

here is the config for codimd 
 ```
     - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_DOMAIN=hmd.mydomain.com
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
      - CMD_OAUTH2_PROVIDERNAME=mm
      - CMD_OAUTH2_USER_PROFILE_URL=https://mm.mydomain.com/api/v4/users/me
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=id
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=username
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=https://mm.mydomain.com/oauth/access_token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://mm.mydomain.com/oauth/authorize
      - CMD_OAUTH2_CLIENT_ID=xxx
      - CMD_OAUTH2_CLIENT_SECRET=yyy
      - DEBUG=false
```

and the hdm apache configuration
ServerName  ${host}

```
<VirtualHost *:443>
        #...(hostname stuff)
ProxyPreserveHost On
ProxyRequests Off
  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /(.*) ws://${ip}:${port}/$1 [P,L]
ProxyPass / http://${ip}:${port}${folder}
ProxyPassReverse / http:/${ip}:${port}
<Proxy *>
Order deny,allow
Allow from all
</Proxy>

SSLCertificateFile /etc/letsencrypt/live/${host}/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/${host}/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

</VirtualHost>

```

I'm almost sure the problem comes from the proxy but I didn't find what to change in order to work. If someone can help me it would be very nice :)

**Comment by SISheogorath** [comment]
Have you made sure you can access the reverse proxy from the codimd container?

I guess that codimd is unable to contact your Mattermost instance.

**Comment by amasson84** [comment]
@SISheogorath that was the problem I didn't think of checking that and my firewall was blocking the connection (it's a new system I'm using)
it's working fine thank you very much :)
