### ISSUE TITLE
[refactor] Replace blueimp-md5 with nodejs internal MD5

### ISSUE THREAD

**Issue by dsprenkels** [hackmdio/codimd#1106]
https://github.com/hackmdio/codimd/blob/007f25227358f7ee697a2cf87364830f4569583d/lib/letter-avatars.js#L3

In (^), CodiMD uses a dedicated module `'blueimp-md5'` for MD5 hashing. However, OpenSSL already exposes MD5 and is included in NodeJS. We can remove this dependency by just using the standard library.

I would be happy to implement this myself.

**Comment by SISheogorath** [comment]
Sounds great. We just just test that it works with the whole range of node versions that we support (namely node 6).

:+1:
