### ISSUE TITLE
Fallback for CDN issues

### ISSUE THREAD

**Issue by urakagi** [hackmdio/codimd#1111]
Hi, `cdnjs.com` has a problem and is not fixed for three days: https://github.com/cdnjs/cdnjs/issues/13165
Since the CDN service looks not very reliable, is there a plan to add a fallback when CDN fails or just use local files?

**Comment by jackycute** [comment]
Hi @urakagi, you could specify `CMD_USECDN=false` and restart server, it should use local bundle resources instead.

**Comment by urakagi** [comment]
Thank you very much :)

**Comment by gramakri** [comment]
This unfortunately broke all the Cloudron CodiMD installations as well. I have pushed an update that disables CDN.

@jackycute @SISheogorath  Is there a chance we can disable CDN by default. If I am not mistaken, I think even non-Cloudron installations will be broken by default as it right now (until cdnjs is fixed).
