### ISSUE TITLE
photo pasting glitch (or feature)

### ISSUE THREAD

**Issue by racterub** [hackmdio/codimd#1122]
Hi, idk I should use mandarin or english here :/

I've encounter a glitch which occurs when I tried to paste on codimd.
While pasting images, codimd will also paste the photo original urls, but hackmd won't.
I don't know this is a feature or a bug, but it's kind of annoying 😅 

Here's the screenshot of hackmd and codimd:
![image](https://user-images.githubusercontent.com/20561837/51434469-d9237900-1c9b-11e9-9ac6-8a2caf20dd92.png)
![image](https://user-images.githubusercontent.com/20561837/51434472-de80c380-1c9b-11e9-9959-bf1224c7922a.png)

**Comment by racterub** [comment]
Hmm
After restarting server, it disappear :/

**Comment by racterub** [comment]
Answer: We should use the original url.

After reading your comments I realize the reason about this issue is the way I'm using it,
I should use markdown to attach the existed images on the web :/ .

**Comment by ccoenen** [comment]
If I paste a URL, I wouldn't expect CodiMD messing with it. At least not automatically.

**Comment by SISheogorath** [comment]
GitHub for example proxies all embedded pictures to prevent user tracking and similar
