### ISSUE TITLE
Support Node 10 and beyond

### ISSUE THREAD

**Issue by kindfulkirby** [hackmdio/codimd#1132]
CodiMD does not seem to run in Node 10 or newer (according to the README and a quick, informal test), but Node 9 is already EOL and Node 8 (the LTS version) will be in December.

I don't know anything about Node, but that would seem to be a problem?

**Comment by SISheogorath** [comment]
We are already working on Node 10 support. And most things actually work, there are only little hickups left, like this one: https://github.com/hackmdio/codimd/pull/1127

So in theory you can already run CodiMD on node 10. For best stability we still recommend to use node 8.15.0.

**Comment by Ppjet6** [comment]
Hey, I'm curious about the status of this ticket. The PR linked seems to be merge, any ETA/list of missing features?

**Comment by jackycute** [comment]
We already support Node.js version 10.
