### ISSUE TITLE
Add an option to delete the permission that guests can view

### ISSUE THREAD

**Issue by hakoai** [hackmdio/codimd#1144]
hi,
There are `allowAnonymous` and `allowAnonymousEdits` for changing the authority of the guest, but there is no setting to prohibit guest viewing.

I suppose I can create a patch.  (`allowAnonymousViews=false`)
* hide `New guest note` button
* hide `freely`, `editable` and `locked` permission

Is it possible to add this patch? Thanks.

**Comment by hakoai** [comment]
| allowAnonymous | allowAnonymousEdits | allowAnonymousViews | `New guest note` button | `freely` permission | `editable/locked` permission | 
| -------- | -------- | -------- | -------- | -------- | -------- |
| true | - | - | active | active | active |
| false | - | false | inactive | inactive | inactive |
| false | false | true | inactive | inactive | active |
| false | true | true | inactive | active | active |

**Comment by SISheogorath** [comment]
Sorry for reaching out so late, I was quite sure to have already answered that. Had some busy week. The proposal looks good, I would like to see such implementation.

On the other hand, we may rework the entire permission this year, so if you want to work on the bigger step, then I guess this would be a way to go for you! Of course, before we can get our hands on the permissions, we probably need to work on the account system. But depending on your preferences, every helping hand is very welcome!
