### ISSUE TITLE
Question: Is Commenting on the View Mode available?

### ISSUE THREAD

**Issue by Mulkave** [hackmdio/codimd#1146]
Running CodiMD using the [container repo](https://github.com/hackmdio/codimd-container) with `docker-compose-up` and I do not see it possible to comment on a note as done on hackmd.io even when logged in. Am I missing something?

![screenshot 2019-02-14 at 2 15 13 pm](https://user-images.githubusercontent.com/2647333/52786233-07aa2f00-3063-11e9-81cd-dc9793f9eddf.png)

**Comment by ccoenen** [comment]
HackMD and CodiMD are two separate things. CodiMD currently has no commenting feature. We've discussed this and other things on and off for CodiMD, but so far no clear winner has emerged.

If this does not fully anwer your question, please feel free to continue discussion here.
