### ISSUE TITLE
Sessions are only preserved over short timespans on my Heroku (free) deployed Codimd instance even though CMD_SESSION_LIFE is set to very long.

### ISSUE THREAD

**Issue by rmst** [hackmdio/codimd#1151]
Hi, the issue is stated in the title. I have to log in again after quite short periods of time. I should emphasize that I am using Heroku free so the instance spins down after 30min of inactivity. Perhaps the sessions aren't preserved over spin downs? How could I improve this?

**Comment by SISheogorath** [comment]
Have you set the `CMD_SESSION_SECRET`? The Session secret is used to encrypt the session key and is, given that you didn't set it explicitly, re-generated on each start, which could explain the problem.

**Comment by rmst** [comment]
No I didn't set CMD_SESSION_SECRET! Thank you!

**Comment by diablov** [comment]
If changed CMD_SESSION_LIFE，you should change CMD_SESSION_SECRET，otherwise the cookie time limit would not change。
