### ISSUE TITLE
Using emoji breaks HTML export

### ISSUE THREAD

**Issue by dhavlik** [hackmdio/codimd#1164]
In our instance running 1.3.0, after adding an emoji to the content of a pad, HTML export is no longer working:

`TypeError: r is undefined`

The error is triggered by [this code](https://github.com/hackmdio/codimd/blob/de0acbb566b3a9be095c414bf15edb734ac755be/public/js/extra.js#L606
):
```javascript
  src.find('img.emoji').each((key, value) => {
    let name = $(value).attr('alt')
```
Looking at the DOM, it seems emojis do not get an alt-attribute. After adding it in inspector, the HTML export works.

Seems like the issue here is that the emojis don't get the alt-attr. I tried to find out where emojis are added, but couldn't locate the piece of code.

**Comment by ccoenen** [comment]
I can confirm this issue on our demo instance. This document here can't be exported via menu -> HTML.

https://demo.codimd.org/LYPSOcwpQqGS7F120FuJHA#

Personally, I dislike the way it's handled: after downloading the document it's then dependent on some odd CDN being available for all time. Maybe we can fix this at the same time.
