### ISSUE TITLE
flowchart 版本低

### ISSUE THREAD

**Issue by Lursun** [hackmdio/codimd#1167]
```flow
st=>start: Start|past:>http://www.google.com[blank]
e=>end: End|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes
or No?|approved
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
```

呈現 
![image](https://user-images.githubusercontent.com/11616295/54260057-d6aa1500-45a2-11e9-99c8-3b6c79c62337.png)
而非
![image](https://user-images.githubusercontent.com/11616295/54260224-491af500-45a3-11e9-864f-dcb2be1c7f74.png)

來源連結：https://flowchart.js.org/

**Comment by Lursun** [comment]
誤會了，沒事

**Comment by SISheogorath** [comment]
:upside_down_face: Sorry, but we can only support you, when you can provide your questions in english.

It seems like a misunderstanding about how flowchart works, as you have to define the colors in your flowchart code. We support that. In the example code they provide the colors in the function call during initialization of the diagram.

**Comment by ccoenen** [comment]
Here's a [CodiMD Flowchart example with style](https://demo.codimd.org/QZT8FvroRL2HFLLNNwPamQ) taken from [this example](https://github.com/adrai/flowchart.js/blob/master/example/index.html#L77-L98)

**Comment by Yukaii** [comment]
We've upgraded flowchart.js [recently](https://github.com/hackmdio/codimd/pull/1226). Open a new issue if you still have other problems. 👍
