### ISSUE TITLE
Permissions of Upload-Directory

### ISSUE THREAD

**Issue by dbrgn** [hackmdio/codimd#1173]
I'm running CodiMD in a Docker container, but have mounted the uploads to a directory on the host. There, I serve the uploads directly through Nginx for performance and caching reasons:

    location /uploads/ {
        alias /srv/docker/hackmd/uploads/;
        expires 30d;
    }

Since 1.3(?) every time I restart the container, the permissions of the `/codimd/public/uploads` directory are reset from `drwxr-xr-x` to `drwx------`. Of course this means that Nginx will get a "403 Forbidden" response.

Is this permission change necessary?

**Comment by SISheogorath** [comment]
Please see https://github.com/hackmdio/codimd-container/issues/25

I already created a branch that solves this problem, just didn't find the the time to test and merge it :)

**Comment by dbrgn** [comment]
Thanks @SISheogorath, I didn't see that issue :slightly_smiling_face:
