### ISSUE TITLE
Edit mode but only with the output of Markdown

### ISSUE THREAD

**Issue by rodrigocipriani** [hackmdio/codimd#1185]
I've used HackMD with people that don't really work with IT, so they not feel so well when they see Markdown Tags.  🤦‍♂️

So I've the idea to use the editor with top bar in edition mode but not showing the MD code.

What do you think about?

**Comment by HerHde** [comment]
A [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) editor? Although I hate them and their output this idea is good, especially for beginners.

**Comment by rodrigocipriani** [comment]
not a full WYSIWYG really ... very similar, but the output is MD, understood?

**Comment by heyakyra** [comment]
You mean WYSIWYM (What You See Is What You Mean) which is maybe pretty similar to semantic WYSIWYG: https://www.456bereastreet.com/archive/200612/forget_wysiwyg_editors_use_wysiwym_instead/

There are many editors available. Could look to what https://github.com/Requarks/wiki or https://github.com/taigaio/taiga-front uses for their wiki editing functionality

**Comment by jackycute** [comment]
Hi everyone, thanks for helping us address this.
This project will remain focus on plain text editor experience. WYSIWYG is way too much UIs and states to maintain, the closest solution might be making a theme let the editor looks very close to WYSIWYG.
