### ISSUE TITLE
image post error 

### ISSUE THREAD

**Issue by junlicn** [hackmdio/codimd#1186]
I setup hackmd by docker.  
when I paste a image, the UI display:  ![Uploading file..._kce8uwpvk]() 
and the docker-compose up console display error:

> 

app_1       | 2019-04-07T14:01:46.264Z - info: ::ffff:223.72.77.131 - - [07/Apr/2019:14:01:46 +0000] "POST /uploadimage HTTP/1.1" - - "http://bttracker.top:3000/7z4WWTt3Q36ZLmRPs8wR9Q?both" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
app_1       | 
app_1       | 2019-04-07T14:01:54.049Z - error:  Error: Error: connect ETIMEDOUT 31.13.74.1:443
app_1       |     at /hackmd/lib/web/imageRouter/imgur.js:26:14
app_1       |     at _rejected (/hackmd/node_modules/q/q.js:864:24)
app_1       |     at /hackmd/node_modules/q/q.js:890:30
app_1       |     at Promise.when (/hackmd/node_modules/q/q.js:1142:31)
app_1       |     at Promise.promise.promiseDispatch (/hackmd/node_modules/q/q.js:808:41)
app_1       |     at /hackmd/node_modules/q/q.js:624:44
app_1       |     at runSingle (/hackmd/node_modules/q/q.js:137:13)
app_1       |     at flush (/hackmd/node_modules/q/q.js:125:13)
app_1       |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
app_1       |     at process._tickCallback (internal/process/next_tick.js:181:9)
app_1       | 2019-04-07T14:03:16.996Z - info: deserializeUser: 986f5dfe-e410-4f76-b58f-cafaa90d4d9b

**Comment by jackycute** [comment]
Hi @junlicn 
What the size of the image you were uploading?
What's the timeout of your load balancer?

It looks like it took too long to upload the image thus causing timeout.
Might need more information to investigate.

**Comment by jackycute** [comment]
Close for now, feel free to re-open if you can provide more info.
