### ISSUE TITLE
allow raw view of code + enable CORS (so browsers can `fetch` content from hackmd documents)

### ISSUE THREAD

**Issue by serapath** [hackmdio/codimd#1189]
allow raw view of code + enable CORS (so browsers can `fetch` content from hackmd documents)

In gituhub repositories, files have a button `raw` which, when clicked, opens a link that shows the file content without any formatting. This is very convenient when people want to write websites which fetch raw content (e.g. a json file from a github repository) directly.

It would be cool if hackmd would enable this, so users can use hackmd to update certain data or configuration files by hand and websites automatically fetch - and eventually even try older versions too :-)

e.g.
```js
;(async () => {
  const text = await fetch('https://hackmd.io/tutorials?raw').then(response => response.text())
  console.log(text)
})()
```

**Comment by jackycute** [comment]
Hi @serapath 
Thanks for asking.

Could you try `/download` API, you can add it after the note link like: `https://hackmd.io/features/download`

**Comment by serapath** [comment]
fantastic, that works :-) thx
