### ISSUE TITLE
Migration didn't return a promise

### ISSUE THREAD

**Issue by zkaiq** [hackmdio/codimd#1197]
I got a error when i run "node_modules/.bin/sequelize db:migrate", the error is
"ERROR: Migration 20171009121200-longtext-for-mysql.js (or wrapper) didn't return a promise"
how can i fix it?

**Comment by jackycute** [comment]
Hi @zkaiq,
Thanks for reporting, could you please try if above PR fix this issue?

**Comment by bitinerant** [comment]
After receiving this error, the [above-mentioned PR](https://github.com/hackmdio/codimd/pull/1199/commits/fc642e0d14983279eeccb0d68fbb82981e85c58e) fixed this error for me. Thank you.

**Comment by sufyansalim** [comment]
how exactly was it fixed can someone explain?
