### ISSUE TITLE
Permissions - Editable

### ISSUE THREAD

**Issue by wattwood** [hackmdio/codimd#1203]
If allowAnonymouse is false, allowAnonymousEdits is false, and allowEmailRegister is false, an anonymous user on a document with the permission of 'Editable' will be prompted to sign-in or register when they attempt to modify the document.

I am working to lock this down to specific team individuals for all access; we don't want anyone that isn't signed in to be able to see anything.  Is there a way to adjust the allowed permissions on documents?  I can see that I can set a default. I'd like to limit to `Limited`, `Protected` and `Private`.  

<img width="347" alt="Screen Shot 2019-04-22 at 3 03 46 PM" src="https://user-images.githubusercontent.com/1388178/56531024-8f536480-6510-11e9-9aa2-49346ba2ba80.png">

**Comment by jackycute** [comment]
Maybe you're looking for PR #1152 ?

**Comment by jackycute** [comment]
I will close this issue since it looks like you're requesting for PR #1152 
Re-open if you have other idea, thank you!
