### ISSUE TITLE
Heroku one click deployment not working

### ISSUE THREAD

**Issue by zhampu** [hackmdio/codimd#1206]
Here the full log

`VIPS app detected
-----> Installing libvips
       Downloading libvips and unpacking
       libvips installed
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=8.0.0
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=8.0.0...
       Downloading and installing node 12.0.0...
       Using default npm version: 6.9.0
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.15.2)...
       Installed yarn 1.15.2
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.15.2
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       error /tmp/build_c5f23507515a78b99f7226d811b2720a/node_modules/scrypt: Command failed.
       Exit code: 1
       Command: node-gyp rebuild
       Arguments: 
       Directory: /tmp/build_c5f23507515a78b99f7226d811b2720a/node_modules/scrypt
       Output:
       make: Entering directory '/tmp/build_c5f23507515a78b99f7226d811b2720a/node_modules/scrypt/build'
         SOLINK_MODULE(target) Release/obj.target/copied_files.node
         COPY Release/copied_files.node
         CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
         CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
         CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
         CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
         AR(target) Release/obj.target/scrypt_wrapper.a
         COPY Release/scrypt_wrapper.a
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
         CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
         AR(target) Release/obj.target/scrypt_lib.a
         COPY Release/scrypt_lib.a
         CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
         CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h: In constructor ‘NodeScrypt::Params::Params(const v8::Local<v8::Object>&)’:
       ../src/node-boilerplate/inc/scrypt_common.h:39:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
              N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
                                                       ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h:39:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
              N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
                                                                      ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                                ^~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h:40:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
              r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
                                                       ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h:40:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
              r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
                                                                      ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                                ^~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h:41:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
              p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
                                                       ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                        from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_common.h:41:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
              p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
                                                                      ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                                ^~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
                        from ../src/node-boilerplate/scrypt_params_async.cc:4:
       ../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
       ../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
              callback->Call(1, argv);
                                    ^
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
       ../../nan/nan.h:1674:3: note: declared here
          Call(int argc, v8::Local<v8::Value> argv[]) const {
          ^~~~
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
       ../src/node-boilerplate/inc/scrypt_params_async.h: In constructor ‘ScryptParamsAsyncWorker::ScryptParamsAsyncWorker(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/node-boilerplate/inc/scrypt_params_async.h:35:36: error: no matching function for call to ‘v8::Value::NumberValue()’
              maxtime(info[0]->NumberValue()),
                                           ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2564:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                              ^~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
       ../src/node-boilerplate/inc/scrypt_params_async.h:36:39: error: no matching function for call to ‘v8::Value::NumberValue()’
              maxmemfrac(info[1]->NumberValue()),
                                              ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2564:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                              ^~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
       ../src/node-boilerplate/inc/scrypt_params_async.h:37:36: error: no matching function for call to ‘v8::Value::IntegerValue()’
              maxmem(info[2]->IntegerValue()),
                                           ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2565:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                               ^~~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
       ../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: no matching function for call to ‘v8::Value::IntegerValue()’
              osfreemem(info[3]->IntegerValue())
                                              ^
       In file included from /app/.node-gyp/12.0.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:2565:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                               ^~~~~~~~~~~~
       /app/.node-gyp/12.0.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
       ../src/node-boilerplate/scrypt_params_async.cc: In member function ‘virtual void ScryptParamsAsyncWorker::HandleOKCallback()’:
       ../src/node-boilerplate/scrypt_params_async.cc:23:67: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
          obj->Set(Nan::New("N").ToLocalChecked(), Nan::New<Integer>(logN));
                                                                          ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3359:26: note: declared here
                            bool Set(Local<Value> key, Local<Value> value));
                                 ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../src/node-boilerplate/scrypt_params_async.cc:24:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
          obj->Set(Nan::New("r").ToLocalChecked(), Nan::New<Integer>(r));
                                                                       ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3359:26: note: declared here
                            bool Set(Local<Value> key, Local<Value> value));
                                 ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../src/node-boilerplate/scrypt_params_async.cc:25:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
          obj->Set(Nan::New("p").ToLocalChecked(), Nan::New<Integer>(p));
                                                                       ^
       In file included from /app/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.0.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.0.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/node-boilerplate/scrypt_params_async.cc:1:
       /app/.node-gyp/12.0.0/include/node/v8.h:3359:26: note: declared here
                            bool Set(Local<Value> key, Local<Value> value));
                                 ^
       /app/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       ../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
          callback->Call(2, argv);
                                ^
       In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
       ../../nan/nan.h:1674:3: note: declared here
          Call(int argc, v8::Local<v8::Value> argv[]) const {
          ^~~~
       scrypt.target.mk:127: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
       make: Leaving directory '/tmp/build_c5f23507515a78b99f7226d811b2720a/node_modules/scrypt/build'
       make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_c5f23507515a78b99f7226d811b2720a/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
       gyp ERR! System Linux 4.4.0-1038-aws
       gyp ERR! command "/tmp/build_c5f23507515a78b99f7226d811b2720a/.heroku/node/bin/node" "/tmp/build_c5f23507515a78b99f7226d811b2720a/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_c5f23507515a78b99f7226d811b2720a/node_modules/scrypt
       gyp ERR! node -v v12.0.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

**Comment by tomgoto** [comment]
I found out that Node v12 is used while building which is not compatible with CodiMD.

```
Downloading and installing node 12.0.0...
```

I edited `package.json` to limit the node version. Now building passes. :)
```
  "engines": {
    "node": ">=8.0.0 <12.0.0"
  },
```

**Comment by Yukaii** [comment]
@tomgoto Would you like to open a PR for this?

**Comment by tomgoto** [comment]
@Yukaii Ok, I'm writing a samll PR for this.

**Comment by tomgoto** [comment]
Deploying to heroku went successful, but another error stops starting app.

```
2019-08-13T03:25:10.571531+00:00 heroku[web.1]: Starting process with command `npm start`
2019-08-13T03:25:12.739163+00:00 heroku[web.1]: State changed from starting to crashed
2019-08-13T03:25:12.746202+00:00 heroku[web.1]: State changed from crashed to starting
2019-08-13T03:25:12.642026+00:00 app[web.1]: 
2019-08-13T03:25:12.642046+00:00 app[web.1]: > codimd@1.3.1 start /app
2019-08-13T03:25:12.642047+00:00 app[web.1]: > sequelize db:migrate && node app.js
2019-08-13T03:25:12.642049+00:00 app[web.1]: 
2019-08-13T03:25:12.651395+00:00 app[web.1]: sh: 1: sequelize: not found
2019-08-13T03:25:12.655527+00:00 app[web.1]: npm ERR! file sh
2019-08-13T03:25:12.655733+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-08-13T03:25:12.655900+00:00 app[web.1]: npm ERR! errno ENOENT
2019-08-13T03:25:12.656066+00:00 app[web.1]: npm ERR! syscall spawn
2019-08-13T03:25:12.657297+00:00 app[web.1]: npm ERR! codimd@1.3.1 start: `sequelize db:migrate && node app.js`
2019-08-13T03:25:12.657408+00:00 app[web.1]: npm ERR! spawn ENOENT
2019-08-13T03:25:12.657606+00:00 app[web.1]: npm ERR!
2019-08-13T03:25:12.657740+00:00 app[web.1]: npm ERR! Failed at the codimd@1.3.1 start script.
2019-08-13T03:25:12.657885+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-08-13T03:25:12.665444+00:00 app[web.1]: 
2019-08-13T03:25:12.665570+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-08-13T03:25:12.665634+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-08-13T03_25_12_659Z-debug.log
2019-08-13T03:25:12.724094+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by tomgoto** [comment]
Deploying to heroku went successful, but starting app stopped with an error.
```
2019-08-13T03:54:27.598099+00:00 heroku[web.1]: Starting process with command `npm start`

2019-08-13T03:54:30.465172+00:00 app[web.1]: 

2019-08-13T03:54:30.465202+00:00 app[web.1]: > codimd@1.3.1 start /app

2019-08-13T03:54:30.465206+00:00 app[web.1]: > sequelize db:migrate && node app.js

2019-08-13T03:54:30.465208+00:00 app[web.1]: 

2019-08-13T03:54:31.076002+00:00 app[web.1]: 

2019-08-13T03:54:31.079422+00:00 app[web.1]: [4mSequelize CLI [Node: 11.15.0, CLI: 5.4.0, ORM: 5.3.5][24m

2019-08-13T03:54:31.079523+00:00 app[web.1]: 

2019-08-13T03:54:31.118159+00:00 app[web.1]: Options:

2019-08-13T03:54:31.118164+00:00 app[web.1]:   --help             Show help  [boolean]

2019-08-13T03:54:31.118167+00:00 app[web.1]:   --version          Show version number  [boolean]

2019-08-13T03:54:31.118169+00:00 app[web.1]:   --env              The environment to run the command in  [string] [default: "development"]

2019-08-13T03:54:31.118171+00:00 app[web.1]:   --config           The path to the config file  [string]

2019-08-13T03:54:31.118173+00:00 app[web.1]:   --options-path     The path to a JSON file with additional options  [string]

2019-08-13T03:54:31.118181+00:00 app[web.1]:   --migrations-path  The path to the migrations folder  [string] [default: "migrations"]

2019-08-13T03:54:31.118184+00:00 app[web.1]:   --seeders-path     The path to the seeders folder  [string] [default: "seeders"]

2019-08-13T03:54:31.118186+00:00 app[web.1]:   --models-path      The path to the models folder  [string] [default: "models"]

2019-08-13T03:54:31.118188+00:00 app[web.1]:   --url              The database connection string to use. Alternative to using --config files  [string]

2019-08-13T03:54:31.118190+00:00 app[web.1]:   --debug            When available show various debug information  [boolean] [default: false]

2019-08-13T03:54:31.118192+00:00 app[web.1]:   --to               Migration name to run migrations until  [string]

2019-08-13T03:54:31.118194+00:00 app[web.1]:   --from             Migration name to start migrations from (excluding)  [string]

2019-08-13T03:54:31.118228+00:00 app[web.1]: 

2019-08-13T03:54:31.118315+00:00 app[web.1]: Unknown argument: dialect

2019-08-13T03:54:31.130786+00:00 app[web.1]: npm ERR! code ELIFECYCLE

2019-08-13T03:54:31.131173+00:00 app[web.1]: npm ERR! errno 1

2019-08-13T03:54:31.132525+00:00 app[web.1]: npm ERR! codimd@1.3.1 start: `sequelize db:migrate && node app.js`

2019-08-13T03:54:31.132628+00:00 app[web.1]: npm ERR! Exit status 1

2019-08-13T03:54:31.132827+00:00 app[web.1]: npm ERR! 

2019-08-13T03:54:31.132952+00:00 app[web.1]: npm ERR! Failed at the codimd@1.3.1 start script.

2019-08-13T03:54:31.133032+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

2019-08-13T03:54:31.140925+00:00 app[web.1]: 

2019-08-13T03:54:31.141243+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:

2019-08-13T03:54:31.141404+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-08-13T03_54_31_134Z-debug.log
```

**Comment by jackycute** [comment]
It seems like it's lacking of DB URL, could you check?

**Comment by tomgoto** [comment]
@jackycute 
Removing `dialect` from .sequelizerc went successful.
Probably because `url` includes `dialect` in heroku environment.

**Comment by tomgoto** [comment]
I'm checking again, if it went successful I'll write a PR

**Comment by tomgoto** [comment]
The same commit went successful in master branch didn't succeed in dev branch.
It looks like `bin/heroku` wasn't ran , which leads to lack of `.sequelizerc` and `config.json`.
I will dig further tomorrow.

**Comment by tomgoto** [comment]
@jackycute 
I finally successfully deployed to heroku, would you please check PR #1255?
thank you.
