### ISSUE TITLE
Cannot scroll past end of editor when window is narrow

### ISSUE THREAD

**Issue by jimbo1qaz** [hackmdio/codimd#1207]
Given a wide window, I can scroll past the end of the editor view. When I make the window horizontally narrow (by snapping the window to the left half of my screen), I can no longer do this, making editing the bottom of a document difficult, especially difficult because https://github.com/hackmdio/codimd/issues/617 (the bottom line is covered by the bottom bar).

This may happen at similarly narrow widths where "text+preview" mode is disabled, and only text or preview is allowed.

Is it possible to always enable scrolling past the bottom?

hackmd.io, Firefox 67.0b8 on Kubuntu, 1920x1080 with 1.3x scale.

**Comment by jackycute** [comment]
Hi @jimbo1qaz 
Could you share your screenshot?
And are you using hackmd.io or self-hosted CodiMD?

**Comment by jimbo1qaz** [comment]
hackmd.io

Narrow: ![Narrow screenshot](https://user-images.githubusercontent.com/913957/56702050-e6933980-66b6-11e9-99e9-9bf4d9e2219b.png)

Wide: 
![Wide screenshot](https://user-images.githubusercontent.com/913957/56702063-fa3ea000-66b6-11e9-9bc0-40101781579d.png)

**Comment by jackycute** [comment]
Thanks for reporting to us @jimbo1qaz!

**Comment by jimbo1qaz** [comment]
https://github.com/hackmdio/codimd/blob/master/public/js/index.js#L555
https://github.com/hackmdio/codimd/blob/4e596d724dcb1a5a19ab1e75df250767334ebfc9/public/js/index.js#L555

Apparently, JS observing a CSS selector is responsible for switching to single-pane-only view on narrow screens. I confirmed that it happens at exactly the same window width that "overscrolling" is disabled.

https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/scrollpastend.js is *not* used by hackmd.io. `editor.getOption("scrollPastEnd")` returns `undefined` and `editor.setOption("scrollPastEnd", true or false)` does nothing.

**Comment by jackycute** [comment]
Hi @jimbo1qaz 
Thanks for letting me know that the existence of scrollPastEnd addon.
Will add that soon!

**Comment by jimbo1qaz** [comment]
I didn't ask to add the addon (unless you want to replace your existing code handling that). But somehow you already have "scroll past end" functionality implemented independently of the add-on, but it gets turned off on narrow windows.

**Comment by jackycute** [comment]
Yeah, so I did check the `visibleXS` in the implementation of "scroll past end" function and this will be fixed.

**Comment by jimbo1qaz** [comment]
seems to be fixed?
