### ISSUE TITLE
https://demo.codimd.org/ is down?

### ISSUE THREAD

**Issue by jdhao** [hackmdio/codimd#1208]
I am using this website to store my note. But it seems that I can access it now. It shows:

> Error 502, bad gateway.

**Comment by jackycute** [comment]
Hi @jdhao 
Thanks for reporting, but we no longer manage that website.
Could you report this to https://github.com/codimd/server/issues?

Thank you!

**Comment by jdhao** [comment]
Ok, I will report this issue there.
