### ISSUE TITLE
Don't insert <br/> within paragraphs, unless the line ends with at least two spaces

### ISSUE THREAD

**Issue by jdhoek** [hackmdio/codimd#1212]
In Markdown paragraphs may contain hard breaks. To indicate a hard break, a line within a paragraph (but not the last one), may be suffixed with at least two spaces:

https://spec.commonmark.org/0.29/#hard-line-break

This is done to prevent Markdown parsers from interpreting *every* line break as a hard break. Line breaks are often used in source Markdown documents to keep the maximum line length under a certain bound.

CodiMD seems to parse *any* line break as a hard break. This is probably a bug.

# Versions affected

This happens in 65d8fd26131efabe00c6e1563fe978a82ff2f001 (May 1, 2019).

# Examples

## No hard breaks

This Markdown (spaces replaced with `␣` for display):

```markdown
Asperiores␣in␣vitae␣quo␣ratione␣
omnis␣dolorem␣doloribus␣voluptatum. 
Dicta␣laborum␣quasi␣aut␣vel␣est. 
```

Should generate this HTML:

```html
<p>Asperiores in vitae quo ratione 
omnis dolorem doloribus voluptatum. 
Dicta laborum quasi aut vel est.</p>
```

CodiMD however, generates:

```html
<p>Asperiores in vitae quo ratione<br/>
omnis dolorem doloribus voluptatum.<br/>
Dicta laborum quasi aut vel est.</p>
```

## Hard breaks

This Markdown (spaces shown as `␣`):

```markdown
Snow␣in␣my␣shoe␣␣
Abandoned␣␣
Sparrow's␣nest␣␣
```

Should render as:

```html
<p>Snow in my shoe<br/>
Abandoned<br/>
Sparrow's nest</p>
```

**Comment by jackycute** [comment]
Hi @jdhoek,

This wasn't a bug, I made that happen at the very beginning.

Some discussion can be found right here:
https://github.com/hackmdio/hackmd-io-issues/issues/79

You could use YAML metadata front-matter to make it parse the line breaks as the spec by:
```
---
breaks: false
---
```

**Comment by jdhoek** [comment]
Ah, I couldn't find any issue here, but it looks like @reagle already opened one in the HackMD project. Feel free to close this issue as a duplicate in favour of that one.

> This wasn't a bug, I made that happen at the very beginning.

According to that discussion, this does look like a bug though.

**Comment by reagle** [comment]
I think he means it was intentional. Even so, it does create breakage/incompatibilities.

**Comment by jdhoek** [comment]
I've changed the default to `breaks: false` in my local fork. If anyone is hosting CodiMD themselves and wants this behaviour, feel free to use it:

https://github.com/jdhoek/codimd/tree/feature/proper-linebreaks

Alternatively, you edit the two Javascript files yourself, this is the commit that does it:

https://github.com/jdhoek/codimd/commit/c12a8d2fddf496966f64ccabc688f3a09320ea90

**Comment by jdhoek** [comment]
@jackycute Would you consider merging a PR that makes this a configurable setting in `config.js`?

**Comment by jackycute** [comment]
> @jackycute Would you consider merging a PR that makes this a configurable setting in `config.js`?

Hi @jdhoek that sounds great!
Could you open a PR for that?
