### ISSUE TITLE
Add markdown equivalent to <details> snippets

### ISSUE THREAD

**Issue by fvisin** [hackmdio/codimd#1217]
`<details>`snippets, introduced in #445, are a great way to hide information when the page is too dense. 

The html notation is quite cumbersome though and markdown and LaTeX formatting is often difficult to format inside an indented `<details>` snippet. Would it be possible to fully integrate them with the rest of the syntax, by adding a markdown equivalent?

**Comment by Yukaii** [comment]
Currently we implement bootstrap style alert block by using [container syntax][1]

https://github.com/hackmdio/codimd/blob/5ce981859ebdb8a4ae2f9ec7cc65a30751a39e7b/public/js/extra.js#L992-L995

![Screen Shot 2019-08-03 at 11 29 17 AM 1](https://user-images.githubusercontent.com/4230968/62406665-f4275c00-b5e1-11e9-9987-7146076d146d.png)

[1]: https://github.com/markdown-it/markdown-it-container

In [the example][2] of markdown-it-container, it shows a container named `spoiler` that converts to details/summary snippets:

```md
:::spoiler click me
*content*
:::
```

converts to:

```html
<details><summary>click me</summary>
<p><em>content</em></p>
</details>
```

What do you think about this, @fvisin 

[2]: https://github.com/markdown-it/markdown-it-container#example

**Comment by Yukaii** [comment]
![details-container](https://user-images.githubusercontent.com/4230968/62407053-c2fc5b00-b5e4-11e9-9172-9a2595d66b30.gif)

**Comment by fvisin** [comment]
That's awesome, thank you!

Does this work with formatting syntax inside the spoiler as well? Something like:

```
:::spoiler click me
* list element
    * **bold sublist**
:::
```

Also, will this be automatically ported to hackmd.io as well or should I open a separate issue there?

**Comment by jackycute** [comment]
Hi @fvisin,
We'll first land this feature here to see how it goest, you can open a separate issue at https://github.com/hackmdio/hackmd-io-issues/issues
