### ISSUE TITLE
How to implement a header authorization?

### ISSUE THREAD

**Issue by urakagi** [hackmdio/codimd#1221]
Hi, I'm trying to write a new `Strategy` for `SandStorm` platform, which contains headers with user id, name, and picture in the request.

I plug in `passport-trusted-header`, but am not sure how to deal with the user profile or `hackmd` user objects. Can you give me a hint? Thank you!

**Comment by jackycute** [comment]
I think you can take a look at JWT:
https://github.com/mikenicholson/passport-jwt

**Comment by bingluen** [comment]
Hi @jackycute 

I have implemented an auth strategy with for Sandstorm platform to solve this issue.

Ref https://github.com/PDIS/codimd-sandstorm/blob/master/lib/web/auth/sandstorm/index.js

PS. In order to run CodiMD on Sandstorm platform, I did some custom modification and it is base on 5606380

**Comment by jackycute** [comment]
@bingluen @urakagi 
Thanks you guys for working on that auth strategy.
