### ISSUE TITLE
flowchart.js update

### ISSUE THREAD

**Issue by evilscientress** [hackmdio/codimd#1225]
The currently used version of flowchart.js ist quite old. The current version is [v1.12.0](https://github.com/adrai/flowchart.js/releases/tag/v1.12.0)
The current version has vastly improved rendering quality with big charts.
I tried it on my instance and it works flawlessly.

I can open a PR for this if wanted.

**Comment by jackycute** [comment]
Hi @evilscientress,
We would love to take the PR.
Thank you!

**Comment by evilscientress** [comment]
In the contributing guidelines it reads I should do a version bump. Is this true in this case as well?

**Comment by jackycute** [comment]
We will plan a release with version bump, and that should include your PR, so maybe not in this case.

**Comment by evilscientress** [comment]
OK I thought so, that's why I asked :)
