### ISSUE TITLE
http working, https is not

### ISSUE THREAD

**Issue by duffybelfield** [hackmdio/codimd#1235]
Hi there,

Thanks for a great product! After deploying to AWS ECS (as a docker container) I'm struggling to get https working.  http seems to work fine :) but https seems to receive a 404 and a message of "default". I'm terminating my SSL at the application load balancer.

Here are my environment vars:

CMD_DOMAIN = fish.org
CMD_PROTOCOL_USESSL = true
HMD_DB_URL = postgres://hackmd:hackmdpass@127.0.0.1:5432/hackmd
CMD_PORT = 443
NODE_ENV = production

What could I be missing?

**Comment by jackycute** [comment]
Hi @duffybelfield,

I think you don't need to specify port since you put the server behind ELB, it can be default port 3000 and you'll set the mapping in you target group.
Also, using ELB provided SSL is recommended, otherwise you'll have to give the CodiMD server your SSL certs and CA chains.

**Comment by jackycute** [comment]
Hi @duffybelfield do you have any update?

**Comment by jackycute** [comment]
Close for now, feel free to reopen if you found anything.
