### ISSUE TITLE
Stop assigning random names to guests

### ISSUE THREAD

**Issue by peteshadbolt** [hackmdio/codimd#1244]
Currently guests are assigned a random surname:

https://github.com/hackmdio/codimd/blob/ba0e4df6b7284739610ac7f2c0d075c23c112c5c/lib/realtime.js#L583

This is cute but also confusing to users:

- When a team member with a real name is viewing a note as guest, they are given a new, fake name.
- It's easy to get confused and think that this is a real name - maybe this is a new team member I haven't met yet, or even an intruder?

I would suggest that Guests are given a different unique identifier. I'd suggest a truncated UUID (`Guest abc123`) or [`chance.animal`](https://chancejs.com/thing/animal.html).

**Comment by jackycute** [comment]
Hi @peteshadbolt,
Thanks for giving us suggestion!
`chance.animal` sounds like a solid idea, let's wait for more opinions.
