### ISSUE TITLE
[BUG] Slides' print-pdf function prints only background

### ISSUE THREAD

**Issue by cbsghost** [hackmdio/codimd#1246]
I was upgrading the database of CodiMD. I use docker-compose to recreate the CodiMD container, then the print function does not work anymore. Only the background will be printed. Since the docker image is the same, maybe there is some broken npm packages in package.json file?

Please help. I really need the print to PDF feature of slides.

![](https://user-images.githubusercontent.com/1150982/62285479-3e94c580-b488-11e9-848e-f60d7d1b4f4b.png)

![](https://user-images.githubusercontent.com/1150982/62285481-418fb600-b488-11e9-8f88-135ae1ea1712.png)

**Comment by jackycute** [comment]
Hi @cbsghost 
Thanks for reporting to us.
Unfortunately, I couldn't reproduce this issue.

Could you see any errors in the DevTool console?
Did you run `npm install` and `npm build` after you upgrade the server?

Please provide more details for investigation.

**Comment by cbsghost** [comment]
I'm use the docker-compose file below:
https://github.com/hackmdio/docker-hackmd/blob/master/docker-compose.yml

The only modification was disabling the registration of CodiMD. Recently I just upgrade the PostgreSQL from 9.6 to 11.

I cannot successfully run `npm install` and `npm build` in the official docker image.

![](https://user-images.githubusercontent.com/1150982/62450110-3e553c80-b79e-11e9-9614-b3fb5a25cc3b.png)
Here is the only warning from the printing page. (Probably not related to the bug)
