### ISSUE TITLE
Do i need restart app when i change config(config.json)?

### ISSUE THREAD

**Issue by ev0A** [hackmdio/codimd#1276]
i deploy docker-codimd and i install minio in docker-container
https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-image-storage-minio
i think everything is correct 
but now i still can't upload images, they were uploaded in /tmp directory not minio /data/hackmd

I don't know if my configuration file is wrong or if I need to restart it.
if i need to restart it, docker will be killed because its pid is 1
and minio will disappear because i install it in docker and docker restart
So what went wrong， how can i do

**Comment by jackycute** [comment]
Feel free to reopen if you still having the issue.
