### ISSUE TITLE
Add the ability to insert charts

### ISSUE THREAD

**Issue by alternative-rvb** [hackmdio/codimd#1279]
It would be very useful to add the ability to insert charts, like bar chart. While discussing on your Facebook page, it seems that you plan to integrate this function with the Vega-Lite project.

[https://vega.github.io/vega-lite/](https://vega.github.io/vega-lite/)

**Comment by jackycute** [comment]
We're in the progress of release.

**Comment by alternative-rvb** [comment]
Great
