### ISSUE TITLE
Print blank pages when using Print-pdf for slides 

### ISSUE THREAD

**Issue by YuuuuXie** [hackmdio/codimd#1299]
Hi,

Recently I got an issue when using `?print-pdf` for slides. This did not happen before. After I add `?print-pdf` to the web address, I can successfully get into the page where all the contents are listed and prepared to print. However, when I use my browser to print (ctrl+P), there's no content, as shown below:

<img width="999" alt="Screen Shot 2019-10-12 at 12 15 27 AM" src="https://user-images.githubusercontent.com/24205323/66694829-f06d2100-ec85-11e9-83ed-8f88b8e2bddc.png">

I tried different browsers, chrome, firefox, safari, but still the same. So I don't know if this could be an issue of your repo. Thanks very much!

Best,
Yu

**Comment by jackycute** [comment]
Hi @YuuuuXie,
Thanks for reporting to us.
I think this issue might duplicate with #1246 

Could you tell us your image version, OS and browser version?
Also what's your CDN option? it would be better if you can provide your full setup to debug.

Thanks.

**Comment by YuuuuXie** [comment]
OS: macOS mojave 10.14.6
Chrome Version 77.0.3865.120
I don't know how to check the image version and CDN option...

**Comment by YuuuuXie** [comment]
> Hi @YuuuuXie,
> Thanks for reporting to us.
> I think this issue might duplicate with #1246
> 
> Could you tell us your image version, OS and browser version?
> Also what's your CDN option? it would be better if you can provide your full setup to debug.
> 
> Thanks.

- I'm not sure if this is a problem with Chrome or not. But in my Mac, other Firefox and Safari don't work as well. 
- And I tried it in Ubuntu's Chrome, got the same problem. 
- I tried Ubuntu's Firefox, there're things printed out (not blank any more), though I need to adjust the page size
- "View mode" does not have any problem with printing
- "Slide mode" shows all things in the html with "print-pdf" flag, but printing preview shows blank pages when trying to print
I don't know if there's anything got hidden in your slide printing settings... Thanks

**Comment by jackycute** [comment]
Hi @YuuuuXie,

Thanks for letting us know!
We will investigate this soon.

**Comment by Yukaii** [comment]
Hi @YuuuuXie 

We fix #1246 in PR #1339 , could you verify that does your slide work on this instance?

https://codimd-bugfix-slide-mod-gzodj0.herokuapp.com/

**Comment by YuuuuXie** [comment]
> Hi @YuuuuXie
> 
> We fix #1246 in PR #1339 , could you verify that does your slide work on this instance?
> 
> https://codimd-bugfix-slide-mod-gzodj0.herokuapp.com/

Yes, it is fixed now. Thanks!!
