### ISSUE TITLE
two or three people on the same page，can not see who is modifly this page!

### ISSUE THREAD

**Issue by rgonerao** [hackmdio/codimd#1304]
when i  on an page ,  I want to know who is eidt this page, can show his name when he is edit this page?

like this:

https://qn-cdn.leanote.top/teakki/img/home/demo.gif

**Comment by jackycute** [comment]
Hi @rgonerao,

We do showing the authorship, you need to hover on the line gutter which has vertical color bar.

<img width="150" alt="螢幕快照 2019-10-17 下午9 34 01" src="https://user-images.githubusercontent.com/2639151/67013532-db7d0b80-f125-11e9-819b-3ff08d33ecf7.png">

**Comment by rgonerao** [comment]
only on eidt mode can see the authorship?  Preview Mode can not see the authorship?

**Comment by rgonerao** [comment]
only on eidt mode can see the authorship?  Preview Mode can not see the authorship?

**Comment by rgonerao** [comment]
![image](https://user-images.githubusercontent.com/48788906/67014961-50e9db80-f128-11e9-8d32-46aa1751aa05.png)
can i see the editor when i on View mode？ ths

**Comment by jackycute** [comment]
No, view mode is not designed for viewing authorship and other users cursors.

**Comment by rgonerao** [comment]
有資料夾的概念嗎，我能新建一個資料夾嗎，然後將多個檔案放到一個資料夾下。

**Comment by jackycute** [comment]
Not for now, see #949 for folder discussion.

**Comment by rgonerao** [comment]
就是不考慮開發資料夾嗎

**Comment by jackycute** [comment]
Sorry, I was pointing to wrong issue.

There are:
https://github.com/hackmdio/codimd/issues/1275
https://github.com/hackmdio/codimd/issues/109
We just need more discussion before going there.

**Comment by jackycute** [comment]
Feel free to reopen if you have any other issues.
