### ISSUE TITLE
Git(-Hub/Lab) compatible (lower-case) header references

### ISSUE THREAD

**Issue by hoijui** [hackmdio/codimd#1305]
The automatically generated header-references in Codimd are not compatible with github and gitlab (and others, like pandoc), because codi keeps the caseing of the text, while the standard is to make everything lower-case.

This is an issue if one transfers documents back and forth between codi and other systems, as internal links break.

Would it be possible to introduce a config variable to enable github compatible reference generation? or maybe even choosing completely different markdown flavors?

**Comment by TWille** [comment]
Thx for mentioning this, I think it would help a lot for new Open Source documentation Workflows to have this compatibility.

**Comment by Yukaii** [comment]
Just pushed a PR releated to case.

https://github.com/hackmdio/codimd/pull/1306 introduces a new config to change default break style. The implementation will be very similar to this, if we want to generate header reference in different way.

The implementation step will be

1. Add a new config entry named `linkifyHeaderStyle` or something (https://github.com/hackmdio/codimd/pull/1306/commits/495b65e3b983603819e11371e43aecbd40ffe825)
2. Change linkify related code:
	https://github.com/hackmdio/codimd/blob/fd155fa74dc613d22473b5f32ef94b6c3644f707/public/js/extra.js#L862-L878

**Comment by hoijui** [comment]
WOW! thanks @Yukaii !!!
that is the best guide/help I have ever received to empower me to solve an issue myself!
I will try!

**Comment by jackycute** [comment]
related to #795 
and https://github.com/hackmdio/hackmd-io-issues/issues/27

**Comment by hoijui** [comment]
@Yukaii 
when I add `const config = require('../../lib/config')` in _public/js/extra.js_, I get:

```
    WARNING in ./lib/config/index.js 44:16-63
    Critical dependency: the request of a dependency is an expression
     @ ./public/js/extra.js
     @ ./public/js/index.js
     @ multi babel-polyfill script-loader!jquery-ui-resizable script-loader!codemirror script-loader!inlineAttachment script-loader!jqueryTextcomplete script-loader!codemirrorSpellChecker script-loader!codemirrorInlineAttachment script-loader!ot flowchart.js imports-loader?Raphael=raphael!js-sequence-diagrams expose-loader?RevealMarkdown!reveal-markdown ./public/js/index.js
    
    WARNING in ./lib/config/index.js 60:49-72
    Critical dependency: the request of a dependency is an expression
     @ ./public/js/extra.js
     @ ./public/js/index.js
     @ multi babel-polyfill script-loader!jquery-ui-resizable script-loader!codemirror script-loader!inlineAttachment script-loader!jqueryTextcomplete script-loader!codemirrorSpellChecker script-loader!codemirrorInlineAttachment script-loader!ot flowchart.js imports-loader?Raphael=raphael!js-sequence-diagrams expose-loader?RevealMarkdown!reveal-markdown ./public/js/index.js
```

why so?
or say.. how to I funnel a config value into the function in _extra.js_ that you highlighted?

PS: I am not a web-dev ;-)

**Comment by Yukaii** [comment]
@hoijui Oh I miss one step.

In order to feed config value to frontend javascript, in commit https://github.com/hackmdio/codimd/pull/1306/commits/495b65e3b983603819e11371e43aecbd40ffe825#diff-49b2b9de95c0652315feda851dd65d5cR9, I also edit `public/js/lib/common/constant.ejs`, to make `window.defaultUseHardbreak` available.

**Comment by hoijui** [comment]
ahh.. thank you!
now got it working.

**Comment by hoijui** [comment]
does it make sense to do a commit on the community version of codimd aswell? or will they pull it from here anyway once/if it is merged?

**Comment by Yukaii** [comment]
We appreciate your work, and it depends on you 😸
