### ISSUE TITLE
Update markdownlint package to latest version

### ISSUE THREAD

**Issue by Yukaii** [hackmdio/codimd#1307]
> Update: `markdownlint-browser.js` should be available in the npm package for `markdownlint` with the next release.

https://github.com/hackmdio/codimd/issues/1256#issuecomment-537766142

### Tasks

1. Upgrade `package.json` & `yarn.lock`
2. Apply the following patch

> ```js
> // markdown-lint/index.js
> window.markdownit = require('markdown-it')
> require('script-loader!markdownlint')
> ```
> 
> ```js
> // update webpack config
> resolve: {
>   alias: {
>     markdownlint: path.join(__dirname, 'public/vendor/markdownlint-browser.min.js')
>   }
> }
> ```

3. Drop the workaround in https://github.com/hackmdio/codimd/issues/1256#issuecomment-522087161

> ```js
>     new webpack.NormalModuleReplacementPlugin(
>       /^url$/,
>       path.resolve(__dirname, './public/js/url.js')
>     )
> ```
> 
> and the content of `url.js` is:
> 
> ```js
> exports.URL = window.URL
> ```

https://github.com/hackmdio/codimd/issues/1256#issuecomment-522240249

**Comment by gerlis18** [comment]
Hey man!, i'm working in this issue but i have a problem, can you explain me where i should put these lines?

 `window.markdownit = require('markdown-it')
require('script-loader!markdownlint')`

**Comment by Yukaii** [comment]
@gerlis18 You can take a look at https://github.com/hackmdio/codimd/pull/1257, where the markdownlint feature was originally implemented. 

This issue is a follow up task to upgrade markdownlint package. You can read that thread for the whole context https://github.com/hackmdio/codimd/issues/1256#issuecomment-522087161.

**Comment by Yukaii** [comment]
Hi @gerlis18 , Thanks for your willing to contribute, but because we're close to release version 1.4.0, I'll take this myself instead.
