### ISSUE TITLE
Browser stuck  when useing Mermaid excludes weekdays feature

### ISSUE THREAD

**Issue by t42ji2ji** [hackmdio/codimd#1314]
When I type  down this code , chrome was stuck and cant do anything and cant click any button.
So I can't delete this project too. This is so annoying.
below is my origin code 

```mermaid
gantt
dateFormat  YYYY-MM-DD
title 預估進度圖 
excludes weekdays 
    section Logo設計
    草稿、風格           :a1, 2019-10-23, 5d
    定稿設計     :a2, after a1  , 3d
    section 名片設計
    名片設計      :b1, after a2 , 3d
    section 參考書
    參考書設計    :c1, after b1, 10d
    section 信封設計
    信封設計     :d1, after c1, 2d
    section DM設計
    DM設計    :e1, after d1, 1d
    section 集點卡
    集點卡    :f1, after e1, 1d
    section 課程費用表
    課程費用表    :g1, after f1, 1d
```

**Comment by jackycute** [comment]
Hi @t42ji2ji 
Thanks for reporting!

I've filed an issue in https://github.com/mermaid-js/mermaid/issues/1060
Now it has been fixed and we upgraded it in https://github.com/hackmdio/codimd/pull/1418
