### ISSUE TITLE
Documentation is for unreleased version

### ISSUE THREAD

**Issue by cfstras** [hackmdio/codimd#1330]
There should be a prominent notice on the documentation page (https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration) stating that the target is the current develop version, rather than the most recent release version.

Specifically, the configuration `CMD_S3_ENDPOINT` is mentioned (without a hint on when it was added), but has no effect prior to https://github.com/hackmdio/codimd/commit/d127b8ef7fd522b389e33610b7163b7e5af5906e, which first appears in v1.4.0-rc1, and not in the stable version 1.3.1.

**Comment by Yukaii** [comment]
Version 1.4.0 got released, but still very thanks for pointing this out. We'll keep improving our online documentation and the release workflow 👍
