### ISSUE TITLE
Question : is master branch aligned with release ?

### ISSUE THREAD

**Issue by jdauphant** [hackmdio/codimd#1340]
Hello,

I want to know if master is or in the futur will be aligned with the last release ?
It looks like it's not the case because there is 106 commit on master since 1.3.1 .
I ask this question because I want to simplify the deployment on PaaS hosting like Heroku (I can only deploy "develop" for the moment because master have an incorrect yarn.lock file).

Thanks for your answer,
Julien

**Comment by Yukaii** [comment]
Hi @jdauphant 

Yes, the release tags will be on master branch, and we're in the process of releasing the new version of CodiMD, stay tuned!

**Comment by Yukaii** [comment]
Hi @jdauphant, we just released our latest version 1.4.0 🎉 

I would close this issue now 👍

**Comment by jdauphant** [comment]
Thanks, congrats ;)
If you keep master aligned with the last publish version, it will be perfect to automate update.

All the best
