### ISSUE TITLE
Docker repository archived and not up to date but referenced for docker deployment

### ISSUE THREAD

**Issue by MelBourbon** [hackmdio/codimd#1348]
The docker repository (https://github.com/hackmdio/docker-hackmd) is archived but still used for docker deployment in the documentation for CodiMD. In addition the archive is not up to date (see below example):

https://github.com/hackmdio/docker-hackmd/blob/55c58abb016ec93d80add8c2b08c90876cac48ed/docker-compose.yml#L55-L57
```
    #    - "HACKMD_REPOSITORY=https://github.com/hackmdio/hackmd.git"
    image: hackmdio/hackmd:1.2.0
    #mem_limit: 256mb         # version 2 only
```

**Comment by jackycute** [comment]
Hi @MelBourbon,
We'll update to docs soon, thanks for heads up!

**Comment by jackycute** [comment]
We've updated the docs! Please check if that works for you.

**Comment by MelBourbon** [comment]
So for docker-deployment which repository needs to be pulled before? Currently it was `docker-hackmd`. Is this changed or not needed anymore? If yes this is fine and issue can be closed. If not this should be added for lay users like me :blush:

**Comment by jackycute** [comment]
Yes, the `docker-hackmd` was already deprecated, using the deployments in this repo instead please.
