### ISSUE TITLE
[docker] Reverse Proxy problem

### ISSUE THREAD

**Issue by johnny88850tw** [hackmdio/codimd#1353]
Sorry and thanks for `codimd`. I am not sure about my expression is clear or not...

I would like to make my own url path such as http://example.com:3000/ become http://example.com/codimd/, and I found some problem.

* I use `Apache 2.2` config with `httpd.conf` :

```
<VirtualHost _default_:80 _default_:443>
    DocumentRoot "<my apache web folder>"
    ProxyRequests off
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
    ProxyPass /codimd http://127.0.0.1:3000/
    ProxyPassReverse /codimd http://127.0.0.1:3000/
    ProxyPreserveHost on
</VirtualHost>
```

* And here is my `docker-compose.yml` environment config

```
environment:
  - CMD_DB_URL=postgres://codimd:examplehard@database/codimd
  - CMD_USECDN=false
  - CMD_EMAIL=true
  - CMD_ALLOW_EMAIL_REGISTER=false
  - CMD_ALLOW_ANONYMOUS=false
  - CMD_URL_PATH=codimd
```

* The result is that it can show `screenshot.png` image in home page, but `css` broke like this:
    * ![image](https://user-images.githubusercontent.com/30661645/69410319-b774a180-0d45-11ea-8450-a52faf06b49d.png)

* The reason is that the `css` file under `/build/` can't be import. To fix, I add an extra `ProxyPass` to `httpd.conf`:

```
ProxyPass /build http://127.0.0.1/codimd/
ProxyPassReverse /build http://127.0.0.1/codimd/
```

* Is there any solution or parameter (Environment Variable) can solve it? I think I miss some important key-point. I thought it may be solved after adding the 'Environment Variable' `CMD_URL_PATH=codimd`

**Comment by a60814billy** [comment]
Hi @johnny88850tw,
Thanks for reporting, we found `CMD_URL_PATH` is not working anymore.
We've opened an issue #1358 for that, it's related to webpack configs.

We'll fix that as soon as we can, thank you.

**Comment by johnny88850tw** [comment]
Thanks !!

**Comment by gkoerk** [comment]
Any ETA on this fix?
