### ISSUE TITLE
[PaaS Deployment] Scalingo one-click button

### ISSUE THREAD

**Issue by brandon-welsch** [hackmdio/codimd#1359]
Hello. I'm a developer at Scalingo, [Scalingo](https://scalingo.com/) is a European and Heroku compatible PaaS.

And today I come to you because we want to make the project easily deployable on Scalingo via a one-click button.

Would you agree that we could propose our file additions as well as documentation about the deployment with us?

**Comment by jackycute** [comment]
Hi @brandon-welsch,
We agree and definitely would love to see this.
Thanks for reaching us!

**Comment by brandon-welsch** [comment]
Thank you very much @jackycute, I'll do it quickly.

**Comment by brandon-welsch** [comment]
@jackycute I haven't found how to contribute to the documentation, can you add a page to the documentation?

**Comment by Yukaii** [comment]
Hi @brandon-welsch 

Currently we host CodiMD docs on HackMD, and I just opend an repo for this contribution. 

Could you follow format as [heroku deployment](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-heroku-deployment), adding a `scalingo-deployment.md` in https://github.com/hackmdio/codimd-docs repository? Thanks a lot!

We'll sync back these changes to our hosted doc after PR get merged.

**Comment by brandon-welsch** [comment]
@Yukaii Thank you, the PR for the documentation is here: https://github.com/hackmdio/codimd-docs/pull/1
