### ISSUE TITLE
[docker] How can I add user without OAuth and disable CMD_ALLOW_EMAIL_REGISTER?

### ISSUE THREAD

**Issue by johnny88850tw** [hackmdio/codimd#1366]
I saw the hint in [Authentication-Email](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration), but I don't know how to use it when deploying with Docker.
I would like to create a codimd server for just several people, so is there a "super user" account or some better way to manage small number of users?

**Comment by jackycute** [comment]
Hi @johnny88850tw,
We don't support doing this at the moment, maybe just turn on email register and close after all the super user accounts have created?

**Comment by johnny88850tw** [comment]
@jackycute  thanks for reply, I am using this solution now, haha. But it would be inconvenient if I want to add extra user LoL...

**Comment by jackycute** [comment]
@johnny88850tw Would you like to try command line tool?
https://github.com/hackmdio/codimd/blob/develop/bin/manage_users

**Comment by johnny88850tw** [comment]
It looks great! I will try it when `1.4.1` is released. Thanks a lot!
