### ISSUE TITLE
How to implement fail2ban?

### ISSUE THREAD

**Issue by finzzz** [hackmdio/codimd#1367]
There is no notification of failed login attempts.

**Comment by jackycute** [comment]
Hi @finzzz,
We don't have that at the moment, maybe taking a look at server logs for sign in error 403 would help?

**Comment by finzzz** [comment]
> Hi @finzzz,
> We don't have that at the moment, maybe taking a look at server logs for sign in error 403 would help?

I have tried enabling debug or verbose but I don't find any 401/403 error.

**Comment by jackycute** [comment]
You're right, I only can see this log
```
codimd_1    | 2019-12-02T15:59:07.778Z info: 	172.20.0.1 - - [02/Dec/2019:15:59:07 +0000] "POST /login HTTP/1.1" 302 46 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
```

Because the login failed needs to redirect to home page.

You can add login failed log at: https://github.com/hackmdio/codimd/blob/develop/lib/web/auth/email/index.js#L26

**Comment by jackycute** [comment]
Feel free to reopen if you still have no idea how to implement that.
