### ISSUE TITLE
Giving notes a specific URL | Consistent URL

### ISSUE THREAD

**Issue by dev-clavis** [hackmdio/codimd#1372]
Hi,
I often use CodiMD in school spontaneous with other people, and the begin is often a pain because the process of sharing the note is really annoying, another student writes instead of l I and so on. In school we don't work on our own PC, therefore I have to share the ID or the ShortID orally.
My Idea would be
* to add a Metatag for the note called url
* and to have also the note open from /$username/$url or directly from /$url

**Comment by a60814billy** [comment]
Hi @dev-clavis,

Maybe you can try ours `allow free url` feature. just setup by environment variable `CMD_ALLOW_FREEURL` to `true`.

The feature enable you to typing any url to create a note. e.g Using `https://my.codimd.dev/custom-url` to create a note.

**Comment by jackycute** [comment]
Feel free to reopen if you need further help @dev-clavis
