### ISSUE TITLE
Arbitrary oauth2 providers

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1373]
I have read the [documentation ](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-oauth-github) and seen that you can specify your oauth2 secrets for specific providers:

```
CMD_GITHUB_CLIENTID=3747d30eaccXXXXXXXXX
CMD_GITHUB_CLIENTSECRET=2a8e682948eee0c580XXXXXXXXXXXXXXXXXXXXXX
```

but it doesn't mention which env vars one should set for oauth2 providers that are not github, gitlab, mattermost, nextcloud or twitter.

Can I specify the clientid, clientsecret, authendpoint, tokenendpoint, userinfoendpoint and scope somehow? It is a standard, after all :)

**Comment by a60814billy** [comment]
In OAuth2, we provider these env vars 
```
CMD_OAUTH2_PROVIDERNAME,
CMD_OAUTH2_BASEURL,
CMD_OAUTH2_USER_PROFILE_URL,
CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR,
CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR,
CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR,
CMD_OAUTH2_TOKEN_URL,
CMD_OAUTH2_AUTHORIZATION_URL,
CMD_OAUTH2_CLIENT_ID,
CMD_OAUTH2_CLIENT_SECRET
```

**Comment by Trolldemorted** [comment]
Is this documented anywhere?

**Comment by a60814billy** [comment]
The document below is a example to setup for NextCloud OAuth2 authentication, you can give it a try.

https://github.com/hackmdio/codimd/blob/develop/docs/guides/auth/nextcloud.md

**Comment by Trolldemorted** [comment]
Any chance we can get this vital information to a not nextcloud-specific page? :)

**Comment by a60814billy** [comment]
Hi @Trolldemorted,
We update the document about `generic OAuth 2.0 provider`. If you have any question, feel free to re-open this issue.
