### ISSUE TITLE
Graphviz does not work in develop branch 

### ISSUE THREAD

**Issue by pch007** [hackmdio/codimd#1374]
![bug](https://user-images.githubusercontent.com/8195937/70572942-1db04f80-1ba1-11ea-8c6a-99f97cfbec32.png)
How to reproduce the error:
 1. Create new note
 2. Open "Both" view (Ctrl+Alt+B)
 3. Paste:
```graphviz
digraph a {
aaa
	
}
```
 4. Place cursor just after "aaa" and start typing characters: "-> b".
Just after you type character "-" graph stops to render (because of syntax error) and it will not begin to render after syntax error is fixed (after typing "-> b").

Upgrading viz.js (4531d96) may have caused this problem.

**Comment by wejn** [comment]
Wouldn't this be relevant:

https://github.com/mdaines/viz.js/wiki/Caveats#rendering-graphs-with-user-input

?

Because on 1.4.1 I have similar issue -- live editing a graph breaks the rendering. Only after refresh it shows again.

**Comment by wejn** [comment]
Cool, thanks!
