### ISSUE TITLE
codimd does not specify a scope to passport

### ISSUE THREAD

**Issue by Trolldemorted** [hackmdio/codimd#1375]
As you can see, you do[ not supply a scope parameter to passport](https://github.com/jaredhanson/passport-oauth2/blob/master/test/oauth2.test.js#L157-L164):

https://github.com/hackmdio/codimd/blob/a0cc1955cb2c02c990c2fd4dbe0a9e479d267959/lib/web/auth/oauth2/index.js#L86-L93

Right now you cannot use codimd with oauth providers that require scope usage.

**Comment by a60814billy** [comment]
thanks for your suggest, we'll support to customize scope in oauth2 provider on next release.

**Comment by jackycute** [comment]
Implemented in #1424 
Thanks @Trolldemorted @a60814billy
