### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by yekanchi** [hackmdio/codimd#1380]
i wanted  to contribute to the project by adding RTL (right to left) support but i did'nt  know where to start, i was thinking about extending the markdown to have some areas that are in rtl languages in the docs.

i don't want to use html tags because u cannot use markdown inside a html tag.

**Comment by jackycute** [comment]
Hi @yekanchi, thanks for reaching us.

I think you can set yaml metadata to enable rtl, for example:
```
---
dir: rtl
---
```

put above syntax on the very beginning of the note would work.

**Comment by yekanchi** [comment]
@jackycute  It works pretty well but how to change it in the middle of the note. i mean mixed rtl and ltr.

is it possible by adding some features to Codimd source code?

**Comment by Yukaii** [comment]
Hi @yekanchi , could this be done with css class?

```html
<style>
.ltr {
    direction: ltr;
}

.rtl {
    direction: rtl;
}
</style>

<div class="ltr">
   abcdefg 
</div>

<div class="rtl">
   hijklmnop
</div>
```

![Screen Shot 2019-12-17 at 10 29 59 PM](https://user-images.githubusercontent.com/4230968/71004318-c8ce8500-211c-11ea-98af-b8b1b5314f8b.png)

https://codimd-app.herokuapp.com/CfEE4XhqTK6S7iFU4YEfqA

**Comment by yekanchi** [comment]
thanks @Yukaii, i knew about this solution even simpler like below one but the problem is that it's not possible using Markdown inside the html tags.

```
<div dir="ltr">
   abcdefg 
</div>

<div dir="rtl">
   hijklmnop
</div>
```

does not need any styles/

**Comment by jackycute** [comment]
@yekanchi 

It's possible to write markdown in the HTML tags, for example:

```
<div class="ltr">

# Title
    
*Yes it's possible*
    
</div>

<div class="rtl">


# Title
    
*Yes it's possible*
    
</div>
```

**Comment by yekanchi** [comment]
> @yekanchi
> 
> It's possible to write markdown in the HTML tags, you just need to leave empty line above and below, for example:
> 
> ```
> <div class="ltr">
> 
> # Title
>     
> *Yes it's possible*
>     
> </div>
> 
> <div class="rtl">
> 
> # Title
>     
> *Yes it's possible*
>     
> </div>
> ```

yes it works file!
thanks for your suggestion
