### ISSUE TITLE
Add support for hostedDomain parameter in passport 

### ISSUE THREAD

**Issue by datadavev** [hackmdio/codimd#1383]
The `hostedDomain` parameter limits the domain for OAuth. For example, with a GSuite domain of `example.com`, the following would restrict Google authentication to only members of that domain:

In `lib/web/auth/google/index.js`:
```
googleAuth.get('/auth/google', function (req, res, next) {
  setReturnToFromReferer(req)
  passport.authenticate('google', { scope: ['profile'], hostedDomain:'example.com' })(req, res, next)
})
```

Suggest also to retrieve the value from something like `config.oauthHostedDomain`.

**Comment by a60814billy** [comment]
The `hostedDomain` parameter only work in `passport-google-oauth20` package, maybe we can add `CMD_GOOGLE_HOSTEDDOMAIN` to support this.
