### ISSUE TITLE
Question - does this project has index page for all notes?

### ISSUE THREAD

**Issue by zulhfreelancer** [hackmdio/codimd#1401]
I'm trying to install this project for my team internal usage where everybody will contribute their notes using their own account — something like how Google Drive collaboration feature.

From what I can see, users can't see each other's notes in one central view. For example, Bob can't see Alice's notes and Alice can't see Bob's notes.

Do we already this page somewhere in this project? Something like in image below. Or, it's never exists by designed?

![codimd](https://user-images.githubusercontent.com/3416976/73926099-1213a780-490a-11ea-9c7c-e6c652edf4d4.jpg)

**Comment by jackycute** [comment]
Hi @zulhfreelancer,

We never had that page to view all notes by all users on a instance.
It was designed for viewing the note that you've visited for privacy.

**Comment by zulhfreelancer** [comment]
Thank you for the answer
