### ISSUE TITLE
Question - how to enable Sync with GitHub feature?

### ISSUE THREAD

**Issue by zulhfreelancer** [hackmdio/codimd#1403]
I stumbled upon the [Sync with GitHub](https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github) feature and I tried it on HackMD site.

I tried to find "Versions" in my CodiMD so that I can sync my CodiMD notes with GitHub. But, I couldn't find it.

Where is the docs on how to enable GitHub sync for CodiMD? Does the function exist only on HackMD?

**Comment by jackycute** [comment]
Hi @zulhfreelancer 
Unfortunately, CodiMD doesn't have this feature.

**Comment by zulhfreelancer** [comment]
Thank you for the clarification @jackycute.
