### ISSUE TITLE
Question - does it possible to only enable certain permissions?

### ISSUE THREAD

**Issue by zulhfreelancer** [hackmdio/codimd#1404]
![Screen Shot 2020-02-09 at 12 49 17 PM](https://user-images.githubusercontent.com/3416976/74096481-9ea4ac80-4b3a-11ea-921e-ced4e8caed83.png)

I'm self hosting a CodiMD instance and I'm curious — does it possible to only allow my users to select _Limited_ or _Private_? I don't want to show all permissions above to them.

I tried to find it in the [configuration docs](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration), but I couldn't see any config related to this. Did I missed something?

**Comment by zulhfreelancer** [comment]
Hi @jackycute, appreciate your inputs here

**Comment by jackycute** [comment]
Hi @zulhfreelancer 
Please take a look at: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration "User Privilege" and see `CMD_ALLOW_ANONYMOUS` and `CMD_ALLOW_ANONYMOUS_EDITS`.

<img width="1107" alt="螢幕快照 2020-02-10 上午11 20 35" src="https://user-images.githubusercontent.com/2639151/74118698-7929a880-4bf7-11ea-889c-5914bc20a926.png">

This also from PR https://github.com/hackmdio/codimd/pull/1152

**Comment by zulhfreelancer** [comment]
Thanks @jackycute. It worked!

For future reference, here is the useful table from #1152: 

![permissions](https://user-images.githubusercontent.com/3416976/74128258-baca4b80-4c17-11ea-91e4-3f62cfee46c6.png)

And below is my own version for _Limited_ vs _Protected_ vs _Private_:

![permissions-2](https://user-images.githubusercontent.com/3416976/74128311-e77e6300-4c17-11ea-867f-8390f8901088.png)

Here is the relevant snippet from _config.json_ file:

```
    "email": false,
    "allowAnonymous": false,
    "allowAnonymousEdits": false,
    "allowAnonymousViews": false,
    "defaultPermission": "limited",
```
