### ISSUE TITLE
Are there any plan of supporting addons of mindmap?

### ISSUE THREAD

**Issue by Windelly** [hackmdio/codimd#1407]
Here is a project on converting markdown into interactive mindmap:https://github.com/dundalek/markmap

Are there any plan of integrating this into codimd?

**Comment by Yukaii** [comment]
Just saw yet another `markdown <-> mindmap` library on HN today: https://github.com/gera2ld/markmap-lib

The MindMap integration could be another preview mode besides slide mode and published mode.

**Comment by Yukaii** [comment]
This is implemented in #1483
