### ISSUE TITLE
[Feature Request] Zoom in/out images on mouse click

### ISSUE THREAD

**Issue by YTTom** [hackmdio/codimd#1411]
Hi,

I hope it can be zoomed in and out, when I click Images.

Like 'Medium'

- Normal
![image](https://user-images.githubusercontent.com/22091920/74798976-4031b800-530a-11ea-9a51-1d8188bfd408.png)

- Zoom In
![image](https://user-images.githubusercontent.com/22091920/74799016-5b042c80-530a-11ea-8eba-fd34d494d2d2.png)

Thanks!
Tom

**Comment by jackycute** [comment]
Hi @YTTom, thanks for suggestion.
Implemented in https://github.com/hackmdio/codimd/pull/1463
