### ISSUE TITLE
Upgrade mermaid-js 8.2.3 to 8.4.7

### ISSUE THREAD

**Issue by erhlee-bird** [hackmdio/codimd#1412]
Mermaid being used in package.json is `~8.2.3`.

Would be great to update to the latest `8.4.7`.

- https://github.com/mermaid-js/mermaid/releases

**Comment by jackycute** [comment]
Thanks for heads up!

Implemented in #1418

**Comment by erhlee-bird** [comment]
Awesome, appreciate it @jackycute
