### ISSUE TITLE
Support PlantUML syntax highlighting

### ISSUE THREAD

**Issue by Yukaii** [hackmdio/codimd#1413]
Since we've already supported PlantUML in #1096 , it's time to add some colors!

- https://github.com/kkeisuke/plantuml-editor

**Comment by kishan3** [comment]
Hi @Yukaii Please explain the steps would be interesting to contribute to this!

**Comment by Yukaii** [comment]
Hi @kishan3, I forgot this issue 😅 This was implemented in https://github.com/hackmdio/CodeMirror/pull/5 and released in [version 2.0.0](https://hackmd.io/@codimd/release-notes/%2F%40codimd%2Fv2_0_0#PlantUML-syntax-highlighting). Feel free to check other good first issues!
