### ISSUE TITLE
Bad Copy/Paste of Image converted to Base64 (~10,000 Lines) - Server Crash 

### ISSUE THREAD

**Issue by JJediny** [hackmdio/codimd#1425]
**User Story**
If this is not helpful, please close, but a real-world test of a self-deployed codimd instance use-case that caused a chrome browser `Version 80.0.3987.122 (Official Build) (64-bit) on Linux Mint 19.3` crash and the codimd server (running remotely on cloud foundry w/ carbon-lts build pack, w/ 2cpu 
& 4gb) to fail/restart (w/ 1-2 min 404 returned). 

**Recreate:**
I uploaded as a gist here to a new note:
https://gist.githubusercontent.com/JJediny/31fce32701656f39eede263e4eea0805/raw/9066a6a78c9b2e8c5d9a68d841eb93a42e9216c4/codimd-base64-image-crash-file.md

Didn't inspect with dev tools, might be worth building into a test.

**Comment by jackycute** [comment]
Hi @JJediny,

Thanks for reporting to us.

I think we have a limitation that the max length of the doc should less or equal 100,000 characters.
The Gist you provided is 647,560 characters long.

We will continue investigate this.
