### ISSUE TITLE
Render csv codeblock as table

### ISSUE THREAD

**Issue by Yukaii** [hackmdio/codimd#1436]
- https://csv.js.org/parse/

**Comment by daniele-athome** [comment]
Nice feature. I wonder how this will be done. I mean I will still be able to render a CSV codeblock as a CSV codeblock right?

**Comment by Yukaii** [comment]
In my imagination, users can enable CSV as table with the syntax:

~~~md
```csv {editor="true"}
John,Doe,120 jefferson st.,Riverside, NJ, 08075
Jack,McGinnis,220 hobo Av.,Phila, PA,09119
"John ""Da Man""",Repici,120 Jefferson St.,Riverside, NJ,08075
Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD, 91234
,Blankman,,SomeTown, SD, 00298
"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,00123
```
~~~

And in the right side (preview panel), the data could be rendered to a table with [HandsonTable](https://handsontable.com/)(interactive) or some library. Then we can listen to the table on such events as [afterChange](https://handsontable.com/docs/7.4.2/Hooks.html#event:afterChange), and reflecting the changes to the document.

**Comment by Yukaii** [comment]
It seems too far for implementing an editing feature. 🤣 Or we can just render CSV as HTML table with `{preview="true"}`:

~~~
```csv {preview="true"}
John,Doe,120 jefferson st.,Riverside, NJ, 08075
Jack,McGinnis,220 hobo Av.,Phila, PA,09119
"John ""Da Man""",Repici,120 Jefferson St.,Riverside, NJ,08075
Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD, 91234
,Blankman,,SomeTown, SD, 00298
"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,00123
```
~~~

**Comment by daniele-athome** [comment]
Nice, thanks! Editing would be a nice thing to add, but we can agree that CodiMD is not Excel :-)
