### ISSUE TITLE
Login-button doesnt work

### ISSUE THREAD

**Issue by exetico** [hackmdio/codimd#1444]
Hi,

I'm currently running codimd from `linuxserver/codimd:latest`, and it has been great. However...

I updated my container today, and now the "Login"-button doesn't respons.

If i check the Console, no errors is thrown, and, there's no Network-requests, too.

![image](https://user-images.githubusercontent.com/3549445/76071585-ca2e8180-5f96-11ea-820d-95b8f9f7212a.png)

I've tried both in Private session, with cookies removed, and so - but with the same results. I've also tried in both Firefox and Chrome, and both directly on IP:PORT, but also throguh my reverse proxy solution.

Am i the only one, facing this issue?

No changes has been made to my config-file:
```
{
        "production": {
                "use_env_variable": "CMD_DB_URL",
                "domain": "mydomain",
                "allowOrigin":"removed.0.removed.removed, localhost, mydomain",
                "protocolUseSSL":true,
                "email":true,
                "allowEmailRegister":false,
                "allowAnonymous":false
        }
}
```

And the logs looks fine:
```
Loaded configuration file "../../config/config.json".
Using environment "production".
No migrations were executed, database schema was already up to date.
2020-03-06T09:37:27.984Z warn:  PDF export was disabled for this release to mitigate a critical security issue. This feature will hopefully become available again in future releases.
Fri, 06 Mar 2020 09:37:28 GMT hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. at app.js:85:18
2020-03-06T09:37:29.120Z info:  HTTP Server listening at 0.0.0.0:3000
2020-03-06T09:37:35.457Z info:  10.0.0.11 - - [06/Mar/2020:09:37:35 +0000] "GET / HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

**Comment by jackycute** [comment]
Hi @exetico, thanks for reporting to us.
I couldn't reproduce this issue on https://codimd-app.herokuapp.com/, which runs the current develop branch.

Could you try the image from this doc?
https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment

**Comment by exetico** [comment]
Wow, that a fast answer.

I just spotted that common.x.js and cover-pack.x.js is returning with 302. I'm not sure why? 

![image](https://user-images.githubusercontent.com/3549445/76072671-b257fd00-5f98-11ea-8c2c-746468cc309f.png)

But, good point with the image. I'll try and pull the other one, in a bit.

**Comment by jackycute** [comment]
> I just spotted that common.x.js and cover-pack.x.js is returning with 302. I'm not sure why?
It means that resource is loaded from disk cache.

**Comment by exetico** [comment]
My only problem right now, that i would like to have a proper export, before switching to the other setup. But now that i can't access it, that task is just a bit more complex... 

I found it pretty wierd, that the problem happend, after i updated the container-image.

**Comment by jackycute** [comment]
Do you see anything in your devtool console?
Please also attach a screenshot and make sure you're using the latest image (by visiting the release-notes page in your instance, like this: https://codimd-app.herokuapp.com/s/release-notes).

**Comment by exetico** [comment]
Hi again

Nope. Nothing at all. That's pretty wierd. However was pretty sure that no updates has been done, in the last 6 months, or so.

So, i removed my container, and forced it to pull `linuxserver/codimd:1.4.0-ls7`, and after that, it's responding again. But buttons, and all other things. So, now i'll backup my data, and move to the recommended container-source. I'll update the issue, after that's done.

**Comment by jackycute** [comment]
For the complete list of all the configurations, please read: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration
You can also find other docs from the left sidebar in above link.

**Comment by exetico** [comment]
Well, i'm just trying to get secrets to work, as local files - but it doesn't work.

It keeps reporting:
```
> docker logs codimd
2020/03/06 12:10:28 portchecker.go:42: dial tcp: lookup  : no such host
    wait 3 seconds retry
2020/03/06 12:10:31 portchecker.go:42: dial tcp: lookup  : no such host
    wait 3 seconds retry
2020/03/06 12:10:34 portchecker.go:42: dial tcp: lookup  : no such host
    wait 3 seconds retry
2020/03/06 12:10:37 portchecker.go:42: dial tcp: lookup  : no such host
    wait 3 seconds retry
2020/03/06 12:10:40 portchecker.go:42: dial tcp: lookup  : no such host
```
I'm wondering why it's not working. It's working for all my other contains, and [it's part of the docker-compose documentation](https://docs.docker.com/compose/compose-file/#secrets).

It works just fine, with the normal settings, provided from the docs (with no secrets in use). So i'm not sure if it's my docker-setup, or something else.

**Comment by exetico** [comment]
I've switched back to the good old way, and will look into secrets in the future.
