### ISSUE TITLE
docker image use unmaintained debian jessie

### ISSUE THREAD

**Issue by philpep** [hackmdio/codimd#1454]
Hi,

The docker image uses an old version of debian which does no longer receive security updates.

```
% docker run --rm -it nabo.codimd.dev/hackmdio/hackmd:2.0.0 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by a60814billy** [comment]
Hi @philpep,

Thanks for your information, the Debian jessie is supported to June 30 2020. We already plan updating to next LTS version along with node.js 12.

**Comment by philpep** [comment]
Hi @a60814billy , ah indeed jessie is still supported, good to hear update is planned. I'm closing the issue.
