### ISSUE TITLE
[Doc] Wrong uploads path

### ISSUE THREAD

**Issue by Turakar** [hackmdio/codimd#1464]
According to the [documentation](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment) uploads are saved to `/home/hackmd/app/public/uploads`. A manual inspection reveals `/codimd/public/uploads` as the correct path.

This is dangerous, because admins may loose the uploaded images of their users if they are not careful during updating!

**Comment by jackycute** [comment]
Hi @Turakar,
Could you let us know which version are you using?
We've changed uploads path after 1.4.0.

**Comment by Turakar** [comment]
Oh, my fault. Thought that `nabo.codimd.dev/hackmdio/hackmd:latest` would download the latest version, but it downloaded `1.3.1`. To be honest, that is not very intuitive... Is the `latest` tag intentionally set this way and if yes, why?

**Comment by jackycute** [comment]
> Oh, my fault. Thought that `nabo.codimd.dev/hackmdio/hackmd:latest` would download the latest version, but it downloaded `1.3.1`. To be honest, that is not very intuitive... Is the `latest` tag intentionally set this way and if yes, why?

Thanks for reporting @Turakar, we've updated the latest tag to version `2.0.0`.
We still recommend to pull for specific image version instead of `latest`, since the latest might not be stable.

**Comment by Turakar** [comment]
Thanks for the fix :)
