### ISSUE TITLE
Missing book mode functionality

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/codimd#1468]
Currently, [as opposed to what the README indicates](https://github.com/hackmdio/codimd/blob/412317a/README.md#codimd---the-open-source-hackmd), the book mode feature isn't available in CodiMD.

As a book mode major user I understand that this feature is one of the selling points of HackMD Enterprise and would like to either:

* Make book mode available to CodiMD
* Drop the mention of book mode in the CodiMD's documentation, so that users won't be confused

Thanks in advance!

**Comment by jackycute** [comment]
Hi @Lin-Buo-Ren 

Thanks for reporting to us.
So that section is meant for describing the features of HackMD and the later part is for CodiMD. Sorry for the confusion, we will fix that in the README.

**Comment by Lin-Buo-Ren** [comment]
Got it, thanks!

Feel free to close this issue when the problem is solved.

**Comment by jackycute** [comment]
Fixed in 2be9db9bf243bba11e00d87b92e674b23525e4fd
