### ISSUE TITLE
Have disabled anonymous usage, can anonymously create new note on free URL 

### ISSUE THREAD

**Issue by crosswick** [hackmdio/codimd#1476]
CMD_ALLOW_FREEURL=true overrides CMD_ALLOW_ANONYMOUS=false ?

I have both in my docker-based install of CodiMD; when I open up a free url on my CodiMD domain (in Chrome incognito mode, without having signed in anywhere) I simply get access!

I've also tested whether adding these lines makes any difference, which they shouldn't and don't:
CMD_ALLOW_ANONYMOUS_EDITS =false
CMD_ALLOW_ANONYMOUS_VIEWS=true

Love the platform btw

**Comment by crosswick** [comment]
Even weirder: when I'm signed in (via email), typing in a free URL results in an Internal Server Error. At the same time the free URL note creation is still available from the Incognito, not-signed in browser window.

**Comment by crosswick** [comment]
Ah good to hear @jackycute, thanks. BTW two features that I thought of because of this: being able to choose a free URL after clicking New Note, and 'save as' to a free URL

**Comment by jackycute** [comment]
> Ah good to hear @jackycute, thanks. BTW two features that I thought of because of this: being able to choose a free URL after clicking New Note, and 'save as' to a free URL

Thanks for suggestion.
Could you open new issue to address your idea in detail?

**Comment by crosswick** [comment]
Alright I will.

**Comment by jackycute** [comment]
@crosswick could you pull the latest 2.0.1 image and test if this version solve this issue?

**Comment by crosswick** [comment]
It does! Issue is solved. That was quick :) Thank you!

**Comment by jackycute** [comment]
You're welcome! Thanks for people who contribute this 😄
