### ISSUE TITLE
Feature Request: ability to gain access to a note by clicking/pasting the URL once

### ISSUE THREAD

**Issue by crosswick** [hackmdio/codimd#1480]
Say I click on or paste a URL of a note that I would like to participate in 
I will first get an error saying "You are not allowed to access this page. Maybe try logging in?"
Then I log in - instead of getting to the note though, I will get the homepage of the CodiMD server.
So then I have to go back and click or paste the link again...

I think it would be great if after logging in, you get to the note in question immediately.

**Comment by jackycute** [comment]
Hi @crosswick,
I think this might duplicate with #1431 ?

**Comment by crosswick** [comment]
@jackycute correct, I hadn't seen that one. AFAIK this issue may be merged or deleted.
