### ISSUE TITLE
GitHub avatar invalid URL

### ISSUE THREAD

**Issue by paroxp** [hackmdio/codimd#1489]
## What

Noticed that after authenticating with github, the avatar URL is a little malformed.

```
https://avatars3.githubusercontent.com/u/2418945v=4?s=96
```

Notice the `v=4` just after ID is effectively part of the ID, which should not be the case.

It's caused by this piece of code:

https://github.com/hackmdio/codimd/blob/d7cc95129d98fe81adf15dee973a434f9a739476/lib/models/user.js#L117-L122

## Potential solution

```javascript
const u = new URL(profile.photos[0].value);
if (bigger) { u.searchParams.set('s', 400) } else { u.searchParams.set('s', 96) }
photo = u.toString();
```

Or more human example:

```javascript
const u = new URL('https://avatars3.githubusercontent.com/u/2418945?s=60&v=4');
u.searchParams.set('s', 96);
console.log(u.toString());
```

**Comment by jackycute** [comment]
Hi @paroxp,

Thanks for reporting this.
Nice catch! I think you're right, could you open a PR for this?

**Comment by paroxp** [comment]
will do later in the day 👍
