### ISSUE TITLE
Reduce size of final docker image

### ISSUE THREAD

**Issue by cruisemaniac** [hackmdio/codimd#1492]
Hey folks,

My first issue here. I just built the docker image using the Dockerfile in the `./deployments` folder. The image turns out to be 1.77GB. This is too massive for a notes / markdown app.

If there's someone who's working on reducing the size, I'd love to help. Or if I'm missing something, please let me know.

**Comment by jackycute** [comment]
Hi @cruisemaniac,

Thank for opening issue.
We're currently working on it.
It's related to the dependencies bundling and how we compose the docker image, will try to make it less than 1GB in the next version release.

**Comment by jackycute** [comment]
I think we've managed to reduced the image size to be less than 1GB.
<img width="1286" alt="截圖 2021-05-13 上午12 03 51" src="https://user-images.githubusercontent.com/2639151/118007504-c78ba100-b37e-11eb-9bef-089f4457406b.png">
