### ISSUE TITLE
Tags in YAML metadata can't handle arrays

### ISSUE THREAD

**Issue by daniele-athome** [hackmdio/codimd#1496]
I can see CodiMD [can only handle a comma-separated string of tags](https://github.com/hackmdio/codimd/blob/develop/lib/models/note.js#L371), so using array notation doesn't work:

```
tags: [tag1, tag2, tag3]
tags:
  - tag1
  - tag2
  - tag3
```

That is valid YAML syntax and such an enhancement would greatly benefit interoperability with other Markdown processing software. Thanks!!!

**Comment by daniele-athome** [comment]
I believe I did it, would you be interested in a pull request?

https://github.com/daniele-athome/codimd/commit/d671cd78f0f87f8814cbf54a359263d05aae6bc9

**Comment by jackycute** [comment]
Hi @daniele-athome,

For sure, we would greatly thank you for opening PR!
