### ISSUE TITLE
CodeMirror div covered by status-bar

### ISSUE THREAD

**Issue by professeurb** [hackmdio/codimd#1510]
In some frequent occasion (which I haven't figured out yet), the bottom of the code editing pane (the "CodeMirror" div) gets covered by the status-bar, so that it is not possible to see most of the bottom line in the code pane… which is precisely the line where you enter your code once it is too long to fit in the pane.

**Comment by jackycute** [comment]
Fixed by https://github.com/hackmdio/codimd/pull/1531
