### ISSUE TITLE
some of notes is hidden  after upgrade from 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by chenboshiun** [hackmdio/codimd#1523]
Hello CodiMD Support:

some of user's notes is hidden, after we upgrade the CodiMD from 1.5.0 to 1.6.0

User can not find it on note dashboard, but can read / write via url if he remember note url

How can i help my user fix to this problem ?

Thanks :)

**Comment by jackycute** [comment]
Hi @chenboshiun,
Sorry for the late reply. We need more information to address this issue.
Maybe you are pointing a note that actually created and owned by another user?
Feel free to reopen if you can reproduce this in the latest version, thank you!
