### ISSUE TITLE
How can I prevent guests viewing ?

### ISSUE THREAD

**Issue by Aincvy** [hackmdio/codimd#1524]
Here is the part of my config file.
```yaml
environment: 
  - CMD_ALLOW_ANONYMOUS=false
  - CMD_ALLOW_EMAIL_REGISTER=false
```

Now, the guests can view content via URL-access, he cannot edit content without login.

Expect: if someone accesses the url, jump to index page.

BTW, if I publish a page, can I cancel it?

**Comment by Aincvy** [comment]
And why I can't delete the notes?

**Comment by jackycute** [comment]
Hi @Aincvy, please read the doc for anonymous settings:
https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fnote-permission#Anonymous-Guest-related-config

The notes created by Guest are not able to be deleted by anyone since there is no way to verify the owner at the moment.

**Comment by Aincvy** [comment]
Hi, @jackycute 
It's very happy to get your response.

After the test, I think the environment option 'CMD_ALLOW_ANONYMOUS_VIEWS' does not work.
The option 'Limited' works.
Here is my work step.

1. Delete the old container.
2. Change `docker-compose.yml` add code to it
3. ```yaml
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_ANONYMOUS_VIEWS=false
      - CMD_DEFAULT_PERMISSION=limited
   ```
4. Call shell cmd `docker-compose up -d`.
5. Login account and access the node url.
6. Log out and refresh the page.
7. I can still see the note content.
8. I send the URL to my friends, they can view the note content.
9. I change permission to limited, then they can't view the note content.

At last, a little advice, move `delete this note` from the permission list to menu list.

**Comment by jackycute** [comment]
Feel free to re-open this if you need further help!
