### ISSUE TITLE
Multiple Instances or scaling of the app

### ISSUE THREAD

**Issue by jdauphant** [hackmdio/codimd#1529]
Hello,

Can I launch multiple instance of the app with the same database, does it work ? or the app need to be alone ?
(I haven't found that on docs neither how we scale the app)

Thanks for your help,
Julien

**Comment by jackycute** [comment]
Hi @jdauphant,
Thanks for reaching us.
We only recommend to run CodiMD as single instance, to avoid a user join notes from many instances you will need to setup load balancer with sticky session. There is no guide or doc for this at the moment.

**Comment by jdauphant** [comment]
Hello, thanks for your answer. 
You mean sticky per user or per note ? 
If some users join the same note from different server, it will work?

**Comment by jackycute** [comment]
Yes, users can access a note on a instance, join from server won't work.

**Comment by jackycute** [comment]
This seems a bit out of work.
Feel free to re-open if someone likes to work on this.
