### ISSUE TITLE
Night mode: no edit/both button highlight

### ISSUE THREAD

**Issue by martinthomson** [hackmdio/codimd#1539]
When night mode is on, the "View" mode toggle is highlighted correctly (it appears slightly darker).  However the "Edit" and "Both" options do not highlight in this way.

The install appears to be using 2.1.0.

**Comment by WillGoGithub** [comment]
![image](https://user-images.githubusercontent.com/45837931/88244540-b924a980-ccc6-11ea-9049-aac5c45f4c92.png)

**Comment by tamo** [comment]
The CSS can be relaxed.

```
diff --git a/public/css/index.css b/public/css/index.css
--- a/public/css/index.css
+++ b/public/css/index.css
@@ -411,7 +411,7 @@ div[contenteditable]:empty:not(:focus):before{
     color: #eee;
 }
 
-.night .btn.btn-default.ui-view.active{
+.night .btn.btn-default.active{
     background: #202020;
 }
 
```

**Comment by tamo** [comment]
Thanks!
