### ISSUE TITLE
求一个word导入功能

### ISSUE THREAD

**Issue by suxue** [hackmdio/codimd#1562]
有大量的本地word文件，有没有办法批量导入呢

**Comment by Yukaii** [comment]
目前我們並不原生支援此功能，但是您可以用  [`hackmd-cli`](https://github.com/hackmdio/hackmd-cli) 工具，加上 [pandoc](https://pandoc.org/) 來實現

1. 用 pandoc 把 word 文件轉成 markdown 檔案
2. 使用 `hackmd-cli` 匯入 markdown 檔案

**Comment by jackycute** [comment]
若有任何問題，歡迎重新開啟此 issue
