### ISSUE TITLE
RTL languages support

### ISSUE THREAD

**Issue by themedleb** [hackmdio/codimd#1563]
Support for auto language directions (include `dir=“auto”` in the HTML markup of each element like paragraph, heading, list, to-do list, …).
This is so much important for RTL languages like Arabic, Hebrew and others.

**Comment by jackycute** [comment]
Hi @themedleb, thanks for reaching us.
We do support dir attribute at the moment, please add dir in the yaml metadata, please learn more here: https://codimd-app.herokuapp.com/s/yaml-metadata#dir

**Comment by themedleb** [comment]
Hey @jackycute thanks for your reply.
That's what I already use right now as a work around, but it's very tiring to include it in every note you create even with the use of Templates. That's nothing like:
1. Create a new note.
2. Start typing.
