### ISSUE TITLE
Import all existing .md files at once from local storage (PC)

### ISSUE THREAD

**Issue by themedleb** [hackmdio/codimd#1564]
Import all existing .md notes at once from local storage, instead of: one by one.

Not sure if this already exist (because it’s crucial for new comers), but have no idea how to achieve it.

**Comment by jackycute** [comment]
Hi @themedleb,
Thank for reaching us.
You can achieve this by our cli tool: https://github.com/hackmdio/hackmd-cli#hackmd-cli-import-file
To import all `.md` files under a directory, please use bash script like:
```
#!/bin/bash
for filename in *.md; do
    hackmd-cli import "$filename"
done
```

**Comment by themedleb** [comment]
Thank you, I used this code before and it worked, would love a one click in the UI for less tech savvy/beginners though.
