### ISSUE TITLE
imageUploadType use s3 with docker ,can't use

### ISSUE THREAD

**Issue by FunTW** [hackmdio/codimd#1572]
Install 2.2.0 with docker .
When imageUploadType set to s3 .
Upload image have error
> Error response received from instance metadata service codimd

I find a way can fix it 

* /lib/imageRouter/s3.js
```
const credentials = {
  accessKeyId: config.s3.accessKeyId,
  secretAccessKey: config.s3.secretAccessKey,
}

const s3 = new S3Client({
  credentials,
  region: config.s3.region
})

```
reference https://github.com/aws/aws-sdk-js-v3/issues/1396

**Comment by tarlety** [comment]
I cannot upload images to s3 with codimd 2.2, too.

```
error: 	Error: Unable to connect to instance metadata service
info: 	x.x.x.x - - [01/Sep/2020:12:29:03 +0000] "POST /uploadimage HTTP/1.1" 500 - "https://xxx.com/xxxxxx?both" "Mozilla/5.0...
```

The fix (to supply credentials in a credentials object) works for me. (tested in 1559c0c)
```
info: 	x.x.x.x - - [01/Sep/2020:12:48:11 +0000] "POST /uploadimage HTTP/1.1" 200 110 "https://xxx.com/xxxxxx?both" "Mozilla/5.0..."
```

---

aws/aws-sdk-js-v3#1396 also mentions that preview version is old and deprecated.

Maybe someone can help to check if latest gamma version had fixed this issue or not?
https://www.npmjs.com/package/@aws-sdk/client-s3/v/1.0.0-gamma.7

**Comment by soulchild** [comment]
So, what's the status on this? 

For me, the S3 upload in the current CodiMD v2.3.2 is still completely broken: `Error response received from instance metadata service`

**Comment by jackycute** [comment]
Hi everyone, could you reproduce this in version 2.4.1?

**Comment by jakubgs** [comment]
Nope.
```
info: #011deserializeUser: e3131308-5bbd-4996-88fb-83535a1dc2ce
error: #011Error: Error response received from instance metadata service
info: #011172.17.1.1 - - [12/May/2021:18:59:32 +0000] "POST /uploadimage HTTP/1.1" 500 - "https://notes.example.or/abcxyz?both"
```
