### ISSUE TITLE
CodiMD@1.6.0: LDAP authentication is not working

### ISSUE THREAD

**Issue by renjithkm86** [hackmdio/codimd#1573]
Hi Team,

I am getting the below error in browser when I use LDAP authentication:
![image](https://user-images.githubusercontent.com/50958130/90153916-26e46280-dda7-11ea-929e-b4edd49e68d3.png)

The error I am observing in the syslog is:

Aug 13 15:16:40 codimd npm[1337]: SizeLimitExceededError: Size Limit Exceeded
Aug 13 15:16:40 codimd npm[1337]:     at messageCallback (/root/server/node_modules/ldapjs/lib/client/client.js:1418:45)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.onMessage (/root/server/node_modules/ldapjs/lib/client/client.js:1088:14)
Aug 13 15:16:40 codimd npm[1337]:     at emitOne (events.js:116:13)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.emit (events.js:211:7)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:111:8)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)
Aug 13 15:16:40 codimd npm[1337]:     at Parser.write (/root/server/node_modules/ldapjs/lib/messages/parser.js:112:10)
Aug 13 15:16:40 codimd npm[1337]:     at end (/root/server/node_modules/ldapjs/lib/messages/parser.js:66:19)

The LDAP parameters I am using are:

            "url": "ldaps://xxxx.com:636",
            "bindDn": "CN=xxxxxxx,OU=Users,OU=xxxxxxx,OU=x,DC=xxxxx,DC=xxxxx,DC=xxxx",
            "bindCredentials": "xxxxxxxx",
            "searchBase": "DC=xxxxxxxx,DC=xxxxxxx,DC=xxxxxxxx",
            "searchAttributes": "displayName",
            "searchFilter": "(objectClass=user)",
            "useridField": "sAMAccountName",
            "searchScope": "sub",

versions:-

root@codimd:~# npm -v
5.6.0

root@codimd:~/server# node -v
v8.9.4

root@codimd:~/server# nvm current
v8.9.4

CodiMD@1.6.0

**Comment by jackycute** [comment]
Hi @renjithkm86,

Sorry for late reply.
Could you still reproduce this in the latest version 2.4.1?

**Comment by renjithkm86** [comment]
It is resolved. I am in 1.6.0. I am trying to upgrade to 2.3.2 but it fails while starting codimd. I will open a new ticket.
