### ISSUE TITLE
Shortly after startup, CodiMD fails to load notes

### ISSUE THREAD

**Issue by Schuermi7** [hackmdio/codimd#1576]
Hello, shortly after I startup the Docker Containers running CodiMD, everything works fine but after about 5-10 minutes it stops working and I get disconnected from a note, I was working on. Other notes work fine and after a restart, the note is accessible again.
```app_1       | 2020-08-18T14:08:38.525Z error:   Operation timeout
app_1       | 2020-08-18T14:08:38.526Z error:   updateDirtyNote: note not found:
app_1       | 2020-08-18T14:08:38.525Z error:   updateDirtyNote: updater error  Operation timeout
app_1       | 2020-08-18T14:08:40.522Z error:   Operation timeout
app_1       | 2020-08-18T14:08:40.522Z error:   updateDirtyNote: note not found:
app_1       | 2020-08-18T14:08:40.522Z error:   updateDirtyNote: updater error  Operation timeout
```
I observed this for notes, that were present, when I upgraded from 1.6.0 to the latest deployment of CodiMD.
I use PostgreSQL 9.6 which worked flawlessly before.

**Comment by jackycute** [comment]
Hi @Schuermi7,
This usually happens when your instance doesn't have enough resource (CPU or memory) to keep up.
Please monitor it and give it at least 2 CPU and 2GB memory.
If you still can reproduce this in latest version, feel free to reopen this, thank you!
