### ISSUE TITLE
ERROR: password authentication failed for user "hackmd"

### ISSUE THREAD

**Issue by RayMacLewis** [hackmdio/codimd#1584]
Hey guys,
i followed the install instruction for Docker Deployment given here: [Link](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment)
I installed CodiMD on Docker for Windows as well as on Ubuntu 18.04 and get the same behaviour.

I used:
```bash
git clone https://github.com/codimd/container.git codimd-container
cd codimd-container
sudo docker-compose up
```
This is just working fine.

But as soon as I change the password in `./docker-compose.yml` (in `- POSTGRES_PASSWORD=hackmdpass_test` and in `- CMD_DB_URL=postgres://hackmd:hackmdpass_test@database:5432/hackmd` and run `sudo docker-compose up` I'll get:
```bash
app_1       | ERROR: password authentication failed for user "hackmd"
```

What am I doing wrong? I searched and tried for over 3 hours now and I'm very surprised that I can't see anyone else with this issue?

Thanks in advance
Ray

**Comment by tamo** [comment]
You didn't follow the guide. You had to change the password before docker-compose up.
You can search for how to use docker commands. (build, down, rmi, and so on...)

**Comment by RayMacLewis** [comment]
Hey @tamo,
thanks a lot for your quick reply. Although I was quite sure I did test that yesterday on a completely fresh server your reply made me think again and it turned out I probably did not remember correctly.

After starting the containers with the default configuration it creates a database which the PostgreSQL container stores on the host automatically. When you bring CodiMD down with `docker-compose down` it does not kill the database. When you then change the password only (in the `docker-compose.yml` file and try to bring it up again it does not match the password you have in the database stored on the host which you would need to change by hand. If you have a fresh installation and do not care about the old database you can run these commands:

**WARNING! This will delete your database!**
```bash
# Find CodiMD container IDs
docker container ls --all
# Remove all of them with:
docker container rm CONTAINER_ID

# Find the CodiMD database volume
docker volume ls
# Remove CodiMD database volume
docker volume rm DATABASE_ID
```

I hope this helps others that might have the same issue!
Ray
