### ISSUE TITLE
doctoc anchors not working with codimd (lowercase/uppercase?) 

### ISSUE THREAD

**Issue by arthurlogilab** [hackmdio/codimd#1590]
I've tried using https://github.com/thlorenz/doctoc with a document in codimd but the anchors generated don't work with codimd. I think it is because they are lowercase as the generated anchors use normal case (keeping the uppercases in the titles). 

It seems the anchors generated in github/bitbucket etc. use lowercase, is there a good technical reason for this ? if so, could codimd change it's anchors ? If not, I'll go on the doctoc issues to ask if a "codimd" mode can be added to the generator. 

Are there any other smart ways of doing this ? Could it be integrated directly in the browser (right now I have to download the markdown, run doctoc and copy/paste the Table of contents).

**Comment by arthurlogilab** [comment]
@jackycute Thanks for the tip, so this is a server side setting ? and changes for all existing documents right ?

**Comment by jackycute** [comment]
> @jackycute Thanks for the tip, so this is a server side setting ? and changes for all existing documents right ?

Exactly.

**Comment by scottrigby** [comment]
It would be nice to add this as a setting inside hackmd.io, since there's also an option to integrate with GitHub. Or is there a better place for hackmd.io issues?

**Comment by jackycute** [comment]
We already have an issue there: https://github.com/hackmdio/hackmd-io-issues/issues/27
Also planned but no ETA for this, thank you!
