### ISSUE TITLE
Cover page has wrong links when linkifyHeaderStyle is not "keep-case"

### ISSUE THREAD

**Issue by tamo** [hackmdio/codimd#1594]
`/features#Share-Notes` is valid only when `linkifyHeaderStyle` is `"keep-case"` (default).

You should add
```
app.locals.linkifyHeaderStyle = config.linkifyHeaderStyle
```
to app.js
and `<% if...` to public/views/index/body.ejs

**Comment by Yukaii** [comment]
Cannot reproduce on latest develop commit
