### ISSUE TITLE
codimd cannot be embedded into another page (e.g. raw HTML or React) via iframe

### ISSUE THREAD

**Issue by xpire** [hackmdio/codimd#1598]
Reproduce:
1. Host codimd via docker-compose as seen [in this guide](https://hackmd.io/s/codimd-docker-deployment) or by following instructions in [codimd/container]( https://github.com/codimd/container). Preferably have the anonymous flag set so you don't need to be logged in to use codimd.
2. generate a page with /new and remember the url
3. create a super simple html document that looks like this
```html
<head><head/>
<body>
                <iframe src="http://localhost:3000/llQUa770R82vnBJSKCyuOA" width="1000px" height="1000px"/>
</body>
```
4. run the file, and observe, the iframe will load in, but the spinner appears and never finishes loading, if someone else goes to the same document normally, they will see another person on the page but the iframe person sees nothing.

I tried doing this in React initially, and was confused as to why it didn't work when someone said it would work #386 , I went all the way back to raw html and was surprised to see it was a codimd problem, as even in raw html it still cannot render itself in an iframe.

Just wondering, what am I doing wrong? I've seen in a [youtube video](https://youtu.be/Tw7ucd2lKBk?t=52) where someone was using this technology actually got it work, and I'm not sure how they did it.

**Comment by maybegeek** [comment]
Hi there,

perhaps this issue is solved, because:

```
<iframe width="100%" height="500" src="https://codimd.c3d2.de/features" frameborder="0"></iframe>
```

works as expected.

(also: slash typo in `<head><head/>`)

thanks,
christoph

**Comment by jackycute** [comment]
Glad you solve it.
