### ISSUE TITLE
some listed filename become links

### ISSUE THREAD

**Issue by changsijay** [hackmdio/codimd#1613]
```
- file1.sh
- file2.js
- file3.py
```

in preview shows

![Screen Shot 2020-10-08 at 3 30 21 PM](https://user-images.githubusercontent.com/245306/95434221-3208d880-097b-11eb-8f20-a5a7c314ce8e.png)

should them be just plain text?

**Comment by jackycute** [comment]
Hi @changsijay, thanks for reaching us.
This is intended feature called "linkify" (https://github.com/markdown-it/linkify-it).
You can make them as code (`file1.sh`) to escape from this.
