### ISSUE TITLE
Features not Available in 2.2.0

### ISSUE THREAD

**Issue by md-ae** [hackmdio/codimd#1615]
Hi,

I'm using the docker image `nabo.codimd.dev/hackmdio/hackmd:2.2.0`. [Based on the documentation](https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fextra-supported-syntax#Extra-Supported-Syntax), I expected to see the `/features` page show documentation for the following, but it doesn't:
- Vega-Lite
- PlantUML
- Geo Map
- Mindmap
- Guitar Tab

After testing the features:
- Vega-Lite, works.
- PlantUML, works.
- Geo Map, doesn't work.
- Mindmap, works.
- Guitar Tab, doesn't work.

Is this expected behaviour?

Thanks

**Comment by unode** [comment]
Are you sure you are using 2.2.0 and not 2.1.0? All the above work for me.

Consider deleting the image from docker and re-downloading to double-check.

**Comment by jackycute** [comment]
Hi @md-ae, thanks for reaching us.
I think all the features all working, you can check it here: https://codimd-app.herokuapp.com/features
For the geo map feature, I've added a test note here: https://codimd-app.herokuapp.com/rBqqBljoRiG4LbhaK7RJgQ
Feel free to re-open if you need further help!
