### ISSUE TITLE
'theme' option for slides not working

### ISSUE THREAD

**Issue by MartiniMoe** [hackmdio/codimd#1620]
Im trying to chose a theme for my slides like this:

```
---
type: slide
slideOptions:
  theme: beige
---
```

but it has no effect. I tried it on different instances of codimd as well, it does seem to work anywhere.

**Comment by jackycute** [comment]
Hi @MartiniMoe,
Thanks for reaching us.
The slideOptions only works in slide mode, it has no effect in editing page.
