### ISSUE TITLE
no referer when fetch a s3 image?

### ISSUE THREAD

**Issue by xxxsen** [hackmdio/codimd#1640]
# Steps to reproduce

1. upload image to in the note.
2. open note in other windows or refresh the editor

How to configure it when I need to add a referer?

![image](https://user-images.githubusercontent.com/3880276/102991976-54ab9600-4555-11eb-9f9b-93a6f408ab82.png)
![image](https://user-images.githubusercontent.com/3880276/102992221-ca176680-4555-11eb-8c21-d036c1bec2d0.png)

**Comment by jackycute** [comment]
Hi @xxxsen, thanks for reaching us.
However, from the image you attached, the host is "cos.ap-chengdu.myqcloud.com", you need to config that service to provide referrer.
As far as I can tell this is not related to CodiMD itself, feel free to provide more context, thank you!

**Comment by xxxsen** [comment]
Thank you for replying.
emmm, it seems that I should change the referrer policy from ‘same-origin’ to ‘origin-when-cross-origin’ or ‘strict-origin-when-cross-origin’
is there any way to change it?


https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

![image](https://user-images.githubusercontent.com/3880276/109518933-b6ecbe00-7ae5-11eb-9dbc-e883186457ef.png)

**Comment by jackycute** [comment]
Hi @xxxsen,
We use helmet to protect our app, you can change it here: https://github.com/hackmdio/codimd/blob/6585976e4d85fa8203a37b65f9c25ad21bd7c12e/app.js#L107
Although it's been set to same-origin for security reasons, we don't recommend to change that.
You can either change that by yourself or open config for that.
