### ISSUE TITLE
Feature Request: Support for MathJax in Code Tags

### ISSUE THREAD

**Issue by H-B-Schmidt** [hackmdio/codimd#1647]
It would be helpfull when Mathjax is also supported within Code tags. 
This is usefull for example to write pseudo code in educational classes.

**Comment by jackycute** [comment]
Hi @H-B-Schmidt,
Thanks for suggestion!
However, this will be hard if a user wants to keep the plain text in the code tags.
I just confirmed you can achieve this by using wrapping mathjax with code tag.
```
<code>$a+b=c$</code>
```

Feel free to reopen if you need further help.
