### ISSUE TITLE
Feature: Auto format table

### ISSUE THREAD

**Issue by whitsunndale** [hackmdio/codimd#1655]
When creating a table, automatically align all entries of the table to make it pretty.
Basically like [this vscode extension](https://marketplace.visualstudio.com/items?itemName=TakumiI.markdowntable).

**Comment by jackycute** [comment]
Hi @whitsunndale, thanks for reaching us.
We've supported table tools since version 1.4.0, learn more here: https://hackmd.io/@codimd/release-notes/%2F%40codimd%2Fv1_4_0#New-Table-Tools

**Comment by jackycute** [comment]
Feel free to file another issue if you're looking for something else.

**Comment by whitsunndale** [comment]
Oh,  I didn't see the tools in the gui, my bad. It seems the keyboard shortcuts are not working, even though it looks like it was intended ([in this code](https://github.com/hackmdio/codimd/blob/181adbd08e3a61aa0738e43844a9f5dcd6a20036/public/js/lib/editor/table-editor.js#L181) ). Going to make another issue.

**Comment by whitsunndale** [comment]
Nevermind, I just found out that it was just a user setting. All good. Thanks :)
