### ISSUE TITLE
Heroku deployment fail

### ISSUE THREAD

**Issue by buslovv** [hackmdio/codimd#1657]
Heroku requre **SSL mode** for postgres connections, but `sequelize db:migrate && node app.js` always run with `SSL off`.
Try deploy with Docker (`heroku:container`), One Click Deployment, git Deployment - same result.
```
...
2021-02-11T06:22:28.954983+00:00 app[web.1]: Parsed url postgres://notadsewaccqnt:*****@ec2-34-254-69-72.eu-west-1.compute.amazonaws.com:5432/d7co6dtp1700qs
2021-02-11T06:22:29.028092+00:00 app[web.1]: ERROR: no pg_hba.conf entry for host "34.248.46.164", user "notadsewaccqnt", database "d7co6dtp1700qs", SSL off
```

**Comment by soulchild** [comment]
Same here. We tried a couple of variations on the connection string params like `?ssl=true` and `?sslmode=require` and even setting the `PGSSLMODE` environment variable to `no-verify`, but Sequelize keeps connecting to the Postgres database without SSL.  

Maybe updating the pg driver dependency might help with this? See: https://github.com/brianc/node-postgres/blob/4bc55834b93f945e3b60378db121e739e0950f92/CHANGELOG.md#pg810

**Comment by Yukaii** [comment]
@soulchild Could you try setting `PGSSLMODE` to `require`? That fixed our heroku deployment with current node-postgres version. (#1660)

**Comment by soulchild** [comment]
@Yukaii Thanks, I'll give that a try. Already found the relevant part in `node-postgres@6.1.6`: 

https://github.com/brianc/node-postgres/blob/b0a2fe45059ba9d2c6279695260dd0a61fee99dc/lib/connection-parameters.js#L31-L42

Seems like `no-verify` is just not supported yet in that version.

**Comment by soulchild** [comment]
Indeed, this fixed the Postgres SSL-only connection problem: :+1:
