### ISSUE TITLE
NOTES table has data,but view page query none,use shortid for uri can get it

### ISSUE THREAD

**Issue by liangzm1985** [hackmdio/codimd#1658]
NOTES table has data,but view page query none,use shortid for uri can get it

**Comment by liangzm1985** [comment]
I have solved this problem, the reason is that the history field in the users table is too small, the default is TEXT, the maximum support is 65535, I will change to LONGTEXT

**Comment by jackycute** [comment]
Thank you for reporting @liangzm1985.
Glad you found the solution!
