### ISSUE TITLE
image registry server issue

### ISSUE THREAD

**Issue by kfox1111** [hackmdio/codimd#1666]
There is a problem with non docker clients downloading images. It fails with podman and containerd, but works with docker:

Containerd based cluster:
Failed to pull image "nabo.codimd.dev/hackmdio/hackmd:2.3.2": rpc error: code = Unknown desc = failed to pull and unpack image "nabo.codimd.dev/hackmdio/hackmd:2.3.2": failed to resolve reference "nabo.codimd.dev/hackmdio/hackmd:2.3.2": unexpected status code [manifests 2.3.2]: 401 Unauthorized

Podman:
$ podman pull nabo.codimd.dev/hackmdio/hackmd:2.3.2
Trying to pull nabo.codimd.dev/hackmdio/hackmd:2.3.2...
  unauthorized: authentication required
Error: unable to pull nabo.codimd.dev/hackmdio/hackmd:2.3.2: Error initializing source docker://nabo.codimd.dev/hackmdio/hackmd:2.3.2: Error reading manifest 2.3.2 in nabo.codimd.dev/hackmdio/hackmd: unauthorized: authentication required

Docker:
$ docker pull nabo.codimd.dev/hackmdio/hackmd:2.3.2
2.3.2: Pulling from hackmdio/hackmd
afb6ec6fdc1c: Pull complete 
028320f35da4: Pull complete 
604b1ee35399: Pull complete 
cab2ed2dbd76: Pull complete 
485ae074d3d0: Pull complete 
350347983bdd: Pull complete 
4f4fb700ef54: Pull complete 
883af4af420c: Pull complete 
7cbe4b2080e1: Pull complete 
Digest: sha256:40b5df943bb762bcd874e86969eb7d4a8c993a52806ef63099104df9d13a1235
Status: Downloaded newer image for nabo.codimd.dev/hackmdio/hackmd:2.3.2
nabo.codimd.dev/hackmdio/hackmd:2.3.2

Since docker uses containerd these days, its possible this is a server based client string detection issue?

**Comment by jackycute** [comment]
Hi @kfox1111,
Thanks for reporting to us.
Please use hackmdio/hackmd:2.4.1 from dockerhub instead, since nabo.codimd.dev does not support podman.
