### ISSUE TITLE
Default Login for localhost:3000?

### ISSUE THREAD

**Issue by jcalfee** [hackmdio/codimd#1669]
What is the login for localhost:3000 after I start hackmdio/hackmd:2.3.2 from docker-compose?

Reference: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment

**Comment by a60814billy** [comment]
Hi @jcalfee, there are **no** default login user, just register a new user.

**Comment by jcalfee** [comment]
I see .. I though I might have to have a email server to do that.  It just let me in .. thanks
