### ISSUE TITLE
CodiMD v2.3.2

### ISSUE THREAD

**Issue by renjithkm86** [hackmdio/codimd#1681]
Hi Team,

I am trying to upgrade my CodiMD v1.6.0 to v2.3.2. I observed the following error while starting:

root@hackmd-dev:~/codimd-2.3.2# npm start --production

> codimd@2.3.2 start /root/codimd-2.3.2
> sequelize db:migrate && node app.js

Sequelize CLI [Node: 12.22.1, CLI: 5.5.1, ORM: 5.21.3]

Parsed url postgres://codimd:*****@localhost:5432/codimd
== 20180306150303-fix-enum: migrating =======

ERROR: type "enum_Notes_permission" already exists

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codimd@2.3.2 start: `sequelize db:migrate && node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codimd@2.3.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-13T06_22_06_361Z-debug.log

> node --version
v12.22.1
> npm --version
6.14.12
> nvm --version
0.35.3

Please help to resolve it.

**Comment by jackycute** [comment]
Hi @renjithkm86,
Please backup your DB first.
It seems you already has the ENUM we need in the migration, let's skip it.
Look at "SequelizeMeta" table in your db, adding a row with name "20180306150303-fix-enum.js".
Then try to run migrate again.

**Comment by renjithkm86** [comment]
Thanks a lot for the quick response! I was able to fix the issue by doing this.
