### ISSUE TITLE
CodiMD 2.3.2 local PlantUML not rendering images

### ISSUE THREAD

**Issue by renjithkm86** [hackmdio/codimd#1692]
Hi Team,

I am trying to use local PlantUML for rendering images. But it is not working. 

The steps I tried:

root@test1:~# docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat
Unable to find image 'plantuml/plantuml-server:tomcat' locally
tomcat: Pulling from plantuml/plantuml-server
69692152171a: Pull complete
ce2b89b60818: Pull complete
6584437267ff: Pull complete
2a57595b940f: Pull complete
34cbaaf9fdee: Pull complete
36b3eb942464: Pull complete
4434c5bc1f83: Pull complete
bd0720e399e1: Pull complete
8f23514929d3: Pull complete
2f6f7a95fea6: Pull complete
93d4da05914d: Pull complete
328b4b8ea6fe: Pull complete
Digest: sha256:4c7ac2b89834d544e09c657a13021e47743e1f7a6c0701f629b1f91f5b2521fb
Status: Downloaded newer image for plantuml/plantuml-server:tomcat
708f0d3bc6c34fb7c3cbebdc3115cd8e9ac6c9ba7cf83613f6aba07cf0d4b572

root@test1:~# docker ps
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS              PORTS                    NAMES
708f0d3bc6c3        plantuml/plantuml-server:tomcat   "catalina.sh run"   18 seconds ago      Up 16 seconds       0.0.0.0:8080->8080/tcp   angry_pike

I can access the PlantUML via http://<local IP>:8080 
![image](https://user-images.githubusercontent.com/50958130/121186008-47286500-c884-11eb-9d5c-7fa003562bf4.png)

I added this in CodiMD config.json like:

        "plantuml":
        {
          "server": "http://<local IP>:8080"
        },

Then restarted Codimd service. 

But it is not rendering the image(external PlantUML URL works well):

![image](https://user-images.githubusercontent.com/50958130/121185781-0c263180-c884-11eb-9900-9a5e7a3636e1.png)

What could be the issue?

**Comment by jackycute** [comment]
Hi @renjithkm86,
Thanks for reaching us.
Could you inspect the broken image and let us know the image url?
You can also try access that image url in your browser and see if you got correct plantuml request url.

**Comment by renjithkm86** [comment]
Yeah it is making https connection to the local PlantUML server. It started working when I setup SSL. Thanks for your help!
