### ISSUE TITLE
404 my file

### ISSUE THREAD

**Issue by SWBMESSI** [hackmdio/codimd#1714]
https://codimd-app.herokuapp.com/f-0zfl26RJCmNkOshuFf7g

**Comment by jackycute** [comment]
Hi @SWBMESSI,

Thanks for reaching us.
https://codimd-app.herokuapp.com is only for demo purpose.
Its DB will flush once in a while, please don't put any important data in there.

**Comment by jackycute** [comment]
We might able to pull some md files from last auto backup of heroku, please send email to max@hackmd.io and let us know the note url, user account you are looking for, there is no guarantee though.
