### ISSUE TITLE
Help setting up an instance on Heroku

### ISSUE THREAD

**Issue by drupol** [hackmdio/codimd#1719]
Hi,

I'm trying to setup CodiMD on Heroku, without success, I have a white page of the death.

Here's the Heroku log: https://0bin.net/paste/+IKwwLML#072u0srCIyEtsLOs0FAgsMEO8xCfCVbcVyVts0eYA2i

To install the instance, I clicked here: https://hackmd.io/s/codimd-heroku-deployment ... and I don't know if there's something else to do, I can't find documentation on that.

Could you please give a bit of help/documentation/information on this?

Thanks in advance.

**Comment by johnny12150** [comment]
https://github.com/hackmdio/codimd/issues/1721#issuecomment-961752679 should help!

**Comment by drupol** [comment]
Thanks! But with the lack of help, I switched to something else.
