### ISSUE TITLE
PDF printing does not yet support Chinese

### ISSUE THREAD

**Issue by XXTX-TOP** [hackmdio/codimd#1725]
PDF printing does not yet support Chinese，It seems that English printing is ok, is it the coding format?

**Comment by cwzsquare** [comment]
Well, if you're using docker to build, just change your image from `hackmdio/hackmd` to `hackmdio/hackmd:2.4.1-cjk` to solve. You can find the latest version with cjk in dockerhub.

**Comment by cwzsquare** [comment]
> Well, if you're using docker to build, just change your image from `hackmdio/hackmd` to `hackmdio/hackmd:2.4.1-cjk` to solve. You can find the latest version with cjk in dockerhub.

![image](https://user-images.githubusercontent.com/50974598/143015930-1a564690-cefd-400a-ada5-c7ac31df87da.png)

**Comment by jackycute** [comment]
Please use `-cjk` appended images like `hackmdio/hackmd:2.4.1-cjk` for supporting CJK font PDF exports.
It will need corresponding fonts to display on the OS that running for PDF exports.
