### ISSUE TITLE
Where Markdown File is persisted?

### ISSUE THREAD

**Issue by joujou77** [hackmdio/codimd#1727]
I have an installation of CodiMD but it's down at the moment due to internal DB issues.
I have edited one note/file there that I need urgently before the issue is resolved and teh instance will be up and running again.

Is there a way to locate that one content file and copy the markdown? iow, where the user contents are persisted?

Thank you!

**Comment by 94rain** [comment]
They are stored in the database (table `Revisions`? if I remember correctly)

**Comment by jackycute** [comment]
They are all in the DB.
Note stores in `Notes` table, `content` is the text body field.
Previous versions of the notes stores in `Revisions` table.
Hope this helps.
