### ISSUE TITLE
how to change password?

### ISSUE THREAD

**Issue by xdandyx** [hackmdio/codimd#1746]
I forgot my password, then how to reset it?

**Comment by yujingxiacai** [comment]
> I forgot my password, then how to reset it?

- 1. The first step is to download your existing `md` file,
- 2. Then delete the current account, 
- 3. Then re-register one with your current email or other email, 
- 3.  Finally copy `md` file in by yourself ( LOL )

**Comment by xdandyx** [comment]
> > I forgot my password, then how to reset it?
> 
> * 1. The first step is to download your existing `md` file,
> * 2. Then delete the current account,
> * 3. Then re-register one with your current email or other email,
> * 3. Finally copy `md` file in by yourself ( LOL )

This seems a bit contradictory, I have forgotten my password, how should I download `*.md`

**Comment by jackycute** [comment]
Hi guys, you can use the manage_users utility tool to reset password, please look at https://github.com/hackmdio/codimd/blob/develop/bin/manage_users

**Comment by jackycute** [comment]
Feel free to re-open if you have further question.

**Comment by xdandyx** [comment]
> Hi guys, you can use the manage_users utility tool to reset password, please look at https://github.com/hackmdio/codimd/blob/develop/bin/manage_users
> 
> The command looks will be: `bin/manage_users --reset <user-email>`

Thank you very much !
