### ISSUE TITLE
How to modify env Var?

### ISSUE THREAD

**Issue by Musicminion** [hackmdio/codimd#1760]
![image](https://user-images.githubusercontent.com/84625273/165676561-c61b0f62-17b7-4af5-96a8-22bdd494d776.png)
I have read the [codimd-configuration](https://hackmd.io/s/codimd-configuration), but I still don't know how to modify environment Var?

the `environment.js` file picture is above, should I modify the item directly? Or, how can I modify 'process.env.CMD_XXXXX'?

Thanks for your help!!

**Comment by jackycute** [comment]
Hi @Musicminion,
You will need to export environment vars to your shell according to your env.
Basically using command `CMD_PORT=1234 node app.js` to run the app will bring up `CMD_PORT` env var.
There are much info on internet.
