### ISSUE TITLE
failed to connect to newer postgresql database because node-postgres is too old

### ISSUE THREAD

**Issue by everything411** [hackmdio/codimd#1770]
see https://github.com/brianc/node-postgres/issues/1508

**Comment by jackycute** [comment]
Hi @everything411,
Thanks for reporting, we will take a look.

**Comment by jackycute** [comment]
We only tested PostgreSQL version up to 11.6, what version are you using @everything411 ?

**Comment by everything411** [comment]
@jackycute PostgreSQL 14. I think it will be ok after upgrading pg to 8.8.0

**Comment by jackycute** [comment]
This might fix by PR #1784
