### ISSUE TITLE
losing all files imported

### ISSUE THREAD

**Issue by semiopat** [hackmdio/codimd#1772]
I just see that alle the files I imported in a codimd account from a hegdedoc export files unexpectedly appeared as "404 not found". What is the problem ? I can reimport them but how can I don't lose them again for sure ?

**Comment by jackycute** [comment]
Hi @semiopat,
Unfortunately we are not maintaining hegdedoc, I'm afraid there is not much we can help.
How did you import those files into CodiMD?

**Comment by jackycute** [comment]
Feel free to re-open when you provide more detail logs or error messages.

**Comment by semiopat** [comment]
Hi,Thank you for your answer. The problem is not on HedgeDoc, it occurs on an instance of CodiMD which follows strictly the free code of hackmd. I export all my files from HedgeDoc, import them on CodiMD and it works first, I can edit them. But when I quit the instance and open it back, all the files disappeared. I’d like to switch to codiMD to benefit the last enhancements that are not implemented in HedgeDoc (the spoiler alert, for example)Best regards,SemioPatLe 13 janv. 2023 à 08:07, Max Wu ***@***.***> a écrit :﻿
Hi @semiopat,
Unfortunately we are not maintaining hegdedoc, I'm afraid there is not much we can help.
How did you import those files into CodiMD?

**Comment by jackycute** [comment]
How do you setup your CodiMD? Did you use docker-compose as the doc: https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment?
If so, please ensure you define `volumes` for data persistent or it will lose on restart.

**Comment by semiopat** [comment]
Thanks for that. I don’t setup CodiMD myself but I can follow this information to the concerned people.
