### ISSUE TITLE
Slide background image not working

### ISSUE THREAD

**Issue by dodomorandi** [hackmdio/codimd#1776]
It looks like that using `slide: data-background` for images is not working, the [relative documentation](https://hackmd.io/s/slide-example#Themes) is broken as well (no image is displayed)

**Comment by jackycute** [comment]
Hi @dodomorandi,
Thanks for reporting.
However, I can't reproduce this issue, it seems working at https://hackmd.io/p/slide-example#/11
<img width="1110" alt="截圖 2023-01-13 下午5 33 25" src="https://user-images.githubusercontent.com/2639151/212286707-41363752-4b52-475e-957c-0f7470cd5b01.png">

Could you provide more detail example or screenshots?

**Comment by dodomorandi** [comment]
Hi @jackycute,
the issue is related to background images, not colors. You can see di issue [directly in the documentation page](https://hackmd.io/s/slide-example#Image-Backgrounds).

**Comment by jackycute** [comment]
Still working from my side:
https://hackmd.io/p/slide-example#/12/2

<img width="1440" alt="截圖 2023-01-15 下午10 09 34" src="https://user-images.githubusercontent.com/2639151/212545709-c3ebfc43-8dc7-433a-8614-8da137fd46aa.png">

<img width="1438" alt="截圖 2023-01-15 下午10 09 41" src="https://user-images.githubusercontent.com/2639151/212545703-5d4f0fd3-c1b1-4b01-9d87-ae18039aa56c.png">

<img width="1439" alt="截圖 2023-01-15 下午10 09 51" src="https://user-images.githubusercontent.com/2639151/212545699-d80454b7-4de4-42e4-9253-dc0b18a6834c.png">

**Comment by dodomorandi** [comment]
Thank you @jackycute for your patient!
You are totally right, unfortunately I cannot remember the specific issue I encountered at the time: it could be my fault or it could be related to some the way I was trying to create the slides.

Nevertheless, I am going to close the issue for now. Thank you for the support!
