### ISSUE TITLE
Underscore after parentheses in math mode

### ISSUE THREAD

**Issue by ikabadzhov** [hackmdio/codimd#1800]
If I write in math mode: `(x)_y` or `(x)_{y}` (or anything with an underscore after an opening or closing paranthesis), I get `y` as a subscript (which is as expected), but also the text afterwards appears as italic in the wiritng console (which is certainly not desired and mismatches the parsed output).
On the other hand, writing (in math mode) `x_y` (and so `x_{y}`) simply puts the `y` as subscript, which I expect to be the default behaviour.

I used HackMD on google chrome.

**Comment by ikabadzhov** [comment]
This was due to polluted space of some missing closing dollar sign. I think it should be closed.

**Comment by jackycute** [comment]
Thank for clarify this @ikabadzhov
