### ISSUE TITLE
Cannot Rename Note

### ISSUE THREAD

**Issue by fweth** [hackmdio/codimd#1827]
Hi, when editing a note, I cannot rename it. I change the name, hit enter, nothing happens. In the notes overview, it's no problem to rename them, only in the editor.

**Comment by Tweniee** [comment]
can you share steps to reproduce it, that would be a great help
thnks

**Comment by fweth** [comment]
Pretty much what I wrote. However, I switched to the beta since I reported this issue, so maybe it is already solved in stable as well? Should I step out of beta and check?

**Comment by Tweniee** [comment]
Yes please

**Comment by fweth** [comment]
OK, I quit feature preview, so that I'm back on main. Then I created a new note, the editor appears, the node is called "untitled", I click on the title, I get a cursor and can enter a new title, then I hit enter and the title switches back to "untitled".

**Comment by fweth** [comment]
Aah, I found the problem! I was using the ClearURLs extension, somehow the renaming of a document seems to change the URL and the extension interfered with this. Sorry!
