### ISSUE TITLE
Edit button

### ISSUE THREAD

**Issue by pierreozoux** [hackmdio/codimd#210]
Once #114 is solved, we can create an amazing workflow for [content as code](http://iilab.github.io/contentascode/).

The problem to solve is how to let a non tech user edit an html page that is originally based on MD and saved in git.

With your solution that looks very promising, we could imagine the following workflow:
- I click on an edit button on an html page
- I get redirected to a hackmd server
- the git repo and the file get passed as arg in url
- the server import the git, and show the file to modify
- when the user is done, he clicks on "propose the change"
- it creates a PR on the associated git

It means the UI would be simplified in this process, as the application should understand that this is a specific task, and there is no need  to show the user all the possibilities (like when you checkout in amazon, you don't have menu any more).

In this particular process, there is not much need about the collaboration part also.

About the PR part, it is tricky as it involves specific API (github, gitlab...).

I'm sharing this more like an idea. Probably #114 is more than enough (the edit button would just link to the specified page.).

And I wanted to share with you the project [content as code](http://iilab.github.io/contentascode/) that a lot of people are following.

Thanks for your work and feel free to close if it doesn't fit your project :)

**Comment by jackycute** [comment]
Hi @pierreozoux !
I really like this `content as code` idea, that's also the core value of HackMD.
And it would be wonderful if HackMD can be part of the workflows.

Thanks to your thinking and suggestion, I would love to take this 😄 
But we're focusing on other issue for now, I will add this issue to milestone while the time has come.

**Comment by ccoenen** [comment]
I'm not seeing this in the near future. It is a tempting suggestion, but There's just so many things to work on that It I don't believe this will get picked up in any time soon.
