### ISSUE TITLE
Add DeckTape PDF exporter for slides presentation

### ISSUE THREAD

**Issue by hermanliang** [hackmdio/codimd#241]
Add feature of download slides as PDF file would be very useful for user who want to share their slides as a printable document.
[DeckTape](https://github.com/astefanutti/decktape) is a good candidate to integrate as a PDF exporter, because it supports reveal.js presentation framework.
I've tested the DeckTape on my computer (following the [instruction](https://github.com/astefanutti/decktape#install)) to export PDF from HackMD's [example slides](https://hackmd.io/p/slide-example/), and it works well.

```
./phantomjs decktape.js https://hackmd.io/p/slide-example slide-example.pdf
```

Thanks for considering my request!

**Comment by SISheogorath** [comment]
Currently, the API documentation for decktape is completely missing. We should wait until a usable documentation exists.

**Comment by SISheogorath** [comment]
Seems like their API is still not documented. Closing for now.
