### ISSUE TITLE
Better table support

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#25]
Table always a big issue in markdown.
Not only hard to maintain or collaborate and also ugly.
May think a unique way to solve.
Not a critical issue.

**Comment by qindj** [comment]
Hello Jacky

Thanks for the project, it really helps my team!

Just want to know is there any plan for the table feature?

**Comment by jackycute** [comment]
Hi @qindj !
It's really hard to find any good syntax for table - after all it's not in the standard.
For now we'll keep using GFM table support.

But I'll keep my eye on any other good choices (or if you found one).
Feel free to tell me more about what you think!

**Comment by nielsAD** [comment]
[Pandoc](http://pandoc.org/MANUAL.html#tables) proposes alternatives for table syntax. Personally, I like `multiline_tables` and `grid_tables` as it allows for headerless tables with nested elements. However, collaboratively editing these variants is (probably) still difficult.

**Comment by jackycute** [comment]
I just thought we could add some textcomplete for `|` which is the start of table to let user quickly add table skeleton or remove row & column.

**Comment by foojiawen** [comment]
Maybe pop up a dialog to let users define numbers of rows and columns after clicking this button?
![image](https://user-images.githubusercontent.com/25086023/28245053-4ecd0b82-6a30-11e7-8793-ee6315a2e4b1.png)

**Comment by despens** [comment]
Table syntax is not so bad in markdown, just the editing can be cumbersome.

There is a great Atom package that makes editing markdown tables very comfortable, maybe it could be adapted to work with CodiMD, too.

https://atom.io/packages/markdown-table-editor

![](https://i.github-camo.com/c2a810dc038c3fb1a3d3373fc6ae83c51112997f/68747470733a2f2f6769746875622e636f6d2f7375736973752f6d61726b646f776e2d7461626c652d656469746f722f77696b692f696d616765732f64656d6f2e676966)

**Comment by SISheogorath** [comment]
Would be awesome if someone wants to write a plugin for CodeMirror that uses this: https://github.com/susisu/mte-kernel

I don't think I have the time right now, but maybe you are interested in doing so, @despens

**Comment by WillGoGithub** [comment]
The new table tools has been supported in [version 1.4.0](https://github.com/hackmdio/codimd/releases/tag/1.4.0)
@jackycute This issue could be closed if the feature meet the requirement. 👍

**Comment by jackycute** [comment]
> The new table tools has been supported in [version 1.4.0](https://github.com/hackmdio/codimd/releases/tag/1.4.0)
> @jackycute This issue could be closed if the feature meet the requirement. 👍

That's right, thanks for heads up!
