### ISSUE TITLE
[Suggestion] New emojis

### ISSUE THREAD

**Issue by brainscript** [hackmdio/codimd#262]
Hello everybody,

I'm a **huge** fan of HackMD, but there's one thing that always bothers me:

:hankey: The emojis
---
Or, to be more clear: the **"default emojis"**.
### What's bad about them?
- Their license is unclear.
- Their glossy look is not modern.
- Many developers don't like them.
- Some of them are offending, like this one: :nerd_face:

What about [EmojiOne][website]?
---
[EmojiOne][website] is an alternative to the "default" emoji pack and is independent from any phone manufacturer or operating system. I'd love to see them in HackMD! :heart_eyes_cat:

![Screenshot][screenshot]

### Why are the [EmojiOne][website] emojis better?
- They look fantastic!
- They're [free][licensing] and [open source][source].
- They're very popular among geeks (especially in the Android "modding" community).
- They make it very easy for developers to implement them.
- They're fluffy.

---

You could argue that users are used to the "default" ones and don't want try something new.
But, I suppose that most HackMD users are geeks/nerds and **we don't look like this**: :nerd_face:
Most of us are always happy to **try something new**. (That's how we stumbled upon HackMD.)

---

Please :+1: this issue if you like my suggestion and let me hear your feedback! :smile_cat:

[screenshot]: https://cloud.githubusercontent.com/assets/8706734/20684378/f0dca030-b5af-11e6-803e-0d9dca27d848.png "Screenshot"
[website]: http://emojione.com/ "Website"
[licensing]: http://emojione.com/ "Licensing"
[source]: https://github.com/Ranks/emojione "Source"

**Comment by jackycute** [comment]
Hi @brainscript 
Thanks for your suggestion!

How about Twemoji? https://github.com/twitter/twemoji

**Comment by jackycute** [comment]
I just found that GitHub use flat style fallback for OS which not support unicode emoji (like Windows).

**Comment by brainscript** [comment]
@jackycute Both emoji packs look awesome.
I honestly can't decide what to use ... :confused:
Which one do you prefer?

**Comment by jackycute** [comment]
I personally prefer Twemoji.
Anyone who cares about emoji please vote.

**Comment by SISheogorath** [comment]
@jackycute I can totally understand why you prefer Twemoji. They are flat and look nice. The only problem I can see is that they are not support codes like `:smile:` which are very useful as not everyone is using a software keyboard which easily enters the unicodes. (May I'm wrong but I couldn't find the parser function for it)

So I think EmojiOne is the better choice in case of UX 😢

**Comment by brainscript** [comment]
@jackycute @SISheogorath Let's make a simple voting using GitHub reactions.
Pick your favorite pack from the table below and react using the voting emoji in the left column.

:arrow_down: | Emoji pack
---|---
:tada: | EmojiOne
:heart: | Twemoji
:confused: | The default

To do this, click on the **+ :smile:** on this comment.
![Tutorial](https://cloud.githubusercontent.com/assets/8706734/21717246/209f5712-d410-11e6-975c-74b5423a8e73.png)

If you want to request another emoji pack comment and **@mention** me.

**Comment by jackycute** [comment]
Maybe we can let user choose their emoji set via meta.
What do you think @brainscript ?

**Comment by jackycute** [comment]
Or if user signin and note not having default settings will load user preferences.

**Comment by brainscript** [comment]
@jackycute Good idea!
```yaml
---
emojis: default
# OR
emojis: twemoji
# OR
emojis: emojiOne
---
```

**Comment by SISheogorath** [comment]
Also a hint for the implementation: 

https://github.com/hackmdio/hackmd/blob/d96385eafdc8e9c408088a3f95a60c9a0193ef67/public/js/extra.js#L88-L102

Now there is only the need to add the emoji JS and CSS files in the right places and it should work fine. Have a look at #243

**Comment by ccoenen** [comment]
Before taking any decision, please make sure the chosen one works on all major platforms. Even Github gets this wrong, this is what happens to github's reaction emoji on windows:

![grafik](https://user-images.githubusercontent.com/124909/31296117-7b30ea80-aae1-11e7-93ba-6fda55ab14ae.png)

(note the missing 'heart' emoji)

**Comment by ccoenen** [comment]
EmojiOne is off the list, simply because they are _not_ open source. They used to be. They are not any longer.
https://www.emojione.com/faq

**Comment by yusf** [comment]
What about EmojiTwo? https://github.com/EmojiTwo/emojitwo

**Comment by Yukaii** [comment]
done with #1261
