### ISSUE TITLE
Export to pdf

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#33]
Support export to pdf is important.
Previous research the result is not very satisfied.
But we found gitprint and it's opensource, might try that again.

https://github.com/adamburmister/gitprint.com
https://github.com/alanshaw/markdown-pdf

**Comment by amigrave** [comment]
Why not using [wkhtml2pdf](http://wkhtmltopdf.org/) on the generated html ?

**Comment by jackycute** [comment]
I don't know wkhtml2pdf before, looks good and will give it a try.
But see from the https://github.com/wkhtmltopdf/wkhtmltopdf/issues
It has lots of issue not solved.

Anyway, thanks for help!

**Comment by jackycute** [comment]
Use markdown-pdf right now, note bad.

**Comment by jvoisin** [comment]
What about pandoc (#48) ;)

**Comment by amigrave** [comment]
Pandoc will export to pdf using it's renderer which is not aware of all the extra components supported by hackmd (eg: mathjax, diagram, google emojis, ... )

Converting the generated html to pdf is the best bet if we want to support all the javascript exotic features. and as a bonus, it will give you the same look/styles that you actually see in hackmd versus a custom renderer which would render with different styles.

**Comment by vincfleurette** [comment]
Could you add a way to integrate the summary in the pdf export ?

**Comment by jackycute** [comment]
Hi @vincfleurette,
Could you tell more about "the summary" ?

**Comment by amlwwalker** [comment]
What could be nice is adding a PDF export button for something like https://docraptor.com/ for those who are happy to pay for the conversion. PDF generation is always tedious from things like markdown, but as HTML export is already implemented, it could be a simple solution? Example code on their website on how to `POST` HTML to docraptor, and get back a PDF, which you then offer to the user via download... Just a thought...

**Comment by jackycute** [comment]
@amlwwalker I found out how dillinger did their PDF export yesterday, we might be able to do this too.
https://github.com/joemccann/dillinger/blob/b28fd80445ac02739548d99d79ea6490ac4c7d2d/plugins/core/server.js#L109

**Comment by ChihChengLiang** [comment]
Dear maintainers,

Thanks for this awesome project. I was googling for how to export slides to pdf and end up finding this discussion here. Would like a feature that can do this, but after went through some issue discussion here I understand lots of works are still going on. For anyone want to export slides to pdf, here I offer a workaround for you.

1. Modify the url by appending `?print-pdf` after it. For example, change from `https://hackmd.io/p/slide-example#/` to `https://hackmd.io/p/slide-example?print-pdf`. Note that `?print-pdf` must be put before `#/`

2. Select `print` in the right-click menu. If you only intend to send it as pdf, check the `background graphics` option and you are in business. 

<img width="245" alt="screen shot 2016-12-16 at 11 16 02 am" src="https://cloud.githubusercontent.com/assets/3391420/21250546/167aac4a-c381-11e6-9f35-944c7a802603.png">

3. If you want to print it and find a dark background too ink costly, you might want to uncheck the `background graphics` and use a black font color. Open your browser developer console and enter the following command `$("h1, h2, p").css("color", "black")`, then you are good to print. For example, in Chrome browser and Mac OS you press `opt + cmd +j` to open the developer console and paste the magic spell.

<img width="642" alt="screen shot 2016-12-16 at 11 25 27 am" src="https://cloud.githubusercontent.com/assets/3391420/21250737/6269b0b4-c382-11e6-8676-0f5ff50681f0.png">

**Comment by tigercosmos** [comment]
Shall we work on this to land the function to export PDF?

**Comment by SISheogorath** [comment]
@tigercosmos  Pull Requests are welcome :)

In general, we have currently a way to export the documents as PDF on self-hosted instances.  

Exporting the Slides as PDF would be another nice feature. If you want to implement that feel free to do so. We would love it!

**Comment by komikoni** [comment]
The "?Print-pdf" feature of the slide no longer works properly.
Now, only the first page can be printed, and the second and subsequent pages can not be printed.

**Comment by jackycute** [comment]
@komikoni Sorry about that. It's an issue of `HackMD.io`, CE can use print-pdf properly.
And we've moved all our EE and HackMD.io issues here:
https://github.com/hackmdio/hackmd-io-issues/issues

**Comment by fabioperrella** [comment]
I've just noticed the export to PDF works much better in Chrome compared to Firefox!

I'm using Ubuntu 16.04
