### ISSUE TITLE
Moving detail description to docs

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#334]
We have too long `README.md` for now (it's growing!).
So maybe we could move some of them to `docs/` to GitHub wiki.

**Comment by ccoenen** [comment]
You're new to this project? perfect! You'll look at HackMD's docs with a fresh pair of eyes. This a nice place to start! Not all contributions to a project are related to code!

**Comment by Yukaii** [comment]
We have a new `README.md` and [online documentation](http://hackmd.io/c/codimd-documentation/) now 🍾
