### ISSUE TITLE
Yank to clipboard in vim mode

### ISSUE THREAD

**Issue by qiuwch** [hackmdio/codimd#351]
Is it possible to make the hackmd yank to the system clipboard in the vim mode? This will make transferring text between notes much easier.

**Comment by aflashyrhetoric** [comment]
It is possible to highlight with visual mode (ie: `v$`) and then do the usual `CMD+C`. It should highlight to clipboard.

**Comment by Yukaii** [comment]
I just found that CodeMirror(which is our editor component) has already exposed `defineRegister` API for custom register. Maybe we can find a way to implement using this API.

Refs:

* https://github.com/codemirror/CodeMirror/issues/3293
* https://github.com/codemirror/CodeMirror/pull/3315

**Comment by jackycute** [comment]
Hmm this still seems like a codemirror's issue if the yank to clipboard is the core feature of vim.
Please take a look at https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js before custom any key bindings.
And I found some yank related commits in CodeMirror repo:
https://github.com/codemirror/CodeMirror/search?q=yank&type=Commits&utf8=%E2%9C%93

**Comment by Yukaii** [comment]
CodeMirror in package.json should also be upgraded. Reopen
