### ISSUE TITLE
Inline popover or shortcut

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#4]
As people ask for, to have a popover toolbar(bold, italic...) on the selection text or shortcut keys for markdown will be more friendly to beginners.

**Comment by jackycute** [comment]
Added change mode shortcut keys in 9d71adc05c93577d64f47180e3429bf3cd9a7be0
Added shortcut keys for symbol surround text in 591134007ca70a542239badc61073f0be515abf4

**Comment by Yukaii** [comment]
Related to #176

**Comment by SISheogorath** [comment]
We have a editor toolbar which is able to do this with #846 now. It should provide the needed flexibility.
