### ISSUE TITLE
feature request: label important revisions

### ISSUE THREAD

**Issue by mistguy** [hackmdio/codimd#443]
Since I sometimes need my old version of documents, it would be really convenient if important revisions can be labeled and compared.

**Comment by ccoenen** [comment]
I'd propose also hooking into <kbd>Ctrl</kbd>+<kbd>S</kbd> for that.

**Comment by Yukaii** [comment]
Labeled/named revision is implemented on [HackMD.io](https://hackmd.io) now. Read the tutorial for more details: https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-save

**Comment by mistguy** [comment]
That's exactly what I want. Thanks.
