### ISSUE TITLE
瀏覽數是可以刷的 / View counts can be flooded

### ISSUE THREAD

**Issue by lifehome** [hackmdio/codimd#466]
Step to reproduce:
1) 隨便找塊pad
2) 瘋狂 F5
3) ???
4) 很多瀏覽數啦～

---

Step to reproduce:
1) Find a note
2) Press F5 crazily
3) ???
4) You got lots of view counts

**Comment by jackycute** [comment]
嗨 @lifehome 
這是已知的問題

但是為了不讓使用者隨意刷瀏覽數，就要額外使用 redis 之類的 MQ，感覺 CP 值有點低
我想，如果使用者想刷就刷吧...，反正目前也沒有排名，只是個數字

**Comment by ccoenen** [comment]
I don't think this is a priority at the moment.
