### ISSUE TITLE
Use pandoc

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#48]
Actually pandoc is pretty good.
It support so many export format and conversions (even export to pdf).
And it can support asciidoc as a cool guy suggested.
http://pandoc.org/

**Comment by reagle** [comment]
Just curious, hackmd does **not** use pandoc, but plans to one day, but doesn't appear as a milestone anymore?

**Comment by SISheogorath** [comment]
Yes, that's correct.

We currently do **not** use pandoc. We use **markdown-it** as renderer right now and so far, don't want to change this, as we put a lot of work into extensions for it.

And that brings us to the reason why pandoc is currently not on the agenda: We build various custom embedding for markdown-it and we would need to port them to pandoc if we would really like to use them. That again is probably more work than we can currently take and also would double all future work. So, so far, markdown-it it is.

**Comment by reagle** [comment]
I see, thank you.

**Comment by Yukaii** [comment]
We can open an api endpoint for generating pandoc export ouptut, like what stackedit did.

- https://github.com/benweet/stackedit/blob/master/server/pandoc.js: Stackedit open an endpoint for pandoc export, whichs use [`pdc`](https://github.com/pvorb/node-pdc) nodejs module.
- https://github.com/mrded/pandoc-as-a-service/blob/master/server.js: For higher demand request, open a standalone server to host pdc service

**Comment by ngirard** [comment]
Hey folks,

I'm contemplating writing a command-line converter from CodiMD's markdown flavor to Pandoc's.
I'd write it either in Python or Rust.
Could anyone point me to a summary of CodiMD's idiosyncraties w.r.t Pandoc ?
Which part of this project would be the trickiest, in your opinion ?
Is there anyone who'd be willing to work with me on this ?
Thanks !
