### ISSUE TITLE
Option to swap the preview pane

### ISSUE THREAD

**Issue by jeffhung** [hackmdio/codimd#487]
It would be great if there is an option item to toggle where the preview pane is - at left or at right.

Because right-handed and left-handed people are used to different kinds of _directions_. For example, as a right-handed person when I am working with a reference book, I tend to put the book at the left-hand-side of my computer. This is the same direction as if I am writing on paper using my right hand while have the reference book at left hand side.

**Comment by pirate** [comment]
Whoever does this, you can snag my 2 line change from here as a starting point: https://github.com/hackmdio/hackmd/pull/665

That code will have to be changed to flip the sides according to the user's preference.

**Comment by ccoenen** [comment]
This has been open for over half a year. I find this to be more of an edge case, so I'm making the decision to not add this for now. This is not a shutdown forever, and if someone were to write it, it would probably get merged.

Still: I'm closing it not to get anyone's hopes up.

**Comment by ccoenen** [comment]
It should also be noted that this adds some complexity to the code, so even if somebody writes the changes, we should take a hard look at the benefit it provides.

Furthermore, I don't follow the lefty/righty argument; to me this is more about reading direction or temporal or workflow arrangement: FIRST I edit (left) THEN I read or recheck the generated document (right).

**Comment by pirate** [comment]
` FIRST I edit (left) THEN I read or recheck`

This is what I was proposing, it seems very strange to me to have "read" on the left, and "edit" on the right as it is right now.

**Comment by ccoenen** [comment]
Yes, the button should be swapped to match the layout of the editor/preview.

**Comment by SISheogorath** [comment]
As I mentioned in the chat the reason is actually easier: It follows the flow of CodiMD itself right now. When there is text inside a node, it shows the VIEW by default. That again means left which is from this perspective logical.
But we can switch it. @pirate you already provided a patch for that but didn't make it to provide it as an acceptable contribution, which is sad.
