### ISSUE TITLE
tags會被算入ToC的第3個層級中 / tags is included in the third level of TOC

### ISSUE THREAD

**Issue by tRexCheng** [hackmdio/codimd#502]
當我的文件title只有2個層級的時候，如果文件中有tags時，tags會被當成第3個層級而出現在ToC中，這個好像有點奇怪。下面的網址是一個範例
https://hackmd.io/s/SJNuMp_N-#

---

When the titles in the doc only have two levels and the doc contains tags, the tags will be considered as third level and showing in the TOC. This is kind of strange, below is an example
https://hackmd.io/s/SJNuMp_N-#

**Comment by ssoda** [comment]
@tRexCheng 前陣子有碰過類似的問題，不過現在應該是解決了。
![tag_issue](https://user-images.githubusercontent.com/30249453/28603453-be421994-71f6-11e7-8fe2-36e43a245d75.PNG)

**Comment by SISheogorath** [comment]
For the English speakers:

> When the document only has 2 subtitles and you add tags using `###### tags: ` to add tags to the document, they show up in the markdown rendered `[TOC]`.
