### ISSUE TITLE
Guest accessing a restricted note should be redirected to sign-in and then back to note

### ISSUE THREAD

**Issue by lgpawel** [hackmdio/codimd#526]
I signed in, created a note, set its status to Limited, and then loaded the page in private mode, ie. as a guest user. The server returns HTTP 403 and loads a page saying "403 Forbidden oh no." Same for a Protected or Private note.

I think that for smoother UX, in such situation the guest should be shown a sign-in page (perhaps with an explanation) and, after a successful authorization, get redirected back to the note.

**Comment by dsprenkels** [comment]
This issue has been fixed in https://github.com/hackmdio/codimd/pull/785 and should be safe to close.
