### ISSUE TITLE
HackMD Community Announcement

### ISSUE THREAD

**Issue by jackycute** [hackmdio/codimd#579]
Dear Markdown hackers,

We are back with great news! Today we are introducing **HackMD Enterprise Edition (EE)**, a new HackMD service with features specifically designed for knowledge sharing and collaboration. We also promise ongoing free hosting of **HackMD.io** and commit to continuous support of the **HackMD Community Edition (CE)**. But most important of all, we want to thank you, from deep in our hearts.

Please read more here: https://hackmd.io/c/community-news/https%3A%2F%2Fhackmd.io%2Fs%2FBk-zpEC9-

**Comment by pierreozoux** [comment]
Thanks for the news! We are also excited about it!
We have one question, will the enterprise version based on the community edition, or will it be a fork?

So the question is a bit like, will you continue to support base features, or it will be just a community effort from now on?

Thanks a lot for the feedback!

**Comment by RoyiAvital** [comment]
Hello,

How come HackMD site shows version 1.0.0 while the GitHub repository is still on 0.5.1?
Moreover, there is no link from the site to the GitHub repository which I think it used to have.

**Comment by jackycute** [comment]
Sorry for late reply @pierreozoux .
Let me also reply @RoyiAvital in this comment.

The HackMD.io now is running a customize version of HackMD which included enterprise features.
So the release notes will on our own roadmap and version name (x.x.x-ee).

As we've mentioned in the announcement (see the link in top post).
This repo is the **Community Edition (CE)** of HackMD, and now are moderated by @SISheogorath and @ccoenen who have actively helped us and devoted to this project a lot in the past few months.
The Community Edition will now have its own roadmap & milestone and will be maintained by community activists (Hello guys :tada:).
So that's why this repo's latest release still 0.5.1 for now, it needs more works to have the next one, and I believe it will soon happen (even sooner if you could help!).

According to the license we going to take (AGPL 3.0). We will not directly merge/integrate the community contribution to CE going forward. But this doesn't mean this repo will no longer maintained by us, we'll keep an eye on and might land some fixes when we able to do it.
Then, we've intended to remove the GitHub repo link from our site to prevent confusing user about which HackMD edition they're using.

**Comment by pierreozoux** [comment]
@jackycute Thanks for the clarification.

IMHO, it is not a Community Edition (CE), The term CE is usually used in the open core model. As I see now, and from what I understand, you want to release a closed source product. So technically your product is a fork (or this open source project is a fork).

To help people identify better which is which and what to expect, and avoid frustration, I'd recommend renaming this project to something else, and separate the 2 identities clearly and tell people what it is: a fork, and not a CE.

I hope it helps.

**Comment by rriemann** [comment]
I also think it is better to be clear about the fact that the business model you choose is a closed-source version based on a fork.

I think it is confusing that both projects carry the same name.

**Comment by jackycute** [comment]
@pierreozoux @rriemann  Thanks for reply, I've been thinking about this for a while.
So actually we do share most core parts in CE and EE edition, like: editor, OT, markdown parser.

To avoiding confusion, I would first make the title to show about this is the CE version and also change the link to auto build for CE on heroku.

Hope this helps too.

**Comment by pierreozoux** [comment]
@jackycute `do share most core parts in CE and EE edition`

This is the question!

If you build EE on top of CE, then it is an open core business model, and the names EE and CE are correct!

If you modify the code of the core parts in the EE version, and do not reshare to CE, then this is a fork. 

Hope it is clearer :)

So is it a fork or an open core model?
Do you modify the CE version in your EE version without resharing the changes?

**Comment by SISheogorath** [comment]
As there is a license change to AGPL and no CLA there is no way to use the CE changes in EE. -> It's not an open core model.

HackMD EE as well as HackMD.io **are forks**. They will move into different directions in future. Right now most of the code is shared. Of course over time there will be changes that make the version incompatible. Then it's probably time to rename it. Right now I would say that it's close enough to stay under the original name.

Also I like the name HackMD and finding a similar good one will be hard. I would say there is enough to do, that is more important than finding a new name.

**Comment by patcon** [comment]
I love you all, but this is a disappointing turn of events. I believe the growth you saw was the result of persons like myself sharing news of your tool in good faith. I have the sense that the spirit of this social contract is damaged.

**Comment by pierreozoux** [comment]
@SISheogorath cool you say it is a fork, it is all about communication, and I'm glad you said it.
Then about changing the name, and having other priorities, I totally agree, and I lack time myself, so I'll not complain. I'm aware myself, for others, they'll have to find this issue to make an informed choice on using HackMD or not)

Just that it is all about managing expectations.
And when people see this EE and CE, they think about GitLab, and here, it is something else.

About being open or not, this entirely your decisions, and I join @patcon to say that you also deserve to be paid. Then the best way to do it, I have no idea myself. We (@unteem and me) try to make a living from https://indie.host since 4 years, and we have 1/2 salary so far, so I'm not sure I'm the most well placed to give advices on monetizing FLOSS.

But I wanted to share this talk that I saw sunday:
https://fosdem.org/2018/schedule/event/nextcloud/
About open source business model, I find it really good, and I hope it gives some informations, and help!

Have a nice day everybody, and the best of luck for making a living for whatever software you develop or host ;)

**Comment by ccoenen** [comment]
I think this issue can be closed now. Feel free to add your comments, or reopen, or create entirely new issues! This is not meant to shut down discussion, just to keep a sane level of issues in the issue tracker :-)
