### ISSUE TITLE
Provide documentation for auth providers

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#583]
To prevent upcoming issues like #582 and #259 we should provide a detailed documentation how to set up our various auth providers.

Further issues related to auth:
https://github.com/hackmdio/hackmd/issues?q=label%3A%22auth+provider%22+is%3Aclosed

Feel free to do your best. [`./docs/guides`](https://github.com/hackmdio/hackmd/tree/master/docs/guides) is waiting for your PRs 😄 

If you have question or similar don't hesitate to contact us.

We are only one click away: 
[![Join the chat at https://gitter.im/hackmdio/hackmd][gitter-image]][gitter-url]

[gitter-image]: https://badges.gitter.im/Join%20Chat.svg
[gitter-url]: https://gitter.im/hackmdio/hackmd

**Comment by devonJS** [comment]
@SISheogorath hello! could i help out with this one?

**Comment by SISheogorath** [comment]
Sure @devonJS! Help is very welcome! ❤️

If you need any help, feel free to reach out to me here or on [gitter](https://gitter.im/hackmdio/hackmd).

**Comment by devonJS** [comment]
@SISheogorath added a small guide at #601, let me know if you'd like any additional documentation.  Your README.md is already pretty good haha

**Comment by SISheogorath** [comment]
Current state:

- [x] GitHub
- [x] Twitter
- [x] SAML
- [ ] Facebook
- [ ] GitLab (.com as ell as self-hosted)
- [ ] Mattermost (@DoubleMalt could you do this?)
- [ ] Dropbox
- [ ] Google


How to do this? -> 

https://github.com/hackmdio/hackmd/pull/601#issuecomment-340235061
https://github.com/hackmdio/hackmd/blob/2db2ff484fb0911ea699c7fc59b8b1ad868ca992/docs/guides/auth.md

I would love to seem some more helping hands :) Would be awesome to have this in the new release!
