### ISSUE TITLE
Feature request: Embedding Maps

### ISSUE THREAD

**Issue by dbrgn** [hackmdio/codimd#592]
It would be great if coordinates could be embedded and displayed as a map :)

**Comment by ccoenen** [comment]
you can add any HTML already, including iframes from - for example - google maps.

Example: https://hackmd.io/KwIwTAZhBsbQtMAhgRgMzwCwQBwXgJwDsaADPBGGgdKZutpkA===#

Can you elaborate what your feature request would add beyond this embedding?

**Comment by SISheogorath** [comment]
If you want to implement it, it shouldn't be too complicated.

Have a look at the file `./public/js/extra.js` and this PR:

https://github.com/hackmdio/hackmd/commit/3424cdd7713421d3fc88a501c1cd7606c943a05e

Pull Requests are welcome ❤️

**Comment by dbrgn** [comment]
> you can add any HTML already, including iframes from - for example - google maps or open street map.

Ah, I somehow wasn't aware of that. Nice :)

> If you want to implement it, it shouldn't be too complicated.

Thanks for the pointers, I'll check it out! :) Maybe I'll create a PR.

**Comment by MarcelWaldvogel** [comment]
The 2.0.0 release notes say that we should give feedback here. I am following this order, but would be happy to open a new issue instead:

* Be able to give a zoom factor also when naming the location (potential syntax: `Bundesplatz, Bern@17`).
* Default zoom factor for named entities should be based on the size of the object (e.g., for an address, the house; for a city, the city boundaries)
* Be able to specify (and potentially name) multiple locations in one map. The map might autoscale to show them all. (This might use a YaML-like syntax, as proposed in #1289.)
