### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#611]
We currently only do static code analysis on our codebase. This prevents broken syntaxes but doesn't prevent logical errors.

And while static-typed languages provide a little bit of security for not breaking things without a compiler error, in JS that's totally possible. To prevent this we need runtime tests. Unit tests using a framework like [mocha](http://mochajs.org/) or [jasmine](https://jasmine.github.io/setup/nodejs.html) would be awesome! It needs a lot of work but it would help to stabilize the code base a lot.

It's an annoying task, I know and for most people, no fun. But I'm not the JS test guru I should be for this task, so I would really appreciate help with this. The basic setup, the concept where to place the tests (in a separate directory or along with the files but with a `.test.js` file ending). How to make these tests not breaking our `webpack` setup and so on?

As you know since #579 we as a community develop HackMD CE now and we have to decide where we want to go. Right now, I try to stabilize the code base and fix existing bugs instead of providing more and more new features. With tests, we can go further and make it easier to verify new features and prevent them from breaking existing ones.

I love working on HackMD as well as I enjoy having this community! So let's work on it as a community and improve HackMD CE!

Pull Request, concepts, examples, and ideas are very welcome! :heart: 

Also feel free to meet me in our Gitter-Space: [![Join the chat at https://gitter.im/hackmdio/hackmd][gitter-image]][gitter-url]

Newer duplicate of #22 

[gitter-image]: https://badges.gitter.im/Join%20Chat.svg
[gitter-url]: https://gitter.im/hackmdio/hackmd?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by ccoenen** [comment]
let's continue here, no need to keep two versions of this ticket open.

**Comment by SISheogorath** [comment]
Asked Cloudron to add their tests to our repository:

https://git.cloudron.io/cloudron/codimd-app/issues/2
