### ISSUE TITLE
When write to the last line, the words will covered by the bottom bar.

### ISSUE THREAD

**Issue by ericma15** [hackmdio/codimd#617]
just like this ![pic](http://chuantu.biz/t6/124/1509714331x3689931740.png)

**Comment by ccoenen** [comment]
I can confirm, this happens to me as well all the time.

**Comment by maxcaluva** [comment]
Not happening to me, I can scroll past the last line, any specific steps to reproduce this?

**Comment by ericma15** [comment]
In fact, I still can't find a way to reproduce this bug 100%.  But when I use hackmd, sometimes it happens. I think it happens because of the sync scroll.

**Comment by ccoenen** [comment]
I had this happen to me yesterday on a linux laptop. I can't exactly pinpoint it, yet. But it happens (version running is 0.5.1, though, so it might have gotten fixed without me noticing)

**Comment by ccoenen** [comment]
Things I remember about the situation: I worked on the document alone, There were lines following the one i edited (i.e. i was editing somewhere in the middle of the document). Typing did not fix this. The browser window was maximised (regular full screen, not that fancy chromeless full screen). I was using firefox on linux.

**Comment by ericma15** [comment]
It happens when I edit at the end of the document. At that time, I use chrome on linux. When I use windows, it doesn't happen.

**Comment by ccoenen** [comment]
I just had this happen on windows as well O_o
I do have to admit that I am still running 0.5.2, and not off of master.
![bottom-bar-bug](https://user-images.githubusercontent.com/124909/33291628-c0a6284c-d3c6-11e7-94e7-cd491d554bf0.gif)

**Comment by SISheogorath** [comment]
Have you checked the CSS of this error?

**Comment by ccoenen** [comment]
Not yet, is there anything in particular that I should look for?

**Comment by SISheogorath** [comment]
Check the class that makes the editor field floating longer and check for possible fields that are added above. Can you reproduce the issues?

**Comment by YadominJinta** [comment]
Still meet this bug in 2020. Is there a solution?

**Comment by jackycute** [comment]
Fixed by https://github.com/hackmdio/codimd/pull/1531
