### ISSUE TITLE
Change spellcheck language

### ISSUE THREAD

**Issue by thmspl** [hackmdio/codimd#647]
Is it possible to change the language of the spellchecker from english to german?

**Comment by SISheogorath** [comment]
Right now the English spell-check is more or less hard-coded. 

https://github.com/hackmdio/hackmd/tree/master/public/vendor/codemirror-spell-checker

But I would love to see someone helping to make this configurable :)

**Comment by thmspl** [comment]
Thank you for the answer. I've tried it by my self and it works!

Here you can see how I've did it -> https://github.com/thmspl/hackmd/commit/ceb841869bff4e3417c3f4d17a765cef644a1adc

I will try to make it configurable during the next days and you can implement it into hackmd if you want.

**Comment by SISheogorath** [comment]
Very cool! I would love to see this coming into HackMD 👍 

I'll reopen this issue until a pull request is landed if you don't mind ^^

**Comment by ccoenen** [comment]
there's a `lang` attribute for the metadata section, this could be leveraged as well, in my opinion:

https://hackmd.io/s/yaml-metadata#lang

**Comment by banderlog** [comment]
#150 is for chrome only

IMHO better to fork `codemirror-spell-checker` and remove hardcoded `en_US `dict to `lang` from yaml header. Currently, repo has 2 hardcoded download links to `en_US.aff` and `en_US.dic` plus 2 hardcoded `Typo()` objects creation.

This is a codeblock where all 4 mentions of hardcoded `en_US` dictionary are :
https://github.com/sparksuite/codemirror-spell-checker/blob/76b6450a6395c86524dee19de4bf478336df4bbf/src/js/spell-checker.js#L31-L70

By the way, the `codemirror-spell-checker` is nothing but a wrapper, which allows dict downloading, around a  ["typo-js" lib](https://github.com/cfinke/Typo.js/) where you need to setup local dir_path to dicts. 
According to [README](https://github.com/cfinke/Typo.js/blob/master/typo/README.md), `Typo()` objects support any kind of languages and Hunspell dictionaries, 

Thus, maybe it is better to just use `typo-js` directly.
