### ISSUE TITLE
Suggestion: Collapsible item set

### ISSUE THREAD

**Issue by Nebukadneza** [hackmdio/codimd#711]
Hi,

I have an idea for a feature that i think would be cool: Collapsible items:
Often, Documents are mainly structured with list-likes, be it lists, enumerations, or the like. These can get a bit long, and users may want to only see one portion of the information at a time. It would be great if there was a element / syntactic element to define: The tree below this point is collapsible at this point. Something like:

```
* Todo
  * [ ] Foo
  * [ ] Bar
* Things to note when doing
  * This
  * That
  *> Detailed $thing
    * …
    * …
      * …
      * …
```
Where `*>` (or anything else more markup-y) denotes that the sub-tree under this item should be collapsible, with a control-element that’s attached to the so-denoted item.

I’d be interested to hear your thoughts on this idea …
Best,
-Dario

**Comment by ccoenen** [comment]
As a workaround: you get this from html with the `<details>` and `<summary>` tags. It even works on Github:

<details>
<summary>click here</summary>
made you look.

this section is generated by this code:
```html
<details>
<summary>click here</summary>
made you look.

(code example here, but let's not get recursive!)
</details>
```
</details>

If we do introduce something like that, it must not interfere with regular Markdown, in my opinion. This is not possible with `*>`:

*> test 1
  * test 1.1
*> test 2
  * test 2.1

So, at least we'd have to find another kind of syntax for this.

**Comment by Nebukadneza** [comment]
Hi,

thank you for the workaround, that’s actually quite nice already :+1: .

As for the syntax — if this feature is of interest to others at all: sorry for the bad proposal. I don’t have a good intuition for MD yet, so I didn’t intend to propose this syntax, but give a small, simple example to make my intention clearer.

As such: Yes, > is already overloaded for HTML-tags as well as for quoting, it’s probably unwise to overload it further. On the other hand, it’d be great and markdown~ish if the character chosen would roughly represent what’s happening. All the closing-braces are already used unfortunately.

If anyone has a good idea, I’d be glad to hear it ^_^.
Best & Thanks,
-Dario

**Comment by SISheogorath** [comment]
I think, we should add a document into `public/docs` where we provide all kind of markdown hack examples.

As the name HackMD may indicates, it's also possible to get nice solutions without having everything build it. So probably it's time to provide and collect some nice workarounds and creative ways to do things.

**Comment by ccoenen** [comment]
I'm closing this in favor of @SISheogorath's suggestion (adding this to docs)
