### ISSUE TITLE
Slides options for font size scaling, left alignment

### ISSUE THREAD

**Issue by Peter554** [hackmdio/codimd#806]
Is there a good way to globally align text in slides to left in the YAML? And to change the default font size (it seems rather big to me?)? Or if not in the YAML maybe there is another way to easily achieve this? If not perhaps this feature should be added?

**Comment by SISheogorath** [comment]
Well, I wouldn't call it easy, but when it's urgent it's a possible way to go:

```HTML
<style>
    .present h1 {
        font-size: 10px;
    }
</style>
```

Simply embed a style into your presentation. A long term solution would need development. Feel free to contribute one :) Pull Requests are welcome!

**Comment by Peter554** [comment]
Stale - closing
