### ISSUE TITLE
Wrong order of Headers in TOC/Menu if one level missing

### ISSUE THREAD

**Issue by eapo** [hackmdio/codimd#816]
## [Example - HackMD](https://hackmd.io/WXQ5hzhXTLOoshQiWQ1uJA)
Wrong order of Headers in TOC/Menu if one level missing _(The first H2 in this example)_

Thank you for this amazing work!

**Comment by ccoenen** [comment]
I've copied it over to [hackmd-ce](https://hackmd-ce.herokuapp.com/N8pIhisqTVi_9m7-Tsah9w#) this applies to both hackMD _and_ CE. I've taken the liberty of adding number in front of everything,

The toc in the menu is also broken.

![grafik](https://user-images.githubusercontent.com/124909/39843511-ad08ee6e-53eb-11e8-96bc-d6e1d4a5facb.png)
