### ISSUE TITLE
Center text

### ISSUE THREAD

**Issue by GZhang2** [hackmdio/codimd#851]
It would be great to be able to use ->Centered Text<- markdown syntax.

**Comment by SISheogorath** [comment]
What markdown standard is that? And who to put other alignments? Does this only effect one paragraph or does it spread across them?

**Comment by ccoenen** [comment]
I haven't seen this syntax either, I only know of centering in tables (`:--:`).

As a workaround you can use a html tag with inline style (example document: https://hackmd-ce.herokuapp.com/X9Eo5wuSQIme24U3YKCu2A )

```
<p style="text-align: center">def 456</p>
```

**Comment by ccoenen** [comment]
I would really like to avoid putting yet another markdown derivate out there. The suggestion would be somewhat useful, but there's a workaround and I know of no other implementation that has this feature.
