### ISSUE TITLE
Collect useful CodiMD hacks and patterns in docs

### ISSUE THREAD

**Issue by ccoenen** [hackmdio/codimd#869]
As suggested in https://github.com/hackmdio/codimd/issues/711#issuecomment-361921222 we should collect useful bits and pieces in `public/docs`. I tagged this as `good first issue`, because this does not require any knowledge of the codebase or JavaScript. If you're familiar with markdown and/or html and/or css, you'll be able to contribute to this issue.

Hacks that could be collected into a document:

* [ ] details and summary tags for collapsible items https://github.com/hackmdio/codimd/issues/711#issuecomment-361418762

(list to be extended)

**Comment by pamnanaimanish169** [comment]
Hi @SISheogorath,

Facing an issue while opening the link

<img width="856" alt="image" src="https://user-images.githubusercontent.com/21191012/230867089-259b47e4-81c9-4ca1-8756-e81919574357.png">

Please have a look at this.

**Comment by ccoenen** [comment]
Sheogorath and I have since left this project. I'm not sure if this particular collection still exists, sorry.
