### ISSUE TITLE
Migrate bootstrap to version 4

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#874]
We currently use bootstrap version 3.3.7. This seems to be the last bootstrap version of 3.x.

We should upgrade to the latest stable bootstrap version 4.

Migration guide: https://getbootstrap.com/docs/4.1/migration/

**Comment by jackycute** [comment]
This might be hard, lots of class names have changed and has different concept.
And I've made all UI look like bootstrap 3, this upgrade only can be done thoroughly not partially in bootstrap itself.
But yeah, it would be brilliant if we can upgrade to bootstrap 4!
