### ISSUE TITLE
Snippet import from Gitlab does not work any more

### ISSUE THREAD

**Issue by Kecksdose** [hackmdio/codimd#887]
Hi all,

we authenticate CodiMD with our self-hosted Gitlab Server, which works perfectly fine. In one of our last updates of Gitlab, we noticed the "import snippet" option from CodiMD broke. We are unable to select a project where to import from.

We tried to update CodiMD, but this did not help (see the exact versions below).

CodiMD version: 1.2.0 (updated from 1.0.1-ce, installed via the docker image)
Gitlab version: 11.0.1 (Community Edition)

**Comment by SISheogorath** [comment]
Seems like the newest GitLab version no longer supports API v3.

So we need to update some code for v4.

If you want to try it yourself, or someone else wants to do that, have a look at:

https://github.com/hackmdio/codimd/blob/b1d1f469de7d5df8b58c9dee94b23c1cf7527b91/public/js/index.js#L966-L998

https://github.com/hackmdio/codimd/blob/b1d1f469de7d5df8b58c9dee94b23c1cf7527b91/public/js/index.js#L1017-L1051

Maybe replacing v3 with v4 works, needs some validation with a gitlab backend.

**Comment by ccoenen** [comment]
Strictly speaking, it's not a bug, as Gitlab has removed an API endpoint we were using. Still: It's broken and needs to get fixed. With the guidance provided by @SISheogorath this might be a straightforward change, I'd encourage you to try to submit a fix :-)

**Comment by Kecksdose** [comment]
I tried to set up CodiMD locally on my laptop, but unfortunately, the GitLab server from our group redirects me to the wrong place when I authorise via Gitlab.

Lets say our gitlab domain is `gitlab.example.com`. Inside GitLab, the redirection points to `gitlab.example.com/auth/gitlab/callback`. When I start CodiMD locally, node serves to port 3000. In the browser, the site appears at `localhost:3000`. The connection to our GitLab server works, after typing my password the following error appears:

```
The redirect URI included is not valid.
```

The domain it wants to redirect is 

```
http://localhost:3000/auth/gitlab/callback&scope=api&client_id=<many numbers and letters here>
```

Here are my configs:
```json
        "gitlab": {
            "baseURL": "https://gitlab.example.com",
            "clientID": "somenumbers",
            "clientSecret": "evenmorenumbers",
            "scope": "api"
        },
        "email": false,
        "domain": "localhost:3000"
```

Do you know how could I avoid this issue?

**Comment by SISheogorath** [comment]
You have to point the redirect to your CodiMD instance. So you should tell GitLab to redirect to `http://localhost:3000/auth/gitlab/callback`

This even works when you GitLab Instance can't reach your CodiMD instance so it's not a problem when you are behind NAT or something. So fixing the redirect URL should fix the whole thing :)

**Comment by micedre** [comment]
I have done some tests with gitlab v4 api and it seems changing v3 by v4 (or getting it by an option) is working. I am just wondering if there is a reason to use snippets in a project (`/projects/:i/snippets`) and not directly the `/snippets` endpoint (linked to the user directly) ?
