### ISSUE TITLE
CodiMD core languages and maintainers

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#889]
We recently introduced [POEditor](https://poeditor.com/join/project/1OpGjF2Jir) as platform for translation work.

Now we noticed during the last release, that we may want to declare some core languages where phrases have to be translated for a release.

As these languages should become release blockers, we want to have maintainers that can be notified to translate the new phrases in around a week.

To become a translation maintainer I think 3 things are required:
- Having an account on POEditor and being assigned to the language
- Checking your mail account on a regular basis
- Being available on Matrix in [#codimd:matrix.org](https://matrix.to/#/#codimd:matrix.org) to get notifications

Please comment below if you want to become a language maintainer by mentioning your matrix name, your POEditor name and what language you want to take of.

**Comment by SISheogorath** [comment]
Awesome @filosofikode! I'll make sure it makes it to the next release :)

**Comment by SISheogorath** [comment]
@filosofikode could you provide the Indonesian name for the Indonedian language? Since we usually put the native language name into the selection field :)

**Comment by filosofikode** [comment]
Bahasa Indonesia
