### ISSUE TITLE
adapting AsciiDoc

### ISSUE THREAD

**Issue by asdfg0280** [hackmdio/codimd#898]
# AsciiDoc doesn't work on HackMD

I want to work HackMD to manipulate adoc file.

But, HackMD only manipulate markdown now.

So, If this repository can be adapt adoc, plz implement AsciiDoc file.

**Comment by ccoenen** [comment]
Hi @asdfg0280, asciidoc has been proposed [before](https://github.com/hackmdio/codimd/issues/30#issuecomment-359951749) and we decided against it as an additional renderer. There will not be two renderers alongside each other.

There is an [adoc fork of HackMD](https://github.com/hackergarten/hackadoc), but it hasn't been updated for half a year.

If you need highlighting or asciidoc sections within CodiMD documents, that might be a whole other topic, this could be realized as a plugin as soon as we have something like a plugin system. Issue #787 is tracking it, but nobody is actively working on it at the moment.

**Comment by msgilligan** [comment]
I'd love to see something like HackMD that works with AsciiDoc(tor).

**Comment by andrewssobral** [comment]
Hello guys, any news about this thread ? same for me, I'd love to see something like HackMD that works with AsciiDoc.
Thanks
