### ISSUE TITLE
/config is served with a text/html Content-Type instead of a js one

### ISSUE THREAD

**Issue by douardda** [hackmdio/codimd#900]
on my setup, hackmd (1.2.0) is served via a reverse proxy (apache).
hackmd itself is installed via docker ( https://github.com/hackmdio/docker-hackmd debian version )

I have a security setup on my proxy that always insert the header 
`
  X-Content-Type-Options nosniff
`

Since the `/config` endpoint advertises wrongly its mime type, it prevents modern browsers to actually load this as a js script from the `<script>` tag.

On of the consequences is that, the global config not being loaded, the version is not available, making the "you need to reload this page" popup appear each and every time (since the doc version is compared to null) a document is loaded.

**Comment by SISheogorath** [comment]
This known and already fixed in master. See https://github.com/hackmdio/codimd/pull/883

**Comment by douardda** [comment]
I've seen this PR but it was not clear whether that the config endpoint was also concerned by this fix (which is clear only is you read the diff).

Anyway, thanks a lot.
