### ISSUE TITLE
don't show picture after give pic url

### ISSUE THREAD

**Issue by huahuayu** [hackmdio/codimd#909]
this is the picture I want to paste in hackmd, http://od3p9hvyr.bkt.clouddn.com/2018-07-31_14-19-42.jpg, I use the syntax: `![](http://od3p9hvyr.bkt.clouddn.com/2018-07-31_14-19-42.jpg) ` nothing showed in the preview perspective. Please check.

**Comment by jackycute** [comment]
For the issues of HackMD.io, please file in
https://github.com/hackmdio/hackmd-io-issues/issues

I just checked the image link you provided to us, the image link didn't send `Content-type` or `Content-length` headers and the link should use SSL (`https://`) protocol for https site.

**Comment by huahuayu** [comment]
@jackycute but if you click the link, the pic can be shown in a new window, no problem. Why it's can't show in hackmd, it's just a picture, why emphasis https？

**Comment by jackycute** [comment]
That's restricted by browser security, using not https protocol in https site is exposing mixed security content.
In other hand, we prefetch the image, which if the headers didn't send correctly will automatically failed. That's also for security.

**Comment by huahuayu** [comment]
what I want to do is just to attach an image, I upload it to qiniu.com a cloud storage provider, can be visited by the browser but get it to paste in hackmd not working.

What's more, when upload image through the toolbar(the camera  button), also not woking, what I got is a text `![Uploading file..._rv0ph4hux]()` , although 10 mins passed, it's still a text.

**Comment by huahuayu** [comment]
imgur 我使用全局代理(shadowsockets，IP切到香港), 上传图片也没用。You can see that, it's a big problem.

**Comment by huahuayu** [comment]
不通过hackmd.io上传，我自己去imgur注册了账号，然后上传，获得外链也行。但是如果imgur被墙了，我自己访问没问题，但是其他在大陆的人就访问不了。还是想用七牛云，http存图片应该可以吧。这又不关乎账号之类的敏感信息。

**Comment by jackycute** [comment]
I mean, you need to use SSL for image links. We can't solve that, its built-in browser security feature which will block ajax non-SSL requests.
