### ISSUE TITLE
Community call - Let's meet!

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#911]
We have over 3500 stars on GitHub close to 4000 but we almost know no one of you. It would be nice if we could change this and get closer together.

The probably most important aspect of an open source project is the community. The community is usually a subset of the combination of the user-base and developers of the project. We started to get some people together on [Matrix](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org) / [Riot](https://riot.im/app/#/room/#codimd:matrix.org) but I don't think that these few people represent the majority of CodiMD users and developers.

So we want to get some people together to talk. During a community call. The medium will probably be a video conference.

Topics that we may want to talk about:

- Who is the "community"?
- On going progress with 1.3.0
- How can we attract more contributors?
- What long term goals do we have for CodiMD?

It's mostly casual talk, it's nothing that is announced, it's more about who is this "community" we are talking about and with and what do you and me want CodiMD to be in the future. There won't be a recording of the talk and there won't be any real decisions but definitely something that may leads to final decisions later on.

<details>
<summary>old dates (please ignore)</summary>

I consider 3 possible times for such a call:

- 8am CEST (2pm CST / 11pm PDT)
- 4pm CEST (10pm CST / 7am PDT)
- 8pm CEST (2am CEST / 11am PDT)

And on what days? Well either the upcoming Sunday (5th August 2018, while I would scratch the 4pm CEST here) or Monday (6th August 2018). [*Here you play around with the times a bit.*](https://www.timeanddate.com/worldclock/meetingtime.html?day=5&month=8&year=2018&p1=83&p2=241&p3=224&iv=0)

~~**Upcoming call: [First Sunday in September (2018-09-02) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=9&day=2&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**~~

~~**Upcoming call: [First Sunday in October (2018-10-07) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=10&day=7&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**~~

~~**Upcoming call: [First Sunday in November (2018-11-04) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=11&day=4&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**~~
</details>

**Upcoming call: [First Sunday in December(2018-12-02) 7pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=12&day=2&hour=19&min=0&sec=0&p1=83&p2=241&p3=224)**

I'm open for suggestions and alternative days. I hope we can make something out of this :)

**Comment by SISheogorath** [comment]
After thinking about it and also talking with @ccoenen, we decided to do this on a more regular basis. Right now we consider every first sunday of a month for a community call.

And since this basically means that sunday is the day, I would like to do the first call tonight(2018-08-05) at 8pm CEST. No problem if you miss it, we still have one next month, but I would really welcome it to hang out with more than 2 people ^^

It's your chance to tell us what you want/like/think and our chance to talk with you about things :)

See you tonight :wave:

**Comment by SISheogorath** [comment]
Call starts in around 15 minutes using Jitsi. Please join us over here:
https://meet.jit.si/CodiMD

**Comment by SISheogorath** [comment]
Since this worked so "great", we'll have our next call on the first Sunday in September (2018-09-02). See you there :wave:

**Comment by SISheogorath** [comment]
Friendly remember that this is upcoming this week. :wave:

**Comment by ccoenen** [comment]
Same Jitsi-Link as last time?

**Comment by SISheogorath** [comment]
Yes, same link. Same time. Collides with my London time, but I think should be doable :)

**Comment by SISheogorath** [comment]
Any further requests for topics to talk about?

**Comment by ccoenen** [comment]
Is 1800UTC / 2000CEST correct?

**Comment by ccoenen** [comment]
Hi everyone. We'll start at 20:00 UTC / 22:00 CEST. There's been an unplanned delay. I'd like to apologize for everyone who waited for the call to start. So, from the time of posting this, around 1:45 hours.

We'll meet in the Jitsi-Channel (Video/Audio conference): https://meet.jit.si/CodiMD
You can also join us on riot (Chat): https://riot.im/app/#/room/#codimd:matrix.org

**Comment by SISheogorath** [comment]
Sorry for that I didn't make it to the call. Collided with some activities with my London trip that took longer than planned.

I'll be around on the next call.

As far as I could hear from people who attended the call there was some positive feedback from the community and from the HackMD team about how things works. For those who attended it, it would be nice to give a little summary here :)

I look forward to make our community more coming together and having fun building CodiMD :)

**Comment by SISheogorath** [comment]
Just scheduled the next call for the **[first sunday of October (2018-10-07) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=10&day=7&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**

Safe the date and participate :)

**Comment by SISheogorath** [comment]
Friendly reminder: Next community call is upcoming **[upcoming Sunday (2018-10-07) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=10&day=7&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**.

Feel free to join us and talk with out about [the future of CodiMD](https://github.com/hackmdio/codimd/issues/969), features and changes in [`1.3.0`](https://github.com/hackmdio/codimd/milestone/17), as well as topics of community organisation and getting started in CodiMD development.

Everyone is welcome. To join, to provide ideas, to listen and to participate now and in our future development. I hope to meet you there :) Would be awesome!

**Comment by ccoenen** [comment]
Sorry I'll be late

**Comment by SISheogorath** [comment]
So the next community call is, given we follow the current pattern, planned for [first Sunday in November(2018-11-04) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=11&day=4&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)

Would be awesome to see you around :)

**Comment by SISheogorath** [comment]
Friendly reminder: The next call is on the **[upcoming Sunday in November(2018-11-04) 6pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=11&day=4&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)**.

Feel free to join us to talk about the current state of [`1.3.0`](https://github.com/hackmdio/codimd/milestone/17), best practices to setup instances of CodiMD, and how to get started to develop CodiMD.

You are welcome to join and enjoy the evening with us. Share your story, ask your questions, bring up your ideas for CodiMD and its community. I hope to meet you there!

**Comment by SISheogorath** [comment]
:man_facepalming: Hey guys, I made it to completely forget about the time change from summer to winter time and it's impact on our community call. Moving it from 6pm UTC to 7pm UTC or for those who wonder: From 8pm CEST to 8pm CET.

We should talk about the time for the next one to make sure this doesn't happen again

**Comment by SISheogorath** [comment]
First of all here is the [document we used during the last community call](https://demo.codimd.org/s/rJvWoTEn7), it's not a protocol but it hopefully reflects a bit what we talked about.

The next community call is on **[first Sunday in December(2018-12-02) 7pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=12&day=2&hour=19&min=0&sec=0&p1=83&p2=241&p3=224)**.

We'll talk about the [`1.3.0`](https://github.com/hackmdio/codimd/milestone/17) release, our ongoing progress towards a [community forum](https://github.com/hackmdio/codimd/issues/998) and the distribution of [CodiMD stickers](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$15420350321061440JyxSc:matrix.org).

Some more details in our ongoing [agenda/meeting note](https://demo.codimd.org/RVB3-hlqQl2MReRyDHb6Bw), which we use to prepare and during the call.

As always it's your chance to join and meet the community, influence the future development, and having a good time with us!

**Comment by SISheogorath** [comment]
Friendly reminder: The next call is on **[upcoming Sunday in December(2018-12-02) 7pm UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2018&month=12&day=2&hour=19&min=0&sec=0&p1=83&p2=241&p3=224)**.

[Agenda and Meeting notes](https://demo.codimd.org/RVB3-hlqQl2MReRyDHb6Bw) can be found on our demo instance if you have any topic you want to discuss, feel free to add.

Also feel free to join us, to discuss and work out some details and goals for [`1.4.0`](https://github.com/hackmdio/codimd/milestone/20), meeting the community or just having a nice evening. It's your chance to make the difference.

**Comment by ccoenen** [comment]
@SISheogorath should we schedule another one for 3.3.2019 19:00 UTC (20:00 MEZ)?

**Comment by SISheogorath** [comment]
@ccoenen Sounds like a plan, even when I don't really have anything newsworthy. Maybe there is something by the community?

Would love to see some points collected for an agenda :)

**Comment by ccoenen** [comment]
Next community call: [3.3.2019 19:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=03&day=3&hour=19&min=0&sec=0&p1=83&p2=241&p3=224) (unless we have nothing to discuss)!
Collect topics in this document: https://demo.codimd.org/TZd9zd6fT9il505uKjCICQ

**Comment by ccoenen** [comment]
If you have been subscribed to this issue to be notified of community calls, please take a look at this issue in our new repository and subscribe there! https://github.com/codimd/server/issues/16

Next Community call will be on 2019-04-07 (upcoming sunday)!
