### ISSUE TITLE
Screen stuck while editing large document

### ISSUE THREAD

**Issue by johnroyer** [hackmdio/codimd#914]
I am editing a document which size is about 10 KB. 

Screen stuck when I adding or deleting words. Especially some keyword like `<` , `"` . Everything goes fine without error after screen stuck.

This problem does not occur when I edit general documents.

Info: 

- Hackmd version:  https://hackmd.io current version (2018-08-07)
- Browser: Chrome 68.0.3440.84
- View: Editor + HTML view in 2 column (`?both` parameter in URL)

----

Is it possible cause by these jobs below ? 

- syntax highlight
- HTML render

**Comment by jackycute** [comment]
For HackMD.io issues, please report in https://github.com/hackmdio/hackmd-io-issues/issues

I can't be sure what cause the freeze according the info you've provided.
Please give us a detailed example or note link.

Thanks!
