### ISSUE TITLE
[feature] Interactively toggling of todo list checkboxes

### ISSUE THREAD

**Issue by quite** [hackmdio/codimd#921]
Wow, would it be cool if it would be possible to interactively toggle the checkboxes rendered from `- [ ] foo` on a note such as:

  https://hackmd-ce.herokuapp.com/2QHIfEOvQGKJxRzlPnH_Bw

With write through to the source markdown. Instant todo list! Perhaps this would mess up permissions, and the note would requirement some setting for whether checkboxes should be read-only for non-logged in users, or so. I have only tried codimd for a few moments so far, and just thought of this...

**Comment by ccoenen** [comment]
In firefox, this works alright:

![toggle gif](https://user-images.githubusercontent.com/124909/44211909-5c2f2900-a16a-11e8-9462-b21c54a136eb.gif)

**Comment by ccoenen** [comment]
what doesn't work (but should be added in my opinion) is clicking the text next to the checkbox. This would require wrapping the text in a label and using its `for=""` attribute.

**Comment by jackycute** [comment]
@ccoenen 
So it was intended not to toggle the checkbox with the text, because you will need to select the text from time to time.

**Comment by ccoenen** [comment]
This is no problem at all? 
(video made from [this test page](https://mdn.github.io/learning-area/html/forms/html-form-structure/fieldset-legend.html) )
Firefox:
![select-legend gif](https://user-images.githubusercontent.com/124909/44212891-dbbdf780-a16c-11e8-8911-67b8f8eac7b6.gif)
(selecting from the middle of text works, too, as seen in the chrome video, i just forgot to test it)

Chrome:
![select-legend-2 gif](https://user-images.githubusercontent.com/124909/44212947-fbedb680-a16c-11e8-80a2-50b30fa17d9c.gif)

**Comment by quite** [comment]
Aha. It does not work using the precise URL that I get when clicking `Publish`. But indeed on the edit-URL I get when clicking the little pen. So, linking to this may be fine for me. We could close this...
