### ISSUE TITLE
Markdown syntax doesn't generate `title` text

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/codimd#922]
This issue is similar to #638 , but with the `title` attribute of the `img` element instead of the `alt` attribute.

The following markup:

```
![Taiwan No.1](https://i.imgur.com/fefdJO5.png "Taiwan No.1")
```

renders to

```html
<p class="part" data-startline="142" data-endline="142">
    <img src="https://i.imgur.com/fefdJO5.png" alt="Taiwan No.1" class="">
</p>
```

The `title` attribute isn't rendered according to [standard Markdown specification](https://daringfireball.net/projects/markdown/syntax#img)

Thanks in advance!

**Comment by ccoenen** [comment]
Interestingly, the same works fine in https://markdown-it.github.io/ (i.e. there the `title=""` attribute is generated).

**Comment by jackycute** [comment]
Hmm, we use `js-xss` to whitelisting allow HTML tags and attributes, maybe we should take a look on that.

**Comment by ccoenen** [comment]
Here's one place where image tags are processed, but it's related to the data URI. The default seems to allow title tags: (can be tested live here: https://jsxss.com/en/try.html )

**Comment by jackycute** [comment]
I just test on https://hackmd-ce.herokuapp.com/Ik-rec4lS6mkaMO3xTLSIw
But everything looks fine to me on Chrome 68 (macOS Sierra)

**Comment by ccoenen** [comment]
![grafik](https://user-images.githubusercontent.com/124909/44307288-02b03f80-a3a0-11e8-93af-da929e71f8ca.png)

**Comment by Lin-Buo-Ren** [comment]
I cannot reproduce it now :-/, anyway thanks for the effort.

**Comment by jackycute** [comment]
Feel free to re-open this if you find any special case to reproduce 👍

**Comment by ccoenen** [comment]
Don't worry :-) If the issue ever comes back, just reopen this, and we'll have another look!
