### ISSUE TITLE
CodiMD on Cloudron

### ISSUE THREAD

**Issue by gramakri** [hackmdio/codimd#923]
Hi CodiMD team, thanks for this fantastic project! Works great and we use it every day ourselves.

We wanted to inform you that we made a CodiMD app package for Cloudron (Cloudron is a platform for running self-hosted web apps). The code for the package itself is at https://git.cloudron.io/cloudron/codimd-app/. We have automated tests as well to test updates in the tests/ directory. The initial package was made thanks to Dick Tang and Felix Bartels.

If you want to try it, you can install CodiMD from our demo instance at https://my-demo.cloudron.me (username: cloudron password: cloudron).

Would be great it if you could add us to one of the installation methods to advertise it a bit.

**Comment by SISheogorath** [comment]
Nice work, I just checked it and it looks like you worked out something great!

Just as hint, this should be obsolete with version 1.2.0:
https://git.cloudron.io/cloudron/codimd-app/blob/master/Dockerfile#L28

Apart from that :+1: I'll merge the PR later today :)

**Comment by gramakri** [comment]
Thanks!

**Comment by SISheogorath** [comment]
@gramakri Could you have a look at your cloudron versions? We are at [1.2.1](https://github.com/hackmdio/codimd/releases/tag/1.2.1) soon [1.3.0](https://github.com/hackmdio/codimd/milestone/17). You should update as soon as possible and please keeping track of new CodiMD versions.

I recommend to join our [Matrix channel](https://matrix.to/#/#codimd:matrix.org) or subscribe to the [release feed](http://github.com/hackmdio/codimd/releases.atom).

**Comment by gramakri** [comment]
@SISheogorath Thanks for checking on this :+1: We are on 1.2.1 which we released on Oct 8. https://cloudron.io/appstatus.html tracks our publishing status across all apps. BTW, https://git.cloudron.io/cloudron/codimd-app/tree/master is our codi source code just in case you are looking at the wrong code.

We use an app called [releasebell](https://releasebell.com/) internally to track all the upstream releases!

**Comment by SISheogorath** [comment]
Ohh, got confused by your internal versioning, because there was the last commit saying "Version 1.1.0". Now I realized that it's your own version string, not the CodiMD one :D

Sorry for wrong alert ^^

By the way, nice tool you have there, have to look into that, seems to be handy :+1:
