### ISSUE TITLE
Add docs for generic oauth2

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#930]
We noticed that some how the generic OAUTH2 method slipped into the codebase [(okay, I admit, I merged it)](https://github.com/hackmdio/codimd/pull/784) without any real documentation. Neither in README nor in any other guide document.

We should add these docs as soon as possible.

@pferreir would you mind to write at least a little reference documentation for the README?

**Comment by pferreir** [comment]
Hi @SISheogorath,
I can take care of the docs 😉

**Comment by ccoenen** [comment]
#987 was a fortunate little accident 🌲
