### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by rmst** [hackmdio/codimd#935]
HTTPS already allows for safe encrypted transfer of data from the user's browser to the server. On the server however the data is decrypted into plaintext again. That allows everyone with access to the server to access all notebooks of all users. A better option for private notebooks would be to (symmetrically) encrypt them in the user's browser with a key only available to the user and then store to encrypted notebook on the server. For shared notebooks the situation would be more complicated but not impossible to solve.

Do you think encryption of private notebooks would be feasible?

**Comment by SISheogorath** [comment]
Please have a look at https://github.com/hackmdio/codimd/issues/138

**Comment by ccoenen** [comment]
I would suggest to continue in issue 138, there's a lot of pros and cons already in there. I'm not against this, but at least "bad admin" is not solved by encryption (longer writeup is in #138, please let's debate there!). Encryption could (depending on the implementation) protect against a third party attacking the server (and gaining access to the database. Long story short: if somebody makes a proposal I'd certainly take a look at it. This is the kind of feature that would need a debate about conceptual changes before actually writing code - in my opinion.

**Comment by rmst** [comment]
Oups sorry, didn't see that. I'll comment there, thanks!
