### ISSUE TITLE
Demo instance and heroku limits

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/codimd#941]
As most of you know we run https://hackmd-ce.herokuapp.com as our test/demo instance.

It also provides some nice input to us when it comes to CSP and similar things that may break in a release, since it's always running the latest master.

A few weeks ago we were informed that we reached the limit of our DB plan which is 10000 rows in Postgres due to the Heroku hobby plan.

I removed a ton of empty notes and some that were short and contained the word "test". This brought us down to ~9000.

This week we had again such an notification and we cleaned it up to ~9800 rows again. Finally today we got another one, since we are again over the limits.

---

Why I tell this is because I currently see three options:

1. We top up the plan and spend some money on it. That would be $9 for 10M rows vs the current 10K.

2. We can reset the instance. Removing all content from it and start with an empty DB, this would of course also reset the limits. But everyone who stored anything on this instance would lose their notes.

3. We can migrate the demo instance to an own host (I can provide the needed infrastructure and setup). This just involves some hassle with Postgres, but should be doable.

So what do you think is the right way to go? (Please keep in mind we have 1 week to figure it out before the `INSERT` privilege will be removed)

/cc @jackycute @ccoenen

**Comment by ccoenen** [comment]
3 sounds like a good option, if (AND ONLY IF!) this is fine with you.

I'm not very fond of 2, I don't think losing existing data is a good idea.

Option 4 could be to disallow new notes on hackmd-ce and just create an entirely new instance somewhere else. We could make it clear that notes get deleted once per month or so, which would essentially circumvent the 10K-Limit for a while.

**Comment by davidmehren** [comment]
Actually, as a user I would expect a demo instance to be regularly wiped and therefore don't store anything important there. So maybe backup the db and clean the instance?

**Comment by ccoenen** [comment]
I don't know if everybody was aware it was a demo instance, also it has the "old" name, so it is a good excuse the register the new one.

**Comment by ccoenen** [comment]
Here's one thing I'd like to see preserved somehow: https://hackmd-ce.herokuapp.com/FXNPgKWnQ4iUekqiS6E8FA#

**Comment by SISheogorath** [comment]
I setup a first test instance for the demo setup today.

Now I wonder if I want to put it behind Cloudflare or not.

While I understand that a lot of people dislike Cloudflare it's a useful tool. It can safe me some bandwidth and this way load from the setup as well as act as a CDN.

While it's a nogo to use it when sensitive information is involved, since it's a demo instance, I hope no one puts sensetive information there and this way consider it as an option.

What do you think?

**Comment by ccoenen** [comment]
Demo-instance is, what puts it into "okay" territory for me. (not fond of, but I totally understand why it's useful. Partly because of [this recent gem](https://www.troyhunt.com/serverless-to-the-max-doing-big-things-for-small-dollars-with-cloudflare-workers-and-azure-functions/), describing how 99+% of server capacity was saved.)

**Comment by SISheogorath** [comment]
The Demo instance was moved to https://demo.codimd.org/

**Comment by ttheuer** [comment]
Maybe add some text that says the instance will be reset regularly (if that is how it will work)?
