### ISSUE TITLE
Group Documents in Folders

### ISSUE THREAD

**Issue by Quving** [hackmdio/codimd#949]
**Userstory**
As a user of hackmd.io , I would like to have the feature to group documents in folders in order to keep a overview over many documents. This implicits the possibility to apply crud-operations on folders.

I would be happy to receive response! :)

Thanks a lot
Quving

**Comment by SISheogorath** [comment]
For issues, feature requests and similar for hackmd.io please use the HackMD.io issue tracker:

https://github.com/hackmdio/hackmd-io-issues/issues

This is the CodiMD issue tracker that is for the free software version of former HackMD (CE).

**Comment by jackycute** [comment]
Hi @Quving 
Thanks for giving us suggestion!
However, for HackMD.io issues, please report in hackmdio/hackmd-io-issues/issues

Thanks 😄

**Comment by Quving** [comment]
> Hi @Quving
> Thanks for giving us suggestion!
> However, for HackMD.io issues, please report in hackmdio/hackmd-io-issues/issues
> 
> Thanks 😄

Ooops. I will create the issue again. :)
