### ISSUE TITLE
using ''@'localhost' denied (mysql)

### ISSUE THREAD

**Issue by nitwhiz** [hackmdio/codimd#951]
are the settings for db or dbURL in config.json ignored?
it always uses no user and no password when doing npm start.

**Comment by SISheogorath** [comment]
How do your settings look like?

**Comment by nitwhiz** [comment]
```
{
        "production": {
                "domain": "mydomain.xyz",
                "urlPath": "notes",
                "host": "localhost",
                "port": 8090,
                "dbURL": "mysql://codimd:<password>@localhost:3306/codimd",
                "allowOrigin": ["localhost", "mydomain.xyz"],
                "allowAnonymousEdits": false,
                "defaultPermission": "private",
                "uploadsPath": "./public/uploads",
                "documentMaxLength": 67108864,
                "email": false,
                "allowEmailRegister": false
        }
}
```

**Comment by SISheogorath** [comment]
Mhm to be honest, it looks fine to me. Do you start CodiMD with `NODE_ENV=production`?

Like `NODE_ENV=production npm start`?

Probably you want to start into production environment but didn't tell codimd to do so. so either use `NODE_ENV=production npm start` or `npm start --production`

**Comment by nitwhiz** [comment]
`npm start --production` did it for me, thanks a lot! :)
