### ISSUE TITLE
USECDN=false works on pads, but not the main page

### ISSUE THREAD

**Issue by almereyda** [hackmdio/codimd#953]
When using the `USECDN=false` flag, pads are delivered without the JavaScript from any CDN.

Yet the main page will still include Cloudflare et al. assets.

**Comment by SISheogorath** [comment]
Which assets do you mean? I just checked our demo instance: https://demo.codimd.org

Seems to be fine to me. Can you provide some details what assets you found?

**Comment by almereyda** [comment]
Oh, seems having been a caching issue. Both front pages on pad.degrowth.net and hack.allmende.io now only load local assets.

**Comment by ccoenen** [comment]
thanks for reporting back :-)
