### ISSUE TITLE
Export Gitlab Snippets 400 error visibility does not have a valid value

### ISSUE THREAD

**Issue by mouson** [hackmdio/codimd#986]
When I export snippet to GitLab (11.3.1) send a request to my private GitLab host

ENV:
Codimd 1.2.1
GitLab 11.3.1
CMD_GITLAB_VERSION=v4

request:

snippets?access_token=xxxxxxxxxx

```
title: test snippet
file_name: test_snippet.md
code: some content
===
some things
visibility_level: 0
visibility: 
```
----------

Response

```
{"error":"visibility does not have a valid value"}
```

**Comment by mouson** [comment]
visibility needs 

visibility | Description
-- | --
private | The snippet is visible only the snippet creator
internal | The snippet is visible for any logged in user
public | The snippet can be accessed without any authentication



ref: [Project snippets \| GitLab](https://docs.gitlab.com/ce/api/project_snippets.html)

**Comment by SISheogorath** [comment]
Interested in providing a patch? Would be nice to see a contribution :)

https://github.com/hackmdio/codimd/blob/c03b42d5d4f804d0cdbaf00c5eb426ca95f2a1cf/lib/response.js#L580-L609

Sounds like a good issue to get started ^^

**Comment by micedre** [comment]
Sorry, it's probably my fault, I do not have time to verify but I believe changing the line in https://github.com/hackmdio/codimd/blob/466dc9bc21305c51bd954eb19269485ea9d94bb5/public/js/index.js#L1482    to

       visibility: $('#snippetExportModalVisibility').val() === '0' ? 'private' : ($('#snippetExportModalVisibility').val() === '10' ? 'internal' : 'public')

should work.
