### ISSUE TITLE
Proposition - Setup a discourse instance for the community

### ISSUE THREAD

**Issue by unteem** [hackmdio/codimd#998]
Following, the last community call we discussed about getting more contributions from the community and what could be the communication channels. It seems that there is a need for a proper place for the community. As for today, there is already a Matrix channel while it is great for live discussions, it is not that easy to have long discussion there, it can involve a lot of scrolling in the history.

So the idea is to setup a discourse forum which could be the main channel, or at least one of the main, for official announcements, discussions, users to ask questions etc. Discourse can also be configured as a mailing list for those that are more into mailing list and is pretty user-friendly for a forum.

There are a lot of open source projects out there that we can get inspiration from:
[nextcloud](https://help.nextcloud.com)

- [letsencrypt](https://community.letsencrypt.org/)
- [kubernetes](https://discuss.kubernetes.io/)
- [rocket.chat](https://forums.rocket.chat/)
- [mattermost](https://forum.mattermost.org)

...

So let us know what you think about this proposal, at least if you are against it.

First question what url?

- community.codimd.org
- forum.codimd.org
- discourse.codimd.org
- discuss.codimd.org
- suggestions?

I vote for community.codimd.org :)

**Comment by ccoenen** [comment]
I like the "community" subdomain. But I'd be happy with "forum" or any of the others as well. Who could run this? I have no idea how much maintenance discourse needs, I just faintly remember it being a Rails project.

**Comment by SISheogorath** [comment]
During the call @unteem said he would host and maintain it. I'm completely fine with that ^^

**Comment by SISheogorath** [comment]
I think it's fine when we keep this open until next Sunday (14th of October 2018) and if no one is strongly against it, we take the results and start working on it :)

**Comment by ccoenen** [comment]
(oooh the irony. tagging somthing to enhance discussion with discussion :o) )

**Comment by almereyda** [comment]
My preferences in this order:

- meta.
- talk.
- users.
- discuss.
- community.
- agora.
- forum.
- discourse.

**Comment by SISheogorath** [comment]
For all who want to suggest names I would like to see a ranking of what names you like.

The idea to select the final name looks like this:

Everyone can rank as many names as he/she likes. The post with the most names is the one I'll start with. Going upwards I'll put points to the ranks. So given that there are 5 names, the last will get 1, the the one before the last 2 and so on. Until the first name gets 5 points.

Now we go to the other list and apply these points from up to down (so in our example the first position gets 5 points, the second 4, and so on) until the list ends. Then we simply sum up the points per name and the name with the most points wins.

Sounds fair? I hope so. If you post multiple lists, I'll only use the last one you posted, so if you want to extent your list, use the edit button ;)

When I start to evaluate, I'll lock this issue.

And now let's see how it works out!

**Comment by ccoenen** [comment]
Why not simply start at the top of the list and count down from 5? Once you reach 0, the other names will just not receive any other points. If I were to push an entry, I could list 99 names, and my top pick would receive 99 points.

Regardless of counting: here's my list:

* community.
* users.
* meta.
* forum.
* talk.
* discuss.
* discourse.
* agora.

**Comment by SISheogorath** [comment]
|subdomain   |points             |
|----------------|------------------|
|`community` |8 + 4 + 8 = 20|
|`forum`         |5 + 2 + 7 = 14|
|`meta`          |6 + 8 = 14      |
|`discuss`      |3 + 5 + 5 = 13|
|`users`         |7 + 6 = 13      |
|`talk`             |4 + 7 + = 11  |
|`discourse`   |2 + 1 + 6 = 9 |
|`agora`         |1+ 3 = 4        |

So `community.codimd.org` it is :)

**Comment by SISheogorath** [comment]
I just delegated the subdomain `community.codimd.org` to Indie Hosters who will sponsor and maintain the discourse instance :)

Thanks a lot of that!
