### ISSUE TITLE
code highlight for Rust is not correct

### ISSUE THREAD

**Issue by tigercosmos** [hackmdio/codimd#999]
when there is lifetime syntax `'a` in Rust code, the highlight will be wrong

correct one as Github show
```rust
fn foo<'a>(s: &'a str) -> &'a str { }
```

what hackmd shows

<img width="429" alt="2018-10-08 2 24 05" src="https://user-images.githubusercontent.com/18013815/46594475-e27e4080-cb05-11e8-86c0-a1c82fa202e5.png">

**Comment by SISheogorath** [comment]
Did you specify that it's rust when you added the code block?

See https://demo.codimd.org/svlYRM33SZCwhfvfO2Fs-Q?view

**Comment by tigercosmos** [comment]
Yes, I do. But I am under hackmd.io
<img width="1079" alt="2018-10-08 3 08 49" src="https://user-images.githubusercontent.com/18013815/46595660-1bb9af00-cb0c-11e8-8f66-1eeaefdd756c.png">

**Comment by jackycute** [comment]
Hi @tigercosmos, for hackmd.io related issues, please report to hackmdio/hackmd-io-issues. This repository is for CodiMD (which is previously called HackMD CE, Community Edition)

**Comment by tigercosmos** [comment]
sorry. I find the wrong repo.
